export const Congression = [
    {value: "Alabama 1st", title: "Alabama 1st"},
    {value: "Alabama 2nd", title: "Alabama 2nd"},
    {value: "Alabama 3rd", title: "Alabama 3rd"},
    {value: "Alabama 4th", title: "Alabama 4th"},
    {value: "Alabama 5th", title: "Alabama 5th"},
    {value: "Alabama 6th", title: "Alabama 6th"},
    {value: "Alabama 7th", title: "Alabama 7th"},
    {value: "Alaska At Large", title: "Alaska At Large"},
    {value: "American Samoa Delegate", title: "American Samoa Delegate"},
    {value: "Arizona 1st", title: "Arizona 1st"},
    {value: "Arizona 2nd", title: "Arizona 2nd"},
    {value: "Arizona 3rd", title: "Arizona 3rd"},
    {value: "Arizona 4th", title: "Arizona 4th"},
    {value: "Arizona 5th", title: "Arizona 5th"},
    {value: "Arizona 6th", title: "Arizona 6th"},
    {value: "Arizona 7th", title: "Arizona 7th"},
    {value: "Arizona 8th", title: "Arizona 8th"},
    {value: "Arizona 9th", title: "Arizona 9th"},
    {value: "Arkansas 1st", title: "Arkansas 1st"},
    {value: "Arkansas 2nd", title: "Arkansas 2nd"},
    {value: "Arkansas 3rd", title: "Arkansas 3rd"},
    {value: "Arkansas 4th", title: "Arkansas 4th"},
    {value: "California 10th", title: "California 10th"},
    {value: "California 11th", title: "California 11th"},
    {value: "California 12th", title: "California 12th"},
    {value: "California 13th", title: "California 13th"},
    {value: "California 14th", title: "California 14th"},
    {value: "California 15th", title: "California 15th"},
    {value: "California 16th", title: "California 16th"},
    {value: "California 17th", title: "California 17th"},
    {value: "California 18th", title: "California 18th"},
    {value: "California 19th", title: "California 19th"},
    {value: "California 1st", title: "California 1st"},
    {value: "California 20th", title: "California 20th"},
    {value: "California 21st", title: "California 21st"},
    {value: "California 22nd", title: "California 22nd"},
    {value: "California 23rd", title: "California 23rd"},
    {value: "California 24th", title: "California 24th"},
    {value: "California 25th", title: "California 25th"},
    {value: "California 26th", title: "California 26th"},
    {value: "California 27th", title: "California 27th"},
    {value: "California 28th", title: "California 28th"},
    {value: "California 29th", title: "California 29th"},
    {value: "California 2nd", title: "California 2nd"},
    {value: "California 30th", title: "California 30th"},
    {value: "California 31st", title: "California 31st"},
    {value: "California 32nd", title: "California 32nd"},
    {value: "California 33rd", title: "California 33rd"},
    {value: "California 34th", title: "California 34th"},
    {value: "California 35th", title: "California 35th"},
    {value: "California 36th", title: "California 36th"},
    {value: "California 37th", title: "California 37th"},
    {value: "California 38th", title: "California 38th"},
    {value: "California 39th", title: "California 39th"},
    {value: "California 3rd", title: "California 3rd"},
    {value: "California 40th", title: "California 40th"},
    {value: "California 41st", title: "California 41st"},
    {value: "California 42nd", title: "California 42nd"},
    {value: "California 43rd", title: "California 43rd"},
    {value: "California 44th", title: "California 44th"},
    {value: "California 45th", title: "California 45th"},
    {value: "California 46th", title: "California 46th"},
    {value: "California 47th", title: "California 47th"},
    {value: "California 48th", title: "California 48th"},
    {value: "California 49th", title: "California 49th"},
    {value: "California 4th", title: "California 4th"},
    {value: "California 50th", title: "California 50th"},
    {value: "California 51st", title: "California 51st"},
    {value: "California 52nd", title: "California 52nd"},
    {value: "California 5th", title: "California 5th"},
    {value: "California 6th", title: "California 6th"},
    {value: "California 7th", title: "California 7th"},
    {value: "California 8th", title: "California 8th"},
    {value: "California 9th", title: "California 9th"},
    {value: "Colorado 1st", title: "Colorado 1st"},
    {value: "Colorado 2nd", title: "Colorado 2nd"},
    {value: "Colorado 3rd", title: "Colorado 3rd"},
    {value: "Colorado 4th", title: "Colorado 4th"},
    {value: "Colorado 5th", title: "Colorado 5th"},
    {value: "Colorado 6th", title: "Colorado 6th"},
    {value: "Colorado 7th", title: "Colorado 7th"},
    {value: "Colorado 8th", title: "Colorado 8th"},
    {value: "Connecticut 1st", title: "Connecticut 1st"},
    {value: "Connecticut 2nd", title: "Connecticut 2nd"},
    {value: "Connecticut 3rd", title: "Connecticut 3rd"},
    {value: "Connecticut 4th", title: "Connecticut 4th"},
    {value: "Connecticut 5th", title: "Connecticut 5th"},
    {value: "Delaware At Large", title: "Delaware At Large"},
    {
        value: "District of Columbia Delegate",
        title: "District of Columbia Delegate",
    },
    {value: "Florida 10th", title: "Florida 10th"},
    {value: "Florida 11th", title: "Florida 11th"},
    {value: "Florida 12th", title: "Florida 12th"},
    {value: "Florida 13th", title: "Florida 13th"},
    {value: "Florida 14th", title: "Florida 14th"},
    {value: "Florida 15th", title: "Florida 15th"},
    {value: "Florida 16th", title: "Florida 16th"},
    {value: "Florida 17th", title: "Florida 17th"},
    {value: "Florida 18th", title: "Florida 18th"},
    {value: "Florida 19th", title: "Florida 19th"},
    {value: "Florida 1st", title: "Florida 1st"},
    {value: "Florida 20th", title: "Florida 20th"},
    {value: "Florida 21st", title: "Florida 21st"},
    {value: "Florida 22nd", title: "Florida 22nd"},
    {value: "Florida 23rd", title: "Florida 23rd"},
    {value: "Florida 24th", title: "Florida 24th"},
    {value: "Florida 25th", title: "Florida 25th"},
    {value: "Florida 26th", title: "Florida 26th"},
    {value: "Florida 27th", title: "Florida 27th"},
    {value: "Florida 28th", title: "Florida 28th"},
    {value: "Florida 2nd", title: "Florida 2nd"},
    {value: "Florida 3rd", title: "Florida 3rd"},
    {value: "Florida 4th", title: "Florida 4th"},
    {value: "Florida 5th", title: "Florida 5th"},
    {value: "Florida 6th", title: "Florida 6th"},
    {value: "Florida 7th", title: "Florida 7th"},
    {value: "Florida 8th", title: "Florida 8th"},
    {value: "Florida 9th", title: "Florida 9th"},
    {value: "Georgia 10th", title: "Georgia 10th"},
    {value: "Georgia 11th", title: "Georgia 11th"},
    {value: "Georgia 12th", title: "Georgia 12th"},
    {value: "Georgia 13th", title: "Georgia 13th"},
    {value: "Georgia 14th", title: "Georgia 14th"},
    {value: "Georgia 1st", title: "Georgia 1st"},
    {value: "Georgia 2nd", title: "Georgia 2nd"},
    {value: "Georgia 3rd", title: "Georgia 3rd"},
    {value: "Georgia 4th", title: "Georgia 4th"},
    {value: "Georgia 5th", title: "Georgia 5th"},
    {value: "Georgia 6th", title: "Georgia 6th"},
    {value: "Georgia 7th", title: "Georgia 7th"},
    {value: "Georgia 8th", title: "Georgia 8th"},
    {value: "Georgia 9th", title: "Georgia 9th"},
    {value: "Guam Delegate", title: "Guam Delegate"},
    {value: "Hawaii 1st", title: "Hawaii 1st"},
    {value: "Hawaii 2nd", title: "Hawaii 2nd"},
    {value: "Idaho 1st", title: "Idaho 1st"},
    {value: "Idaho 2nd", title: "Idaho 2nd"},
    {value: "Illinois 10th", title: "Illinois 10th"},
    {value: "Illinois 11th", title: "Illinois 11th"},
    {value: "Illinois 12th", title: "Illinois 12th"},
    {value: "Illinois 13th", title: "Illinois 13th"},
    {value: "Illinois 14th", title: "Illinois 14th"},
    {value: "Illinois 15th", title: "Illinois 15th"},
    {value: "Illinois 16th", title: "Illinois 16th"},
    {value: "Illinois 17th", title: "Illinois 17th"},
    {value: "Illinois 1st", title: "Illinois 1st"},
    {value: "Illinois 2nd", title: "Illinois 2nd"},
    {value: "Illinois 3rd", title: "Illinois 3rd"},
    {value: "Illinois 4th", title: "Illinois 4th"},
    {value: "Illinois 5th", title: "Illinois 5th"},
    {value: "Illinois 6th", title: "Illinois 6th"},
    {value: "Illinois 7th", title: "Illinois 7th"},
    {value: "Illinois 8th", title: "Illinois 8th"},
    {value: "Illinois 9th", title: "Illinois 9th"},
    {value: "Indiana 1st", title: "Indiana 1st"},
    {value: "Indiana 2nd", title: "Indiana 2nd"},
    {value: "Indiana 3rd", title: "Indiana 3rd"},
    {value: "Indiana 4th", title: "Indiana 4th"},
    {value: "Indiana 5th", title: "Indiana 5th"},
    {value: "Indiana 6th", title: "Indiana 6th"},
    {value: "Indiana 7th", title: "Indiana 7th"},
    {value: "Indiana 8th", title: "Indiana 8th"},
    {value: "Indiana 9th", title: "Indiana 9th"},
    {value: "Iowa 1st", title: "Iowa 1st"},
    {value: "Iowa 2nd", title: "Iowa 2nd"},
    {value: "Iowa 3rd", title: "Iowa 3rd"},
    {value: "Iowa 4th", title: "Iowa 4th"},
    {value: "Kansas 1st", title: "Kansas 1st"},
    {value: "Kansas 2nd", title: "Kansas 2nd"},
    {value: "Kansas 3rd", title: "Kansas 3rd"},
    {value: "Kansas 4th", title: "Kansas 4th"},
    {value: "Kentucky 1st", title: "Kentucky 1st"},
    {value: "Kentucky 2nd", title: "Kentucky 2nd"},
    {value: "Kentucky 3rd", title: "Kentucky 3rd"},
    {value: "Kentucky 4th", title: "Kentucky 4th"},
    {value: "Kentucky 5th", title: "Kentucky 5th"},
    {value: "Kentucky 6th", title: "Kentucky 6th"},
    {value: "Louisiana 1st", title: "Louisiana 1st"},
    {value: "Louisiana 2nd", title: "Louisiana 2nd"},
    {value: "Louisiana 3rd", title: "Louisiana 3rd"},
    {value: "Louisiana 4th", title: "Louisiana 4th"},
    {value: "Louisiana 5th", title: "Louisiana 5th"},
    {value: "Louisiana 6th", title: "Louisiana 6th"},
    {value: "Maine 1st", title: "Maine 1st"},
    {value: "Maine 2nd", title: "Maine 2nd"},
    {value: "Maryland 1st", title: "Maryland 1st"},
    {value: "Maryland 2nd", title: "Maryland 2nd"},
    {value: "Maryland 3rd", title: "Maryland 3rd"},
    {value: "Maryland 4th", title: "Maryland 4th"},
    {value: "Maryland 5th", title: "Maryland 5th"},
    {value: "Maryland 6th", title: "Maryland 6th"},
    {value: "Maryland 7th", title: "Maryland 7th"},
    {value: "Maryland 8th", title: "Maryland 8th"},
    {value: "Massachusetts 1st", title: "Massachusetts 1st"},
    {value: "Massachusetts 2nd", title: "Massachusetts 2nd"},
    {value: "Massachusetts 3rd", title: "Massachusetts 3rd"},
    {value: "Massachusetts 4th", title: "Massachusetts 4th"},
    {value: "Massachusetts 5th", title: "Massachusetts 5th"},
    {value: "Massachusetts 6th", title: "Massachusetts 6th"},
    {value: "Massachusetts 7th", title: "Massachusetts 7th"},
    {value: "Massachusetts 8th", title: "Massachusetts 8th"},
    {value: "Massachusetts 9th", title: "Massachusetts 9th"},
    {value: "Michigan 10th", title: "Michigan 10th"},
    {value: "Michigan 11th", title: "Michigan 11th"},
    {value: "Michigan 12th", title: "Michigan 12th"},
    {value: "Michigan 13th", title: "Michigan 13th"},
    {value: "Michigan 1st", title: "Michigan 1st"},
    {value: "Michigan 2nd", title: "Michigan 2nd"},
    {value: "Michigan 3rd", title: "Michigan 3rd"},
    {value: "Michigan 4th", title: "Michigan 4th"},
    {value: "Michigan 5th", title: "Michigan 5th"},
    {value: "Michigan 6th", title: "Michigan 6th"},
    {value: "Michigan 7th", title: "Michigan 7th"},
    {value: "Michigan 8th", title: "Michigan 8th"},
    {value: "Michigan 9th", title: "Michigan 9th"},
    {value: "Minnesota 1st", title: "Minnesota 1st"},
    {value: "Minnesota 2nd", title: "Minnesota 2nd"},
    {value: "Minnesota 3rd", title: "Minnesota 3rd"},
    {value: "Minnesota 4th", title: "Minnesota 4th"},
    {value: "Minnesota 5th", title: "Minnesota 5th"},
    {value: "Minnesota 6th", title: "Minnesota 6th"},
    {value: "Minnesota 7th", title: "Minnesota 7th"},
    {value: "Minnesota 8th", title: "Minnesota 8th"},
    {value: "Mississippi 1st", title: "Mississippi 1st"},
    {value: "Mississippi 2nd", title: "Mississippi 2nd"},
    {value: "Mississippi 3rd", title: "Mississippi 3rd"},
    {value: "Mississippi 4th", title: "Mississippi 4th"},
    {value: "Missouri 1st", title: "Missouri 1st"},
    {value: "Missouri 2nd", title: "Missouri 2nd"},
    {value: "Missouri 3rd", title: "Missouri 3rd"},
    {value: "Missouri 4th", title: "Missouri 4th"},
    {value: "Missouri 5th", title: "Missouri 5th"},
    {value: "Missouri 6th", title: "Missouri 6th"},
    {value: "Missouri 7th", title: "Missouri 7th"},
    {value: "Missouri 8th", title: "Missouri 8th"},
    {value: "Montana 1st", title: "Montana 1st"},
    {value: "Montana 2nd", title: "Montana 2nd"},
    {value: "Nebraska 1st", title: "Nebraska 1st"},
    {value: "Nebraska 2nd", title: "Nebraska 2nd"},
    {value: "Nebraska 3rd", title: "Nebraska 3rd"},
    {value: "Nevada 1st", title: "Nevada 1st"},
    {value: "Nevada 2nd", title: "Nevada 2nd"},
    {value: "Nevada 3rd", title: "Nevada 3rd"},
    {value: "Nevada 4th", title: "Nevada 4th"},
    {value: "New Hampshire 1st", title: "New Hampshire 1st"},
    {value: "New Hampshire 2nd", title: "New Hampshire 2nd"},
    {value: "New Jersey 10th", title: "New Jersey 10th"},
    {value: "New Jersey 11th", title: "New Jersey 11th"},
    {value: "New Jersey 12th", title: "New Jersey 12th"},
    {value: "New Jersey 1st", title: "New Jersey 1st"},
    {value: "New Jersey 2nd", title: "New Jersey 2nd"},
    {value: "New Jersey 3rd", title: "New Jersey 3rd"},
    {value: "New Jersey 4th", title: "New Jersey 4th"},
    {value: "New Jersey 5th", title: "New Jersey 5th"},
    {value: "New Jersey 6th", title: "New Jersey 6th"},
    {value: "New Jersey 7th", title: "New Jersey 7th"},
    {value: "New Jersey 8th", title: "New Jersey 8th"},
    {value: "New Jersey 9th", title: "New Jersey 9th"},
    {value: "New Mexico 1st", title: "New Mexico 1st"},
    {value: "New Mexico 2nd", title: "New Mexico 2nd"},
    {value: "New Mexico 3rd", title: "New Mexico 3rd"},
    {value: "New York 10th", title: "New York 10th"},
    {value: "New York 11th", title: "New York 11th"},
    {value: "New York 12th", title: "New York 12th"},
    {value: "New York 13th", title: "New York 13th"},
    {value: "New York 14th", title: "New York 14th"},
    {value: "New York 15th", title: "New York 15th"},
    {value: "New York 16th", title: "New York 16th"},
    {value: "New York 17th", title: "New York 17th"},
    {value: "New York 18th", title: "New York 18th"},
    {value: "New York 19th", title: "New York 19th"},
    {value: "New York 1st", title: "New York 1st"},
    {value: "New York 20th", title: "New York 20th"},
    {value: "New York 21st", title: "New York 21st"},
    {value: "New York 22nd", title: "New York 22nd"},
    {value: "New York 23rd", title: "New York 23rd"},
    {value: "New York 24th", title: "New York 24th"},
    {value: "New York 25th", title: "New York 25th"},
    {value: "New York 26th", title: "New York 26th"},
    {value: "New York 2nd", title: "New York 2nd"},
    {value: "New York 3rd", title: "New York 3rd"},
    {value: "New York 4th", title: "New York 4th"},
    {value: "New York 5th", title: "New York 5th"},
    {value: "New York 6th", title: "New York 6th"},
    {value: "New York 7th", title: "New York 7th"},
    {value: "New York 8th", title: "New York 8th"},
    {value: "New York 9th", title: "New York 9th"},
    {value: "North Carolina 10th", title: "North Carolina 10th"},
    {value: "North Carolina 11th", title: "North Carolina 11th"},
    {value: "North Carolina 12th", title: "North Carolina 12th"},
    {value: "North Carolina 13th", title: "North Carolina 13th"},
    {value: "North Carolina 14th", title: "North Carolina 14th"},
    {value: "North Carolina 1st", title: "North Carolina 1st"},
    {value: "North Carolina 2nd", title: "North Carolina 2nd"},
    {value: "North Carolina 3rd", title: "North Carolina 3rd"},
    {value: "North Carolina 4th", title: "North Carolina 4th"},
    {value: "North Carolina 5th", title: "North Carolina 5th"},
    {value: "North Carolina 6th", title: "North Carolina 6th"},
    {value: "North Carolina 7th", title: "North Carolina 7th"},
    {value: "North Carolina 8th", title: "North Carolina 8th"},
    {value: "North Carolina 9th", title: "North Carolina 9th"},
    {value: "North Dakota At Large", title: "North Dakota At Large"},
    {
        value: "Northern Mariana Islands Delegate",
        title: "Northern Mariana Islands Delegate",
    },
    {value: "Ohio 10th", title: "Ohio 10th"},
    {value: "Ohio 11th", title: "Ohio 11th"},
    {value: "Ohio 12th", title: "Ohio 12th"},
    {value: "Ohio 13th", title: "Ohio 13th"},
    {value: "Ohio 14th", title: "Ohio 14th"},
    {value: "Ohio 15th", title: "Ohio 15th"},
    {value: "Ohio 1st", title: "Ohio 1st"},
    {value: "Ohio 2nd", title: "Ohio 2nd"},
    {value: "Ohio 3rd", title: "Ohio 3rd"},
    {value: "Ohio 4th", title: "Ohio 4th"},
    {value: "Ohio 5th", title: "Ohio 5th"},
    {value: "Ohio 6th", title: "Ohio 6th"},
    {value: "Ohio 7th", title: "Ohio 7th"},
    {value: "Ohio 8th", title: "Ohio 8th"},
    {value: "Ohio 9th", title: "Ohio 9th"},
    {value: "Oklahoma 1st", title: "Oklahoma 1st"},
    {value: "Oklahoma 2nd", title: "Oklahoma 2nd"},
    {value: "Oklahoma 3rd", title: "Oklahoma 3rd"},
    {value: "Oklahoma 4th", title: "Oklahoma 4th"},
    {value: "Oklahoma 5th", title: "Oklahoma 5th"},
    {value: "Oregon 1st", title: "Oregon 1st"},
    {value: "Oregon 2nd", title: "Oregon 2nd"},
    {value: "Oregon 3rd", title: "Oregon 3rd"},
    {value: "Oregon 4th", title: "Oregon 4th"},
    {value: "Oregon 5th", title: "Oregon 5th"},
    {value: "Oregon 6th", title: "Oregon 6th"},
    {value: "Pennsylvania 10th", title: "Pennsylvania 10th"},
    {value: "Pennsylvania 11th", title: "Pennsylvania 11th"},
    {value: "Pennsylvania 12th", title: "Pennsylvania 12th"},
    {value: "Pennsylvania 13th", title: "Pennsylvania 13th"},
    {value: "Pennsylvania 14th", title: "Pennsylvania 14th"},
    {value: "Pennsylvania 15th", title: "Pennsylvania 15th"},
    {value: "Pennsylvania 16th", title: "Pennsylvania 16th"},
    {value: "Pennsylvania 17th", title: "Pennsylvania 17th"},
    {value: "Pennsylvania 1st", title: "Pennsylvania 1st"},
    {value: "Pennsylvania 2nd", title: "Pennsylvania 2nd"},
    {value: "Pennsylvania 3rd", title: "Pennsylvania 3rd"},
    {value: "Pennsylvania 4th", title: "Pennsylvania 4th"},
    {value: "Pennsylvania 5th", title: "Pennsylvania 5th"},
    {value: "Pennsylvania 6th", title: "Pennsylvania 6th"},
    {value: "Pennsylvania 7th", title: "Pennsylvania 7th"},
    {value: "Pennsylvania 8th", title: "Pennsylvania 8th"},
    {value: "Pennsylvania 9th", title: "Pennsylvania 9th"},
    {
        value: "Puerto Rico Resident Commissioner",
        title: "Puerto Rico Resident Commissioner",
    },
    {value: "Rhode Island 1st", title: "Rhode Island 1st"},
    {value: "Rhode Island 2nd", title: "Rhode Island 2nd"},
    {value: "South Carolina 1st", title: "South Carolina 1st"},
    {value: "South Carolina 2nd", title: "South Carolina 2nd"},
    {value: "South Carolina 3rd", title: "South Carolina 3rd"},
    {value: "South Carolina 4th", title: "South Carolina 4th"},
    {value: "South Carolina 5th", title: "South Carolina 5th"},
    {value: "South Carolina 6th", title: "South Carolina 6th"},
    {value: "South Carolina 7th", title: "South Carolina 7th"},
    {value: "South Dakota At Large", title: "South Dakota At Large"},
    {value: "Tennessee 1st", title: "Tennessee 1st"},
    {value: "Tennessee 2nd", title: "Tennessee 2nd"},
    {value: "Tennessee 3rd", title: "Tennessee 3rd"},
    {value: "Tennessee 4th", title: "Tennessee 4th"},
    {value: "Tennessee 5th", title: "Tennessee 5th"},
    {value: "Tennessee 6th", title: "Tennessee 6th"},
    {value: "Tennessee 7th", title: "Tennessee 7th"},
    {value: "Tennessee 8th", title: "Tennessee 8th"},
    {value: "Tennessee 9th", title: "Tennessee 9th"},
    {value: "Texas 10th", title: "Texas 10th"},
    {value: "Texas 11th", title: "Texas 11th"},
    {value: "Texas 12th", title: "Texas 12th"},
    {value: "Texas 13th", title: "Texas 13th"},
    {value: "Texas 14th", title: "Texas 14th"},
    {value: "Texas 15th", title: "Texas 15th"},
    {value: "Texas 16th", title: "Texas 16th"},
    {value: "Texas 17th", title: "Texas 17th"},
    {value: "Texas 18th", title: "Texas 18th"},
    {value: "Texas 19th", title: "Texas 19th"},
    {value: "Texas 1st", title: "Texas 1st"},
    {value: "Texas 20th", title: "Texas 20th"},
    {value: "Texas 21st", title: "Texas 21st"},
    {value: "Texas 22nd", title: "Texas 22nd"},
    {value: "Texas 23rd", title: "Texas 23rd"},
    {value: "Texas 24th", title: "Texas 24th"},
    {value: "Texas 25th", title: "Texas 25th"},
    {value: "Texas 26th", title: "Texas 26th"},
    {value: "Texas 27th", title: "Texas 27th"},
    {value: "Texas 28th", title: "Texas 28th"},
    {value: "Texas 29th", title: "Texas 29th"},
    {value: "Texas 2nd", title: "Texas 2nd"},
    {value: "Texas 30th", title: "Texas 30th"},
    {value: "Texas 31st", title: "Texas 31st"},
    {value: "Texas 32nd", title: "Texas 32nd"},
    {value: "Texas 33rd", title: "Texas 33rd"},
    {value: "Texas 34th", title: "Texas 34th"},
    {value: "Texas 35th", title: "Texas 35th"},
    {value: "Texas 36th", title: "Texas 36th"},
    {value: "Texas 37th", title: "Texas 37th"},
    {value: "Texas 38th", title: "Texas 38th"},
    {value: "Texas 3rd", title: "Texas 3rd"},
    {value: "Texas 4th", title: "Texas 4th"},
    {value: "Texas 5th", title: "Texas 5th"},
    {value: "Texas 6th", title: "Texas 6th"},
    {value: "Texas 7th", title: "Texas 7th"},
    {value: "Texas 8th", title: "Texas 8th"},
    {value: "Texas 9th", title: "Texas 9th"},
    {value: "Utah 1st", title: "Utah 1st"},
    {value: "Utah 2nd", title: "Utah 2nd"},
    {value: "Utah 3rd", title: "Utah 3rd"},
    {value: "Utah 4th", title: "Utah 4th"},
    {value: "Vermont At Large", title: "Vermont At Large"},
    {value: "Virgin Islands Delegate", title: "Virgin Islands Delegate"},
    {value: "Virginia 10th", title: "Virginia 10th"},
    {value: "Virginia 11th", title: "Virginia 11th"},
    {value: "Virginia 1st", title: "Virginia 1st"},
    {value: "Virginia 2nd", title: "Virginia 2nd"},
    {value: "Virginia 3rd", title: "Virginia 3rd"},
    {value: "Virginia 4th", title: "Virginia 4th"},
    {value: "Virginia 5th", title: "Virginia 5th"},
    {value: "Virginia 6th", title: "Virginia 6th"},
    {value: "Virginia 7th", title: "Virginia 7th"},
    {value: "Virginia 8th", title: "Virginia 8th"},
    {value: "Virginia 9th", title: "Virginia 9th"},
    {value: "Washington 10th", title: "Washington 10th"},
    {value: "Washington 1st", title: "Washington 1st"},
    {value: "Washington 2nd", title: "Washington 2nd"},
    {value: "Washington 3rd", title: "Washington 3rd"},
    {value: "Washington 4th", title: "Washington 4th"},
    {value: "Washington 5th", title: "Washington 5th"},
    {value: "Washington 6th", title: "Washington 6th"},
    {value: "Washington 7th", title: "Washington 7th"},
    {value: "Washington 8th", title: "Washington 8th"},
    {value: "Washington 9th", title: "Washington 9th"},
    {value: "West Virginia 1st", title: "West Virginia 1st"},
    {value: "West Virginia 2nd", title: "West Virginia 2nd"},
    {value: "Wisconsin 1st", title: "Wisconsin 1st"},
    {value: "Wisconsin 2nd", title: "Wisconsin 2nd"},
    {value: "Wisconsin 3rd", title: "Wisconsin 3rd"},
    {value: "Wisconsin 4th", title: "Wisconsin 4th"},
    {value: "Wisconsin 5th", title: "Wisconsin 5th"},
    {value: "Wisconsin 6th", title: "Wisconsin 6th"},
    {value: "Wisconsin 7th", title: "Wisconsin 7th"},
    {value: "Wisconsin 8th", title: "Wisconsin 8th"},
    {value: "Wyoming At Large", title: "Wyoming At Large"},
];
export const partyName = [
    {value: "Republican", title: "Republican"},
    {value: "Democrat", title: "Democrat"}
];
