const stateList = [
  //{ value: "", title: "Location State" },
  { value: "Alabama", title: "Alabama" },
  { value: "Alaska", title: "Alaska" },
  { value: "Arizona", title: "Arizona" },
  { value: "Arkansas", title: "Arkansas" },
  { value: "California", title: "California" },
  { value: "Colorado", title: "Colorado" },
  { value: "Connecticut", title: "Connecticut" },
  { value: "Delaware", title: "Delaware" },
  { value: "District of Columbia", title: "District of Columbia" },
  { value: "Florida", title: "Florida" },
  { value: "Georgia", title: "Georgia" },
  { value: "Hawaii", title: "Hawaii" },
  { value: "Idaho", title: "Idaho" },
  { value: "Illinois", title: "Illinois" },
  { value: "Indiana", title: "Indiana" },
  { value: "Iowa", title: "Iowa" },
  { value: "Kansas", title: "Kansas" },
  { value: "Kentucky", title: "Kentucky" },
  { value: "Louisiana", title: "Louisiana" },
  { value: "Maine", title: "Maine" },
  { value: "Maryland", title: "Maryland" },
  { value: "Massachusetts", title: "Massachusetts" },
  { value: "Michigan", title: "Michigan" },
  { value: "Minnesota", title: "Minnesota" },
  { value: "Mississippi", title: "Mississippi" },
  { value: "Missouri", title: "Missouri" },
  { value: "Montana", title: "Montana" },
  { value: "Nebraska", title: "Nebraska" },
  { value: "Nevada", title: "Nevada" },
  { value: "New Hampshire", title: "New Hampshire" },
  { value: "New Jersey", title: "New Jersey" },
  { value: "New Mexico", title: "New Mexico" },
  { value: "New York", title: "New York" },
  { value: "North Carolina", title: "North Carolina" },
  { value: "North Dakota", title: "North Dakota" },
  { value: "Ohio", title: "Ohio" },
  { value: "Oklahoma", title: "Oklahoma" },
  { value: "Ontario", title: "Ontario" },
  { value: "Oregon", title: "Oregon" },
  { value: "Pennsylvania", title: "Pennsylvania" },
  { value: "Puerto Rico", title: "Puerto Rico" },
  { value: "Rhode Island", title: "Rhode Island" },
  { value: "South Carolina", title: "South Carolina" },
  { value: "South Dakota", title: "South Dakota" },
  { value: "Tennessee", title: "Tennessee" },
  { value: "Texas", title: "Texas" },
  { value: "Utah", title: "Utah" },
  { value: "Vermont", title: "Vermont" },
  { value: "Virginia", title: "Virginia" },
  { value: "Washington", title: "Washington" },
  { value: "West Virginia", title: "West Virginia" },
  { value: "Wisconsin", title: "Wisconsin" },
  { value: "Wyoming", title: "Wyoming" },
  { value: "Alberta", title: "Alberta" },
  { value: "America Samoa", title: "America Samoa" },
  { value: "American Samoa", title: "American Samoa" },
  { value: "British Columbia", title: "British Columbia" },
  { value: "District Of Columbia", title: "District Of Columbia" },
  { value: "Foreign Countries", title: "Foreign Countries" },
  { value: "Guam", title: "Guam" },
  { value: "Honduras", title: "Honduras" },
  { value: "Manitoba", title: "Manitoba" },
  { value: "Mexico", title: "Mexico" },
  { value: "New Brunswick", title: "New Brunswick" },
  { value: "Newfoundland", title: "Newfoundland" },
  { value: "Northern Mariana Islands", title: "Northern Mariana Islands" },
  { value: "Northwest Territory", title: "Northwest Territory" },
  { value: "Nova Scotia", title: "Nova Scotia" },
  { value: "Panama Canal Zone", title: "Panama Canal Zone" },
  { value: "Prince Edward Island", title: "Prince Edward Island" },
  { value: "Quebec", title: "Quebec" },
  { value: "Saskatchewan", title: "Saskatchewan" },
  { value: "U.S. Virgin Islands", title: "U.S. Virgin Islands" },
  { value: "Virgin Islands", title: "Virgin Islands" },
  { value: "Yukon", title: "Yukon" },
];

//  [

//     { value: "", title: "Jurisdiction State" },
//     { value: 'US_DE', title: 'US_DE' },
//     { value: 'US_CA', title: 'US_CA' },
//     { value: 'US_RI', title: 'US_RI' },
//     { value: 'US_WA', title: 'US_WA' },
//     { value: 'US_OH', title: 'US_OH' },
//     { value: 'US_MI', title: 'US_MI' },
//     { value: 'US_IN', title: 'US_IN' },
//     { value: 'US_NC', title: 'US_NC' },
//     { value: 'US_NJ', title: 'US_NJ' },
//     { value: 'US_TX', title: 'US_TX' },
//     { value: 'US_VA', title: 'US_VA' },
//     { value: 'US_PA', title: 'US_PA' },
//     { value: 'US_NY', title: 'US_NY' },
//     { value: 'US_MD', title: 'US_MD' },
//     { value: 'US_CO', title: 'US_CO' },
//     { value: 'US_AZ', title: 'US_AZ' },
//     { value: 'US_OR', title: 'US_OR' },
//     { value: 'US_MN', title: 'US_MN' },
//     { value: 'US_IL', title: 'US_IL' },
//     { value: 'US_FL', title: 'US_FL' },
//     { value: 'US_TN', title: 'US_TN' },
//     { value: 'US_AR', title: 'US_AR' },
//     { value: 'US_MO', title: 'US_MO' },
//     { value: 'US_UT', title: 'US_UT' },
//     { value: 'US_DC', title: 'US_DC' },
//     { value: 'US_GA', title: 'US_GA' },
//     { value: 'US_ID', title: 'US_ID' },
//     { value: 'US_CT', title: 'US_CT' },
//     { value: 'US_MA', title: 'US_MA' },
//     { value: 'US_MS', title: 'US_MS' },
//     { value: 'US_VT', title: 'US_VT' },
//     { value: 'US_WI', title: 'US_WI' },
//     { value: 'US_ME', title: 'US_ME' },
//     { value: 'US_NV', title: 'US_NV' },
//     { value: 'US_OK', title: 'US_OK' },
//     { value: 'US_LA', title: 'US_LA' },
//     { value: 'US_IA', title: 'US_IA' },
//     { value: 'US_KS', title: 'US_KS' },
//     { value: 'US_AL', title: 'US_AL' },
//     { value: 'US_SC', title: 'US_SC' },
//     { value: 'US_MT', title: 'US_MT' },
//     { value: 'US_NH', title: 'US_NH' },
//     { value: 'US_NE', title: 'US_NE' },
//     { value: 'US_HI', title: 'US_HI' },
//     { value: 'US_AK', title: 'US_AK' },
//     { value: 'US_WY', title: 'US_WY' },
//     { value: 'US_SD', title: 'US_SD' },
//     { value: 'US_KY', title: 'US_KY' },
//     { value: 'US_NM', title: 'US_NM' },
//     { value: 'US_ND', title: 'US_ND' },
//     { value: 'US_WV', title: 'US_WV' },

// ];

const JstateList = [
  // { value: '', title: 'Legal Jurisdiction State' },
  { value: "US_AK", title: "US_AK" },
  { value: "US_AL", title: "US_AL" },
  { value: "US_AR", title: "US_AR" },
  { value: "US_AZ", title: "US_AZ" },
  { value: "US_CA", title: "US_CA" },
  { value: "US_CO", title: "US_CO" },
  { value: "US_CT", title: "US_CT" },
  { value: "US_DC", title: "US_DC" },
  { value: "US_DE", title: "US_DE" },
  { value: "US_FL", title: "US_FL" },
  { value: "US_GA", title: "US_GA" },
  { value: "US_HI", title: "US_HI" },
  { value: "US_IA", title: "US_IA" },
  { value: "US_ID", title: "US_ID" },
  { value: "US_IL", title: "US_IL" },
  { value: "US_IN", title: "US_IN" },
  { value: "US_KS", title: "US_KS" },
  { value: "US_KY", title: "US_KY" },
  { value: "US_LA", title: "US_LA" },
  { value: "US_MA", title: "US_MA" },
  { value: "US_MD", title: "US_MD" },
  { value: "US_ME", title: "US_ME" },
  { value: "US_MI", title: "US_MI" },
  { value: "US_MN", title: "US_MN" },
  { value: "US_MO", title: "US_MO" },
  { value: "US_MS", title: "US_MS" },
  { value: "US_MT", title: "US_MT" },
  { value: "US_NC", title: "US_NC" },
  { value: "US_ND", title: "US_ND" },
  { value: "US_NE", title: "US_NE" },
  { value: "US_NH", title: "US_NH" },
  { value: "US_NJ", title: "US_NJ" },
  { value: "US_NM", title: "US_NM" },
  { value: "US_NV", title: "US_NV" },
  { value: "US_NY", title: "US_NY" },
  { value: "US_OH", title: "US_OH" },
  { value: "US_OK", title: "US_OK" },
  { value: "US_OR", title: "US_OR" },
  { value: "US_PA", title: "US_PA" },
  { value: "US_RI", title: "US_RI" },
  { value: "US_SC", title: "US_SC" },
  { value: "US_SD", title: "US_SD" },
  { value: "US_TN", title: "US_TN" },
  { value: "US_TX", title: "US_TX" },
  { value: "US_UT", title: "US_UT" },
  { value: "US_VA", title: "US_VA" },
  { value: "US_VT", title: "US_VT" },
  { value: "US_WA", title: "US_WA" },
  { value: "US_WI", title: "US_WI" },
  { value: "US_WV", title: "US_WV" },
  { value: "US_WY", title: "US_WY" },
];
export { stateList, JstateList };
