export const newState = [
  // { value: "", title: "", code: "" },
  { value: "Alabama", title: "Alabama", code: "AL" },
  { value: "Alaska", title: "Alaska", code: "AK" },
  { value: "Arizona", title: "Arizona", code: "AZ" },
  { value: "Arkansas", title: "Arkansas", code: "AR" },
  { value: "California", title: "California", code: "CA" },
  { value: "Colorado", title: "Colorado", code: "CO" },
  { value: "Connecticut", title: "Connecticut", code: "CT" },
  { value: "Delaware", title: "Delaware", code: "DE" },
  { value: "District of Columbia", title: "District of Columbia", code: "DC" },
  { value: "Florida", title: "Florida", code: "FL" },
  { value: "Georgia", title: "Georgia", code: "GA" },
  { value: "Hawaii", title: "Hawaii", code: "HI" },
  { value: "Idaho", title: "Idaho", code: "ID" },
  { value: "Illinois", title: "Illinois", code: "IL" },
  { value: "Indiana", title: "Indiana", code: "IN" },
  { value: "Iowa", title: "Iowa", code: "IA" },
  { value: "Kansas", title: "Kansas", code: "KS" },
  { value: "Kentucky", title: "Kentucky", code: "KY" },
  { value: "Louisiana", title: "Louisiana", code: "LA" },
  { value: "Maine", title: "Maine", code: "ME" },
  { value: "Maryland", title: "Maryland", code: "MD" },
  { value: "Massachusetts", title: "Massachusetts", code: "MA" },
  { value: "Michigan", title: "Michigan", code: "MI" },
  { value: "Minnesota", title: "Minnesota", code: "MN" },
  { value: "Mississippi", title: "Mississippi", code: "MS" },
  { value: "Missouri", title: "Missouri", code: "MO" },
  { value: "Montana", title: "Montana", code: "MT" },
  { value: "Nebraska", title: "Nebraska", code: "NE" },
  { value: "Nevada", title: "Nevada", code: "NV" },
  { value: "New Hampshire", title: "New Hampshire", code: "NH" },
  { value: "New Jersey", title: "New Jersey", code: "NJ" },
  { value: "New Mexico", title: "New Mexico", code: "NM" },
  { value: "New York", title: "New York", code: "NY" },
  { value: "North Carolina", title: "North Carolina", code: "NC" },
  { value: "North Dakota", title: "North Dakota", code: "ND" },
  { value: "Ohio", title: "Ohio", code: "OH" },
  { value: "Oklahoma", title: "Oklahoma", code: "OK" },
  { value: "Ontario", title: "Ontario", code: "ON" },
  { value: "Oregon", title: "Oregon", code: "OR" },
  { value: "Pennsylvania", title: "Pennsylvania", code: "PA" },
  { value: "Puerto Rico", title: "Puerto Rico", code: "PR" },
  { value: "Rhode Island", title: "Rhode Island", code: "RI" },
  { value: "South Carolina", title: "South Carolina", code: "SC" },
  { value: "South Dakota", title: "South Dakota", code: "SD" },
  { value: "Tennessee", title: "Tennessee", code: "TN" },
  { value: "Texas", title: "Texas", code: "TX" },
  { value: "Utah", title: "Utah", code: "UT" },
  { value: "Vermont", title: "Vermont", code: "VT" },
  { value: "Virginia", title: "Virginia", code: "VA" },
  { value: "Washington", title: "Washington", code: "WA" },
  { value: "West Virginia", title: "West Virginia", code: "WV" },
  { value: "Wisconsin", title: "Wisconsin", code: "WI" },
  { value: "Wyoming", title: "Wyoming", code: "WY" },
  { value: "Alberta", title: "Alberta", code: "AB" },
  { value: "America Samoa", title: "America Samoa", code: "AS" },
  { value: "American Samoa", title: "American Samoa", code: "AS" },
  { value: "British Columbia", title: "British Columbia", code: "BC" },
  { value: "District Of Columbia", title: "District Of Columbia", code: "DC" },
  { value: "Foreign Countries", title: "Foreign Countries", code: "FC" },
  { value: "Guam", title: "Guam", code: "GU" },
  { value: "Honduras", title: "Honduras", code: "HN" },
  { value: "Manitoba", title: "Manitoba", code: "MB" },
  { value: "Mexico", title: "Mexico", code: "MX" },
  { value: "New Brunswick", title: "New Brunswick", code: "NB" },
  { value: "Newfoundland", title: "Newfoundland", code: "NL" },
  {
    value: "Northern Mariana Islands",
    title: "Northern Mariana Islands",
    code: "MP",
  },
  { value: "Northwest Territory", title: "Northwest Territory", code: "NT" },
  { value: "Nova Scotia", title: "Nova Scotia", code: "NS" },
  { value: "Panama Canal Zone", title: "Panama Canal Zone", code: "PC" },
  { value: "Prince Edward Island", title: "Prince Edward Island", code: "PE" },
  { value: "Quebec", title: "Quebec", code: "QC" },
  { value: "Saskatchewan", title: "Saskatchewan", code: "SK" },
  { value: "U.S. Virgin Islands", title: "U.S. Virgin Islands", code: "VI" },
  { value: "Virgin Islands", title: "Virgin Islands", code: "VI" },
  { value: "Yukon", title: "Yukon", code: "YK" },
];
