export const bq_location_address_state_name = [
  "Alabama",
  "Alaska",
  "Alberta",
  "Arizona",
  "Arkansas",
  "British Columbia",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "District of Columbia",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Manitoba",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Ontario",
  "Oregon",
  "Pennsylvania",
  "Puerto Rico",
  "Rhode Island",
  "Saskatchewan",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virgin Islands",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
  "America Samoa",
  "American Samoa",
  "Foreign Countries",
  "Guam",
  "Honduras",
  "Labrador",
  "Mexico",
  "New Brunswick",
  "Newfoundland",
  "Northern Mariana Islands",
  "Northwest Territory",
  "Nova Scotia",
  "Panama Canal Zone",
  "Prince Edward Island",
  "Quebec",
  "U.S. Virgin Islands",
  "Yukon",
];
export const bq_location_address_county_name = [
  "Abbeville County",
  "Acadia County",
  "Ada County",
  "Adair County",
  "Adams County",
  "Addison County",
  "Aiken County",
  "Alachua County",
  "Alamance County",
  "Alameda County",
  "Alamosa County",
  "Albany County",
  "Albemarle County",
  "Alcona County",
  "Alcorn County",
  "Alexander County",
  "Alexandria City County",
  "Alfalfa County",
  "Alger County",
  "Allegan County",
  "Allegany County",
  "Alleghany County",
  "Allegheny County",
  "Allen County",
  "Alpena County",
  "Alpine County",
  "Amador County",
  "Amelia County",
  "Amherst County",
  "Amite County",
  "Anchorage County",
  "Anchorage Municipality County",
  "Anderson County",
  "Andrew County",
  "Andrews County",
  "Androscoggin County",
  "Angelina County",
  "Anne Arundel County",
  "Anoka County",
  "Anson County",
  "Antrim County",
  "Apache County",
  "Appanoose County",
  "Appling County",
  "Appomattox County",
  "Aransas County",
  "Arapahoe County",
  "Archer County",
  "Archuleta County",
  "Arenac County",
  "Arkansas County",
  "Arlington County",
  "Armstrong County",
  "Aroostook County",
  "Arroyo County",
  "Ascension County",
  "Ashe County",
  "Ashland County",
  "Ashley County",
  "Ashtabula County",
  "Asotin County",
  "Assumption County",
  "Atascosa County",
  "Atchison County",
  "Athens County",
  "Atkinson County",
  "Atlantic County",
  "Atoka County",
  "Attala County",
  "Audrain County",
  "Auglaize County",
  "Augusta County",
  "Austin County",
  "Autauga County",
  "Avery County",
  "Avoyelles County",
  "Bacon County",
  "Bailey County",
  "Baker County",
  "Baldwin County",
  "Baltimore City County",
  "Baltimore County",
  "Baltimore city County",
  "Bandera County",
  "Banner County",
  "Bannock County",
  "Baraga County",
  "Barbour County",
  "Barnstable County",
  "Barnwell County",
  "Barren County",
  "Barron County",
  "Barrow County",
  "Barry County",
  "Bartholomew County",
  "Barton County",
  "Bartow County",
  "Bastrop County",
  "Bates County",
  "Baxter County",
  "Bay County",
  "Bayamon County",
  "Bayfield County",
  "Baylor County",
  "Beadle County",
  "Bear Lake County",
  "Beaufort County",
  "Beauregard County",
  "Beaver County",
  "Beaverhead County",
  "Becker County",
  "Beckham County",
  "Bedford County",
  "Bee County",
  "Belknap County",
  "Bell County",
  "Belmont County",
  "Beltrami County",
  "Benewah County",
  "Bennington County",
  "Benton County",
  "Benzie County",
  "Bergen County",
  "Berkeley County",
  "Berks County",
  "Berkshire County",
  "Bernalillo County",
  "Berrien County",
  "Bertie County",
  "Bexar County",
  "Bibb County",
  "Bienville County",
  "Big Horn County",
  "Bingham County",
  "Black Hawk County",
  "Blackford County",
  "Bladen County",
  "Blaine County",
  "Blair County",
  "Blanco County",
  "Bleckley County",
  "Blount County",
  "Blue Earth County",
  "Boise County",
  "Bolivar County",
  "Bon Homme County",
  "Bond County",
  "Bonner County",
  "Bonneville County",
  "Boone County",
  "Bosque County",
  "Bossier County",
  "Botetourt County",
  "Boulder County",
  "Bourbon County",
  "Bowie County",
  "Bowman County",
  "Box Butte County",
  "Box Elder County",
  "Boyd County",
  "Boyle County",
  "Bradford County",
  "Bradley County",
  "Branch County",
  "Braxton County",
  "Brazoria County",
  "Brazos County",
  "Bremer County",
  "Brevard County",
  "Brewster County",
  "Bristol County",
  "Broadwater County",
  "Bronx County",
  "Brooke County",
  "Brookings County",
  "Broome County",
  "Broomfield County",
  "Broward County",
  "Brown County",
  "Brule County",
  "Brunswick County",
  "Bryan County",
  "Buchanan County",
  "Bucks County",
  "Buena Vista City County",
  "Buena Vista County",
  "Buena Vista city County",
  "Buffalo County",
  "Bullitt County",
  "Bulloch County",
  "Buncombe County",
  "Bureau County",
  "Burke County",
  "Burleigh County",
  "Burleson County",
  "Burlington County",
  "Burnet County",
  "Butler County",
  "Butte County",
  "Butts County",
  "Cabarrus County",
  "Cabell County",
  "Cache County",
  "Caddo County",
  "Caddo Parish County",
  "Calaveras County",
  "Calcasieu County",
  "Caldwell County",
  "Caledonia County",
  "Calhoun County",
  "Callahan County",
  "Callaway County",
  "Calloway County",
  "Calumet County",
  "Calvert County",
  "Cambria County",
  "Camden County",
  "Cameron County",
  "Camp County",
  "Campbell County",
  "Canadian County",
  "Candler County",
  "Canyon County",
  "Cape Girardeau County",
  "Cape May County",
  "Carbon County",
  "Carlton County",
  "Caroline County",
  "Carroll County",
  "Carson City County",
  "Carson County",
  "Carter County",
  "Carteret County",
  "Carver County",
  "Cascade County",
  "Casey County",
  "Cass County",
  "Cassia County",
  "Castro County",
  "Catahoula County",
  "Catawba County",
  "Catoosa County",
  "Cattaraugus County",
  "Cavalier County",
  "Cayuga County",
  "Cecil County",
  "Cedar County",
  "Ceiba County",
  "Centre County",
  "Cerro Gordo County",
  "Chaffee County",
  "Chambers County",
  "Champaign County",
  "Chariton County",
  "Charles City County",
  "Charles County",
  "Charles Mix County",
  "Charleston County",
  "Charlevoix County",
  "Charlotte County",
  "Charlottesville City County",
  "Charlottesville city County",
  "Chase County",
  "Chatham County",
  "Chattooga County",
  "Chautauqua County",
  "Chaves County",
  "Cheboygan County",
  "Chelan County",
  "Chemung County",
  "Chenango County",
  "Cherokee County",
  "Cherry County",
  "Chesapeake City County",
  "Cheshire County",
  "Chester County",
  "Chesterfield County",
  "Cheyenne County",
  "Chickasaw County",
  "Chicot County",
  "Chilton County",
  "Chippewa County",
  "Chisago County",
  "Chittenden County",
  "Choctaw County",
  "Chouteau County",
  "Christian County",
  "Churchill County",
  "Cibola County",
  "Citrus County",
  "Clackamas County",
  "Claiborne County",
  "Clallam County",
  "Clare County",
  "Clarendon County",
  "Clarion County",
  "Clark County",
  "Clarke County",
  "Clatsop County",
  "Clay County",
  "Clayton County",
  "Clear Creek County",
  "Clearfield County",
  "Cleburne County",
  "Clermont County",
  "Cleveland County",
  "Clinch County",
  "Clinton County",
  "Cloud County",
  "Coahoma County",
  "Cobb County",
  "Cochise County",
  "Cochran County",
  "Cocke County",
  "Coconino County",
  "Codington County",
  "Coffee County",
  "Colbert County",
  "Cole County",
  "Coles County",
  "Colfax County",
  "Colleton County",
  "Collier County",
  "Collin County",
  "Colonial Heights City County",
  "Colorado County",
  "Colquitt County",
  "Columbia County",
  "Columbiana County",
  "Columbus County",
  "Colusa County",
  "Comal County",
  "Comanche County",
  "Concordia County",
  "Contra Costa County",
  "Converse County",
  "Conway County",
  "Cook County",
  "Cooke County",
  "Cooper County",
  "Coos County",
  "Copiah County",
  "Corson County",
  "Cortland County",
  "Coryell County",
  "Coshocton County",
  "Covington County",
  "Coweta County",
  "Cowley County",
  "Cowlitz County",
  "Craig County",
  "Craighead County",
  "Craven County",
  "Crawford County",
  "Creek County",
  "Crenshaw County",
  "Crisp County",
  "Crittenden County",
  "Crook County",
  "Cross County",
  "Crow Wing County",
  "Crowley County",
  "Cullman County",
  "Culpeper County",
  "Cumberland County",
  "Cuming County",
  "Currituck County",
  "Curry County",
  "Custer County",
  "Cuyahoga County",
  "Dade County",
  "Dakota County",
  "Dale County",
  "Dallam County",
  "Dallas County",
  "Dane County",
  "Danville City County",
  "Dare County",
  "Darke County",
  "Darlington County",
  "Dauphin County",
  "Davidson County",
  "Davie County",
  "Daviess County",
  "Davis County",
  "Davison County",
  "Dawson County",
  "Day County",
  "De Baca County",
  "De Kalb County",
  "De Soto County",
  "De Witt County",
  "DeKalb County",
  "Deaf Smith County",
  "Dearborn County",
  "Decatur County",
  "Deer Lodge County",
  "Defiance County",
  "Delaware County",
  "Delta County",
  "Denali County",
  "Dent County",
  "Denton County",
  "Denver County",
  "Des Moines County",
  "Deschutes County",
  "Desha County",
  "Desoto County",
  "Dewey County",
  "Dewitt County",
  "Dickenson County",
  "Dickey County",
  "Dickinson County",
  "Dickson County",
  "Dillon County",
  "Dimmit County",
  "Dinwiddie County",
  "District of Columbia County",
  "Dixon County",
  "Doddridge County",
  "Dodge County",
  "Dolores County",
  "Dona Ana County",
  "Donley County",
  "Dooly County",
  "Door County",
  "Dorchester County",
  "Dougherty County",
  "Douglas County",
  "Drew County",
  "DuPage County",
  "Dubois County",
  "Dubuque County",
  "Duchesne County",
  "Dukes County",
  "Dunn County",
  "Dupage County",
  "Duplin County",
  "Durham County",
  "Dutchess County",
  "Duval County",
  "Dyer County",
  "Eagle County",
  "Early County",
  "East Baton Rouge County",
  "East Carroll County",
  "East Feliciana County",
  "Eastland County",
  "Eaton County",
  "Eau Claire County",
  "Ector County",
  "Eddy County",
  "Edgecombe County",
  "Edgefield County",
  "Edwards County",
  "Effingham County",
  "El Dorado County",
  "El Paso County",
  "Elbert County",
  "Elkhart County",
  "Elko County",
  "Ellis County",
  "Elmore County",
  "Emanuel County",
  "Emery County",
  "Emmet County",
  "Erath County",
  "Erie County",
  "Escambia County",
  "Essex County",
  "Estill County",
  "Etowah County",
  "Evangeline County",
  "Evans County",
  "Fairbanks North Star County",
  "Fairfax City County",
  "Fairfax County",
  "Fairfield County",
  "Falls Church City County",
  "Fannin County",
  "Faribault County",
  "Faulkner County",
  "Fauquier County",
  "Fayette County",
  "Fergus County",
  "Ferry County",
  "Fillmore County",
  "Finney County",
  "Flagler County",
  "Flathead County",
  "Florence County",
  "Floyd County",
  "Fluvanna County",
  "Fond du Lac County",
  "Ford County",
  "Forest County",
  "Forrest County",
  "Forsyth County",
  "Fort Bend County",
  "Fountain County",
  "Franklin City County",
  "Franklin County",
  "Frederick County",
  "Fredericksburg City County",
  "Freeborn County",
  "Freestone County",
  "Fremont County",
  "Fresno County",
  "Frio County",
  "Fulton County",
  "Furnas County",
  "Gadsden County",
  "Gage County",
  "Gaines County",
  "Gallatin County",
  "Gallia County",
  "Galveston County",
  "Garden County",
  "Garfield County",
  "Garland County",
  "Garrard County",
  "Garrett County",
  "Garvin County",
  "Garza County",
  "Gasconade County",
  "Gaston County",
  "Gates County",
  "Geary County",
  "Geauga County",
  "Gem County",
  "Genesee County",
  "Geneva County",
  "George County",
  "Georgetown County",
  "Gibson County",
  "Gila County",
  "Gilchrist County",
  "Gillespie County",
  "Gilmer County",
  "Gilpin County",
  "Glacier County",
  "Glades County",
  "Gladwin County",
  "Glenn County",
  "Gloucester County",
  "Glynn County",
  "Goliad County",
  "Gonzales County",
  "Goochland County",
  "Goodhue County",
  "Gooding County",
  "Gordon County",
  "Goshen County",
  "Grady County",
  "Grafton County",
  "Graham County",
  "Grainger County",
  "Grand County",
  "Grand Forks County",
  "Grand Isle County",
  "Grand Traverse County",
  "Granite County",
  "Grant County",
  "Granville County",
  "Gratiot County",
  "Graves County",
  "Gray County",
  "Grays Harbor County",
  "Grayson County",
  "Greeley County",
  "Green County",
  "Green Lake County",
  "Greenbrier County",
  "Greene County",
  "Greenup County",
  "Greenville County",
  "Greenwood County",
  "Gregg County",
  "Grenada County",
  "Grimes County",
  "Grundy County",
  "Guadalupe County",
  "Guernsey County",
  "Guilford County",
  "Gulf County",
  "Gunnison County",
  "Guthrie County",
  "Gwinnett County",
  "Habersham County",
  "Hale County",
  "Halifax County",
  "Hall County",
  "Hamilton County",
  "Hamlin County",
  "Hampden County",
  "Hampshire County",
  "Hampton City County",
  "Hampton County",
  "Hancock County",
  "Hand County",
  "Hanover County",
  "Haralson County",
  "Hardee County",
  "Hardeman County",
  "Hardin County",
  "Hardy County",
  "Harford County",
  "Harnett County",
  "Harney County",
  "Harris County",
  "Harrison County",
  "Harrisonburg City County",
  "Hart County",
  "Hartford County",
  "Hartley County",
  "Harvey County",
  "Haskell County",
  "Hawaii County",
  "Hays County",
  "Haywood County",
  "Heard County",
  "Hempstead County",
  "Henderson County",
  "Hendricks County",
  "Hendry County",
  "Hennepin County",
  "Henrico County",
  "Henry County",
  "Herkimer County",
  "Hernando County",
  "Hertford County",
  "Hidalgo County",
  "Highland County",
  "Highlands County",
  "Hill County",
  "Hillsborough County",
  "Hillsdale County",
  "Hinds County",
  "Hocking County",
  "Hockley County",
  "Hoke County",
  "Holmes County",
  "Holt County",
  "Honolulu County",
  "Hood County",
  "Hood River County",
  "Hooker County",
  "Hoonah Angoon County",
  "Hopewell City County",
  "Hopkins County",
  "Horry County",
  "Houghton County",
  "Houston County",
  "Howard County",
  "Howell County",
  "Hubbard County",
  "Hudson County",
  "Hudspeth County",
  "Huerfano County",
  "Hughes County",
  "Humboldt County",
  "Hunt County",
  "Hunterdon County",
  "Huntingdon County",
  "Huntington County",
  "Huron County",
  "Hutchinson County",
  "Hyde County",
  "Iberia County",
  "Iberville County",
  "Idaho County",
  "Imperial County",
  "Independence County",
  "Indian River County",
  "Indiana County",
  "Ingham County",
  "Inyo County",
  "Ionia County",
  "Iosco County",
  "Iowa County",
  "Iredell County",
  "Iron County",
  "Iroquois County",
  "Isabella County",
  "Isanti County",
  "Island County",
  "Isle of Wight County",
  "Itasca County",
  "Itawamba County",
  "Izard County",
  "Jack County",
  "Jackson County",
  "James City County",
  "Jasper County",
  "Jayuya County",
  "Jeff Davis County",
  "Jefferson County",
  "Jefferson Davis County",
  "Jefferson Parish County",
  "Jennings County",
  "Jerome County",
  "Jersey County",
  "Jessamine County",
  "Jim Wells County",
  "Jo Daviess County",
  "Johnson County",
  "Johnston County",
  "Jones County",
  "Josephine County",
  "Juab County",
  "Juneau County",
  "Juniata County",
  "Kalamazoo County",
  "Kalkaska County",
  "Kanabec County",
  "Kanawha County",
  "Kandiyohi County",
  "Kane County",
  "Kankakee County",
  "Karnes County",
  "Kauai County",
  "Kaufman County",
  "Kay County",
  "Kearney County",
  "Keith County",
  "Kemper County",
  "Kenai Peninsula County",
  "Kendall County",
  "Kennebec County",
  "Kenosha County",
  "Kent County",
  "Kenton County",
  "Kern County",
  "Kerr County",
  "Kershaw County",
  "Ketchikan Gateway County",
  "Kimball County",
  "King County",
  "Kingfisher County",
  "Kings County",
  "Kingsbury County",
  "Kinney County",
  "Kiowa County",
  "Kit Carson County",
  "Kitsap County",
  "Kittitas County",
  "Klamath County",
  "Kleberg County",
  "Klickitat County",
  "Knox County",
  "Kodiak Island County",
  "Koochiching County",
  "Kootenai County",
  "Kosciusko County",
  "Kossuth County",
  "La Crosse County",
  "La Paz County",
  "La Plata County",
  "La Porte County",
  "La Salle County",
  "Labette County",
  "Lackawanna County",
  "Laclede County",
  "Lafayette County",
  "Lafayette Parish County",
  "Lafourche County",
  "Lagrange County",
  "Lake County",
  "Lamar County",
  "Lamoille County",
  "Lamoure County",
  "Lampasas County",
  "Lancaster County",
  "Lane County",
  "Langlade County",
  "Lapeer County",
  "Laramie County",
  "Larimer County",
  "Larue County",
  "Las Animas County",
  "Las Piedras County",
  "Lassen County",
  "Latah County",
  "Lauderdale County",
  "Laurel County",
  "Laurens County",
  "Lavaca County",
  "Lawrence County",
  "Le Flore County",
  "Le Sueur County",
  "Lea County",
  "Leake County",
  "Leavenworth County",
  "Lebanon County",
  "Lee County",
  "Leelanau County",
  "Leflore County",
  "Lehigh County",
  "Lenawee County",
  "Lenoir County",
  "Leon County",
  "Letcher County",
  "Levy County",
  "Lewis County",
  "Lewis and Clark County",
  "Lexington City County",
  "Lexington County",
  "Liberty County",
  "Licking County",
  "Limestone County",
  "Lincoln County",
  "Linn County",
  "Lipscomb County",
  "Litchfield County",
  "Little River County",
  "Livingston County",
  "Llano County",
  "Logan County",
  "Long County",
  "Lonoke County",
  "Lorain County",
  "Los Alamos County",
  "Los Angeles County",
  "Loudon County",
  "Loudoun County",
  "Louisa County",
  "Lowndes County",
  "Lubbock County",
  "Lucas County",
  "Lumpkin County",
  "Luna County",
  "Luzerne County",
  "Lycoming County",
  "Lynchburg City County",
  "Lyon County",
  "Macomb County",
  "Macon County",
  "Macoupin County",
  "Madera County",
  "Madison County",
  "Mahaska County",
  "Mahoning County",
  "Major County",
  "Malheur County",
  "Manassas City County",
  "Manassas Park City County",
  "Manatee County",
  "Manistee County",
  "Manitowoc County",
  "Marathon County",
  "Marengo County",
  "Maricopa County",
  "Marin County",
  "Marinette County",
  "Marion County",
  "Mariposa County",
  "Marlboro County",
  "Marquette County",
  "Marshall County",
  "Martin County",
  "Martinsville City County",
  "Mason County",
  "Massac County",
  "Matagorda County",
  "Matanuska Susitna County",
  "Maui County",
  "Maury County",
  "Maverick County",
  "Mayes County",
  "McClain County",
  "McCone County",
  "McCook County",
  "McCracken County",
  "McCulloch County",
  "McCurtain County",
  "McDonald County",
  "McDonough County",
  "McDowell County",
  "McDuffie County",
  "McHenry County",
  "McIntosh County",
  "McKean County",
  "McKenzie County",
  "McKinley County",
  "McLean County",
  "McLennan County",
  "McLeod County",
  "McPherson County",
  "Meade County",
  "Mecklenburg County",
  "Mecosta County",
  "Medina County",
  "Meeker County",
  "Mendocino County",
  "Menominee County",
  "Merced County",
  "Mercer County",
  "Meriwether County",
  "Merrick County",
  "Merrimack County",
  "Mesa County",
  "Metcalfe County",
  "Miami County",
  "Miami-Dade County",
  "Middlesex County",
  "Midland County",
  "Mifflin County",
  "Milam County",
  "Millard County",
  "Mille Lacs County",
  "Miller County",
  "Mills County",
  "Milwaukee County",
  "Mineral County",
  "Mingo County",
  "Minidoka County",
  "Minnehaha County",
  "Missaukee County",
  "Mississippi County",
  "Missoula County",
  "Mitchell County",
  "Mobile County",
  "Moffat County",
  "Mohave County",
  "Moniteau County",
  "Monmouth County",
  "Mono County",
  "Monongalia County",
  "Monroe County",
  "Montague County",
  "Montcalm County",
  "Monterey County",
  "Montezuma County",
  "Montgomery County",
  "Montmorency County",
  "Montour County",
  "Montrose County",
  "Moody County",
  "Moore County",
  "Morgan County",
  "Morris County",
  "Morrison County",
  "Morton County",
  "Mountrail County",
  "Mower County",
  "Multnomah County",
  "Murray County",
  "Muscatine County",
  "Muscogee County",
  "Muskegon County",
  "Muskingum County",
  "Muskogee County",
  "Musselshell County",
  "Nacogdoches County",
  "Nance County",
  "Nantucket County",
  "Napa County",
  "Nash County",
  "Nassau County",
  "Natchitoches County",
  "Natrona County",
  "Navajo County",
  "Navarro County",
  "Nelson County",
  "Nemaha County",
  "Neosho County",
  "Neshoba County",
  "Nevada County",
  "New Castle County",
  "New Hanover County",
  "New Haven County",
  "New Kent County",
  "New London County",
  "New Madrid County",
  "New York County",
  "Newaygo County",
  "Newberry County",
  "Newport County",
  "Newport News City County",
  "Newton County",
  "Nez Perce County",
  "Niagara County",
  "Nicholas County",
  "Nicollet County",
  "Noble County",
  "Nobles County",
  "Nodaway County",
  "Nolan County",
  "Norfolk City County",
  "Norfolk County",
  "Northampton County",
  "Northumberland County",
  "Norton city County",
  "Nottoway County",
  "Nuckolls County",
  "Nueces County",
  "Nye County",
  "Oakland County",
  "Obion County",
  "Ocean County",
  "Oceana County",
  "Ochiltree County",
  "Oconee County",
  "Oconto County",
  "Ogemaw County",
  "Oglala Lakota County",
  "Ogle County",
  "Oglethorpe County",
  "Ohio County",
  "Okaloosa County",
  "Okanogan County",
  "Okeechobee County",
  "Okfuskee County",
  "Oklahoma County",
  "Okmulgee County",
  "Oktibbeha County",
  "Oldham County",
  "Olmsted County",
  "Oneida County",
  "Onondaga County",
  "Onslow County",
  "Ontario County",
  "Orange County",
  "Orangeburg County",
  "Orleans County",
  "Orleans Parish County",
  "Osage County",
  "Osceola County",
  "Oswego County",
  "Otero County",
  "Otoe County",
  "Otsego County",
  "Ottawa County",
  "Otter Tail County",
  "Ouachita County",
  "Outagamie County",
  "Owen County",
  "Owyhee County",
  "Oxford County",
  "Ozark County",
  "Ozaukee County",
  "Pacific County",
  "Page County",
  "Palm Beach County",
  "Palo Alto County",
  "Palo Pinto County",
  "Pamlico County",
  "Panola County",
  "Park County",
  "Parker County",
  "Parmer County",
  "Pasco County",
  "Pasquotank County",
  "Passaic County",
  "Patrick County",
  "Paulding County",
  "Pawnee County",
  "Payette County",
  "Payne County",
  "Peach County",
  "Pearl River County",
  "Pecos County",
  "Pemiscot County",
  "Pend Oreille County",
  "Pender County",
  "Pendleton County",
  "Pennington County",
  "Penobscot County",
  "Peoria County",
  "Perquimans County",
  "Perry County",
  "Person County",
  "Petersburg City County",
  "Pettis County",
  "Phelps County",
  "Philadelphia County",
  "Phillips County",
  "Piatt County",
  "Pickaway County",
  "Pickens County",
  "Pierce County",
  "Pike County",
  "Pima County",
  "Pinal County",
  "Pine County",
  "Pinellas County",
  "Piscataquis County",
  "Pitkin County",
  "Pitt County",
  "Pittsburg County",
  "Pittsylvania County",
  "Placer County",
  "Plaquemines County",
  "Platte County",
  "Pleasants County",
  "Plymouth County",
  "Pocahontas County",
  "Poinsett County",
  "Pointe Coupee County",
  "Polk County",
  "Ponce County",
  "Pontotoc County",
  "Pope County",
  "Poquoson City County",
  "Portage County",
  "Porter County",
  "Portsmouth City County",
  "Posey County",
  "Pottawatomie County",
  "Pottawattamie County",
  "Potter County",
  "Powell County",
  "Poweshiek County",
  "Powhatan County",
  "Prairie County",
  "Pratt County",
  "Preble County",
  "Presidio County",
  "Presque Isle County",
  "Preston County",
  "Price County",
  "Prince Edward County",
  "Prince George County",
  "Prince George's County",
  "Prince Georges County",
  "Prince William County",
  "Providence County",
  "Prowers County",
  "Pueblo County",
  "Pulaski County",
  "Pushmataha County",
  "Putnam County",
  "Quay County",
  "Queen Anne's County",
  "Queen Annes County",
  "Queens County",
  "Quitman County",
  "Rabun County",
  "Racine County",
  "Radford County",
  "Raleigh County",
  "Ralls County",
  "Ramsey County",
  "Randall County",
  "Randolph County",
  "Rankin County",
  "Rapides County",
  "Rappahannock County",
  "Ravalli County",
  "Ray County",
  "Reagan County",
  "Red River County",
  "Red Willow County",
  "Reeves County",
  "Refugio County",
  "Reno County",
  "Rensselaer County",
  "Renville County",
  "Rice County",
  "Richland County",
  "Richmond City County",
  "Richmond County",
  "Richmond city County",
  "Riley County",
  "Ringgold County",
  "Rio Arriba County",
  "Rio Blanco County",
  "Rio Grande County",
  "Ripley County",
  "Ritchie County",
  "Riverside County",
  "Roane County",
  "Roanoke City County",
  "Roanoke County",
  "Roberts County",
  "Robertson County",
  "Robeson County",
  "Rock County",
  "Rock Island County",
  "Rockbridge County",
  "Rockdale County",
  "Rockingham County",
  "Rockland County",
  "Rockwall County",
  "Roger Mills County",
  "Rogers County",
  "Rooks County",
  "Roscommon County",
  "Roseau County",
  "Rosebud County",
  "Ross County",
  "Routt County",
  "Rowan County",
  "Runnels County",
  "Rush County",
  "Rusk County",
  "Russell County",
  "Rutherford County",
  "Rutland County",
  "Sabine County",
  "Sac County",
  "Sacramento County",
  "Sagadahoc County",
  "Saginaw County",
  "Saguache County",
  "Saint Bernard County",
  "Saint Charles County",
  "Saint Clair County",
  "Saint Croix County",
  "Saint Francois County",
  "Saint Helena County",
  "Saint James County",
  "Saint Johns County",
  "Saint Joseph County",
  "Saint Landry County",
  "Saint Lawrence County",
  "Saint Louis City County",
  "Saint Louis County",
  "Saint Lucie County",
  "Saint Martin County",
  "Saint Mary County",
  "Saint Marys County",
  "Saint Tammany County",
  "Sainte Genevieve County",
  "Salem County",
  "Saline County",
  "Salt Lake County",
  "Saluda County",
  "Sampson County",
  "San Benito County",
  "San Bernardino County",
  "San Diego County",
  "San Francisco County",
  "San Jacinto County",
  "San Joaquin County",
  "San Juan County",
  "San Luis Obispo County",
  "San Mateo County",
  "San Miguel County",
  "San Patricio County",
  "San Saba County",
  "Sanders County",
  "Sandoval County",
  "Sandusky County",
  "Sangamon County",
  "Sanilac County",
  "Sanpete County",
  "Santa Barbara County",
  "Santa Clara County",
  "Santa Cruz County",
  "Santa Fe County",
  "Santa Rosa County",
  "Sarasota County",
  "Saratoga County",
  "Sarpy County",
  "Sauk County",
  "Saunders County",
  "Sawyer County",
  "Schenectady County",
  "Schleicher County",
  "Schley County",
  "Schoharie County",
  "Schuyler County",
  "Schuylkill County",
  "Scioto County",
  "Scotland County",
  "Scott County",
  "Scotts Bluff County",
  "Scurry County",
  "Searcy County",
  "Sebastian County",
  "Sedgwick County",
  "Seminole County",
  "Seneca County",
  "Sequoyah County",
  "Sevier County",
  "Sharkey County",
  "Sharp County",
  "Shasta County",
  "Shawano County",
  "Shawnee County",
  "Sheboygan County",
  "Shelby County",
  "Shenandoah County",
  "Sherburne County",
  "Sheridan County",
  "Sherman County",
  "Shiawassee County",
  "Shoshone County",
  "Sibley County",
  "Sierra County",
  "Silver Bow County",
  "Simpson County",
  "Sioux County",
  "Siskiyou County",
  "Sitka City and Borough County",
  "Sitka County",
  "Skagit County",
  "Skamania County",
  "Smith County",
  "Smyth County",
  "Snohomish County",
  "Snyder County",
  "Socorro County",
  "Solano County",
  "Somerset County",
  "Somervell County",
  "Sonoma County",
  "Southampton County",
  "Spalding County",
  "Spartanburg County",
  "Spencer County",
  "Spokane County",
  "Spotsylvania County",
  "St John the Baptist County",
  "St Joseph County",
  "St. Clair County",
  "St. Croix County",
  "St. Louis County",
  "St. Louis city County",
  "St. Lucie County",
  "Stafford County",
  "Stanislaus County",
  "Stanly County",
  "Stanton County",
  "Stark County",
  "Starke County",
  "Starr County",
  "Staunton City County",
  "Stearns County",
  "Steele County",
  "Stephens County",
  "Stephenson County",
  "Sterling County",
  "Steuben County",
  "Stevens County",
  "Stoddard County",
  "Stokes County",
  "Stone County",
  "Storey County",
  "Story County",
  "Strafford County",
  "Stutsman County",
  "Sublette County",
  "Suffolk City County",
  "Suffolk County",
  "Suffolk city County",
  "Sullivan County",
  "Summers County",
  "Summit County",
  "Sumner County",
  "Sumter County",
  "Sunflower County",
  "Surry County",
  "Susquehanna County",
  "Sussex County",
  "Sutter County",
  "Sutton County",
  "Suwannee County",
  "Swain County",
  "Sweet Grass County",
  "Sweetwater County",
  "Switzerland County",
  "Talbot County",
  "Talladega County",
  "Tallahatchie County",
  "Tallapoosa County",
  "Tama County",
  "Taney County",
  "Tangipahoa County",
  "Taos County",
  "Tarrant County",
  "Tate County",
  "Tattnall County",
  "Taylor County",
  "Tazewell County",
  "Tehama County",
  "Teller County",
  "Terrebonne County",
  "Terrell County",
  "Terry County",
  "Teton County",
  "Texas County",
  "Thayer County",
  "Thomas County",
  "Thurston County",
  "Tift County",
  "Tillamook County",
  "Tioga County",
  "Tippecanoe County",
  "Tishomingo County",
  "Titus County",
  "Todd County",
  "Tolland County",
  "Tom Green County",
  "Tompkins County",
  "Tooele County",
  "Toole County",
  "Toombs County",
  "Towns County",
  "Traill County",
  "Transylvania County",
  "Traverse County",
  "Travis County",
  "Trempealeau County",
  "Treutlen County",
  "Trigg County",
  "Trimble County",
  "Trinity County",
  "Tripp County",
  "Troup County",
  "Trumbull County",
  "Tucker County",
  "Tulare County",
  "Tulsa County",
  "Tunica County",
  "Tuolumne County",
  "Turner County",
  "Tuscaloosa County",
  "Tuscarawas County",
  "Tuscola County",
  "Twiggs County",
  "Twin Falls County",
  "Tyler County",
  "Uinta County",
  "Uintah County",
  "Ulster County",
  "Umatilla County",
  "Union County",
  "Upshur County",
  "Upson County",
  "Utah County",
  "Uvalde County",
  "Val Verde County",
  "Valley County",
  "Van Buren County",
  "Van Wert County",
  "Van Zandt County",
  "Vance County",
  "Vanderburgh County",
  "Vega Baja County",
  "Venango County",
  "Ventura County",
  "Vermilion County",
  "Vermillion County",
  "Vernon County",
  "Victoria County",
  "Vigo County",
  "Vilas County",
  "Vinton County",
  "Virginia Beach City County",
  "Virginia Beach city County",
  "Volusia County",
  "Wabash County",
  "Wabasha County",
  "Wadena County",
  "Wagoner County",
  "Wahkiakum County",
  "Wake County",
  "Wakulla County",
  "Waldo County",
  "Walker County",
  "Walla Walla County",
  "Waller County",
  "Wallowa County",
  "Walsh County",
  "Walthall County",
  "Walton County",
  "Walworth County",
  "Wapello County",
  "Ward County",
  "Ware County",
  "Warren County",
  "Warrick County",
  "Wasatch County",
  "Wasco County",
  "Waseca County",
  "Washakie County",
  "Washington County",
  "Washoe County",
  "Washtenaw County",
  "Watauga County",
  "Waukesha County",
  "Waupaca County",
  "Waushara County",
  "Wayne County",
  "Waynesboro City County",
  "Webb County",
  "Weber County",
  "Webster County",
  "Webster Parish County",
  "Weld County",
  "Wells County",
  "West Baton Rouge County",
  "West Carroll County",
  "West Feliciana County",
  "Westchester County",
  "Westmoreland County",
  "Weston County",
  "Wetzel County",
  "Wexford County",
  "Wharton County",
  "Whatcom County",
  "Wheeler County",
  "White County",
  "White Pine County",
  "Whiteside County",
  "Whitfield County",
  "Whitley County",
  "Whitman County",
  "Wibaux County",
  "Wichita County",
  "Wicomico County",
  "Wilcox County",
  "Wilkes County",
  "Wilkin County",
  "Wilkinson County",
  "Will County",
  "Willacy County",
  "Williams County",
  "Williamsburg City County",
  "Williamsburg County",
  "Williamson County",
  "Wilson County",
  "Winchester City County",
  "Windham County",
  "Windsor County",
  "Winkler County",
  "Winnebago County",
  "Winneshiek County",
  "Winona County",
  "Winston County",
  "Wirt County",
  "Wise County",
  "Wolfe County",
  "Wood County",
  "Woodbury County",
  "Woodford County",
  "Woods County",
  "Woodson County",
  "Woodward County",
  "Worcester County",
  "Worth County",
  "Wrangell City and Borough County",
  "Wright County",
  "Wyandot County",
  "Wyandotte County",
  "Wyoming County",
  "Wythe County",
  "Yadkin County",
  "Yakima County",
  "Yakutat County",
  "Yalobusha County",
  "Yamhill County",
  "Yancey County",
  "Yankton County",
  "Yates County",
  "Yavapai County",
  "Yazoo County",
  "Yellowstone County",
  "Yoakum County",
  "Yolo County",
  "York County",
  "Young County",
  "Yuba County",
  "Yuma County",
  "Zapata County",
  "Acadia Parish County",
  "Accomack County",
  "Adjuntas County",
  "Adjuntas Municipio County",
  "Aguada County",
  "Aguada Municipio County",
  "Aguadilla County",
  "Aguadilla Municipio County",
  "Aguas Buenas County",
  "Aguas Buenas Municipio County",
  "Aibonito County",
  "Aibonito Municipio County",
  "Aitkin County",
  "Aleutians East Borough County",
  "Aleutians East County",
  "Aleutians West Census Area County",
  "Aleutians West County",
  "Alexandria city County",
  "Allamakee County",
  "Allen Parish County",
  "Allendale County",
  "American Samoa County",
  "Anasco County",
  "Anasco Municipio County",
  "Antelope County",
  "Arecibo County",
  "Arecibo Municipio County",
  "Arroyo Municipio County",
  "Arthur County",
  "Ascension Parish County",
  "Assumption Parish County",
  "Audubon County",
  "Aurora County",
  "Avoyelles Parish County",
  "Baca County",
  "Ballard County",
  "Bamberg County",
  "Banks County",
  "Barber County",
  "Barceloneta County",
  "Barceloneta Municipio County",
  "Barnes County",
  "Barranquitas County",
  "Barranquitas Municipio County",
  "Bath County",
  "Bayamon Municipio County",
  "Beauregard Parish County",
  "Ben Hill County",
  "Bennett County",
  "Benson County",
  "Bent County",
  "Bethel Census Area County",
  "Bethel County",
  "Bienville Parish County",
  "Big Stone County",
  "Billings County",
  "Bland County",
  "Bledsoe County",
  "Bollinger County",
  "Borden County",
  "Bossier Parish County",
  "Bottineau County",
  "Boundary County",
  "Bracken County",
  "Brantley County",
  "Breathitt County",
  "Breckinridge County",
  "Briscoe County",
  "Bristol Bay Borough County",
  "Bristol Bay County",
  "Bristol City County",
  "Bristol city County",
  "Brooks County",
  "Buckingham County",
  "Bullock County",
  "Burnett County",
  "Burt County",
  "Cabo Rojo County",
  "Cabo Rojo Municipio County",
  "Caguas County",
  "Caguas Municipio County",
  "Calcasieu Parish County",
  "Caldwell Parish County",
  "Camas County",
  "Cameron Parish County",
  "Camuy County",
  "Camuy Municipio County",
  "Cannon County",
  "Canovanas County",
  "Canovanas Municipio County",
  "Caribou County",
  "Carlisle County",
  "Carolina County",
  "Carolina Municipio County",
  "Caswell County",
  "Catahoula Parish County",
  "Catano County",
  "Catano Municipio County",
  "Catron County",
  "Cayey County",
  "Cayey Municipio County",
  "Ceiba Municipio County",
  "Charlton County",
  "Chattahoochee County",
  "Cheatham County",
  "Chesapeake city County",
  "Childress County",
  "Chowan County",
  "Chugach County",
  "Ciales County",
  "Ciales Municipio County",
  "Cidra County",
  "Cidra Municipio County",
  "Cimarron County",
  "Claiborne Parish County",
  "Clearwater County",
  "Coal County",
  "Coamo County",
  "Coamo Municipio County",
  "Coffey County",
  "Coke County",
  "Coleman County",
  "Collingsworth County",
  "Colonial Heights city County",
  "Comerio County",
  "Comerio Municipio County",
  "Concho County",
  "Concordia Parish County",
  "Conecuh County",
  "Conejos County",
  "Coosa County",
  "Copper River County",
  "Corozal County",
  "Corozal Municipio County",
  "Costilla County",
  "Cottle County",
  "Cotton County",
  "Cottonwood County",
  "Covington City County",
  "Covington city County",
  "Crane County",
  "Crockett County",
  "Crosby County",
  "Culberson County",
  "Culebra County",
  "Daggett County",
  "Daniels County",
  "Danville city County",
  "Dawes County",
  "De Soto Parish County",
  "DeSoto County",
  "DeWitt County",
  "Del Norte County",
  "Denali Borough County",
  "Deuel County",
  "Dickens County",
  "Dillingham Census Area County",
  "Dillingham County",
  "Divide County",
  "Dixie County",
  "Doniphan County",
  "Dorado County",
  "Dorado Municipio County",
  "Dundy County",
  "Dunklin County",
  "East Baton Rouge Parish County",
  "East Carroll Parish County",
  "East Feliciana Parish County",
  "Echols County",
  "Edgar County",
  "Edmonson County",
  "Edmunds County",
  "Elk County",
  "Elliott County",
  "Ellsworth County",
  "Emmons County",
  "Emporia City County",
  "Emporia city County",
  "Esmeralda County",
  "Eureka County",
  "Evangeline Parish County",
  "Fairbanks North Star Borough County",
  "Fairfax city County",
  "Fajardo County",
  "Fajardo Municipio County",
  "Fall River County",
  "Fallon County",
  "Falls Church city County",
  "Falls County",
  "Faulk County",
  "Federated States of Micro County",
  "Fentress County",
  "Fisher County",
  "Fleming County",
  "Florida County",
  "Florida Municipio County",
  "Foard County",
  "Foster County",
  "Franklin Parish County",
  "Franklin city County",
  "Fredericksburg city County",
  "Frontier County",
  "Galax City County",
  "Galax city County",
  "Gentry County",
  "Giles County",
  "Gilliam County",
  "Glascock County",
  "Glasscock County",
  "Gogebic County",
  "Golden Valley County",
  "Gosper County",
  "Gove County",
  "Grant Parish County",
  "Greenlee County",
  "Greensville County",
  "Greer County",
  "Gregory County",
  "Griggs County",
  "Guam County",
  "Guanica County",
  "Guanica Municipio County",
  "Guayama County",
  "Guayama Municipio County",
  "Guayanilla County",
  "Guayanilla Municipio County",
  "Guaynabo County",
  "Guaynabo Municipio County",
  "Gurabo County",
  "Gurabo Municipio County",
  "Haakon County",
  "Haines Borough County",
  "Haines County",
  "Hamblen County",
  "Hampton city County",
  "Hansford County",
  "Hanson County",
  "Harding County",
  "Harlan County",
  "Harmon County",
  "Harper County",
  "Harrisonburg city County",
  "Hatillo County",
  "Hatillo Municipio County",
  "Hawkins County",
  "Hayes County",
  "Hemphill County",
  "Hettinger County",
  "Hickman County",
  "Hickory County",
  "Hinsdale County",
  "Hitchcock County",
  "Hodgeman County",
  "Hoonah-Angoon Census Area County",
  "Hopewell city County",
  "Hormigueros County",
  "Hormigueros Municipio County",
  "Hot Spring County",
  "Hot Springs County",
  "Humacao County",
  "Humacao Municipio County",
  "Humphreys County",
  "Iberia Parish County",
  "Iberville Parish County",
  "Ida County",
  "Irion County",
  "Irwin County",
  "Isabela County",
  "Isabela Municipio County",
  "Issaquena County",
  "Jackson Parish County",
  "Jay County",
  "Jayuya Municipio County",
  "Jefferson Davis Parish County",
  "Jenkins County",
  "Jerauld County",
  "Jewell County",
  "Jim Hogg County",
  "Juana Diaz County",
  "Juana Diaz Municipio County",
  "Judith Basin County",
  "Juncos County",
  "Juncos Municipio County",
  "Juneau City and Borough County",
  "Kalawao County",
  "Kearny County",
  "Kenai Peninsula Borough County",
  "Kenedy County",
  "Keokuk County",
  "Ketchikan Gateway Borough County",
  "Kewaunee County",
  "Keweenaw County",
  "Keya Paha County",
  "Kidder County",
  "Kimble County",
  "King George County",
  "King William County",
  "King and Queen County",
  "Kingman County",
  "Kittson County",
  "Knott County",
  "Kodiak Island Borough County",
  "Kusilvak County",
  "La Salle Parish County",
  "LaGrange County",
  "LaMoure County",
  "LaPorte County",
  "LaSalle County",
  "Lac Qui Parle County",
  "Lac qui Parle County",
  "Lafourche Parish County",
  "Lajas County",
  "Lajas Municipio County",
  "Lake and Peninsula Borough County",
  "Lake and Peninsula County",
  "Lake of the Woods County",
  "Lamb County",
  "Lander County",
  "Lanier County",
  "Lares County",
  "Lares Municipio County",
  "Las Marias County",
  "Las Piedras Municipio County",
  "Latimer County",
  "Lemhi County",
  "Leslie County",
  "Lexington city County",
  "Lincoln Parish County",
  "Live Oak County",
  "Livingston Parish County",
  "Loiza County",
  "Loiza Municipio County",
  "Loup County",
  "Love County",
  "Loving County",
  "Luce County",
  "Lunenburg County",
  "Luquillo County",
  "Luquillo Municipio County",
  "Lyman County",
  "Lynchburg city County",
  "Lynn County",
  "Mackinac County",
  "Madison Parish County",
  "Magoffin County",
  "Mahnomen County",
  "Manassas Park city County",
  "Manassas city County",
  "Manati County",
  "Manati Municipio County",
  "Maricao County",
  "Maries County",
  "Marshall Islands County",
  "Martinsville city County",
  "Matanuska-Susitna Borough County",
  "Mathews County",
  "Maunabo County",
  "Maunabo Municipio County",
  "Mayaguez County",
  "Mayaguez Municipio County",
  "McCormick County",
  "McCreary County",
  "McMinn County",
  "McMullen County",
  "McNairy County",
  "Meagher County",
  "Meigs County",
  "Mellette County",
  "Menard County",
  "Menifee County",
  "Miner County",
  "Moca County",
  "Moca Municipio County",
  "Modoc County",
  "Monona County",
  "Mora County",
  "Morehouse County",
  "Morehouse Parish County",
  "Morovis County",
  "Morovis Municipio County",
  "Morrill County",
  "Morrow County",
  "Motley County",
  "Moultrie County",
  "Muhlenberg County",
  "Naguabo County",
  "Naguabo Municipio County",
  "Naranjito County",
  "Naranjito Municipio County",
  "Natchitoches Parish County",
  "Ness County",
  "Newport News city County",
  "Niobrara County",
  "Nome Census Area County",
  "Nome County",
  "Norfolk city County",
  "Norman County",
  "North Slope Borough County",
  "North Slope County",
  "Northwest Arctic Borough County",
  "Northwest Arctic County",
  "Norton City County",
  "Norton County",
  "Nowata County",
  "Noxubee County",
  "O'Brien County",
  "Obrien County",
  "Oliver County",
  "Ontonagon County",
  "Oregon County",
  "Orocovis County",
  "Orocovis Municipio County",
  "Osborne County",
  "Oscoda County",
  "Ouachita Parish County",
  "Ouray County",
  "Overton County",
  "Owsley County",
  "Palau County",
  "Parke County",
  "Patillas County",
  "Patillas Municipio County",
  "Pembina County",
  "Penuelas County",
  "Penuelas Municipio County",
  "Pepin County",
  "Perkins County",
  "Pershing County",
  "Petersburg Census Area County",
  "Petersburg County",
  "Petersburg city County",
  "Petroleum County",
  "Pickett County",
  "Pipestone County",
  "Piute County",
  "Plaquemines Parish County",
  "Plumas County",
  "Pointe Coupee Parish County",
  "Ponce Municipio County",
  "Pondera County",
  "Poquoson city County",
  "Portsmouth city County",
  "Powder River County",
  "Power County",
  "Prentiss County",
  "Prince of Wales Hyder County",
  "Prince of Wales-Hyder Census Area County",
  "Quebradillas County",
  "Quebradillas Municipio County",
  "Radford city County",
  "Rains County",
  "Ransom County",
  "Rapides Parish County",
  "Rawlins County",
  "Real County",
  "Red Lake County",
  "Red River Parish County",
  "Redwood County",
  "Republic County",
  "Reynolds County",
  "Rhea County",
  "Rich County",
  "Richardson County",
  "Richland Parish County",
  "Rincon County",
  "Rincon Municipio County",
  "Rio Grande Municipio County",
  "Roanoke city County",
  "Rockcastle County",
  "Rolette County",
  "Roosevelt County",
  "Rota County",
  "Sabana Grande County",
  "Sabana Grande Municipio County",
  "Sabine Parish County",
  "Saint Francis County",
  "Saint John County",
  "Saint Thomas County",
  "Saipan County",
  "Saipan Municipality County",
  "Salem city County",
  "Salinas County",
  "Salinas Municipio County",
  "San Augustine County",
  "San German County",
  "San German Municipio County",
  "San Juan Municipio County",
  "San Lorenzo County",
  "San Lorenzo Municipio County",
  "San Sebastian County",
  "San Sebastian Municipio County",
  "Sanborn County",
  "Santa Isabel County",
  "Santa Isabel Municipio County",
  "Sargent County",
  "Schoolcraft County",
  "Screven County",
  "Sequatchie County",
  "Seward County",
  "Shackelford County",
  "Shannon County",
  "Skagway County",
  "Skagway Municipality County",
  "Slope County",
  "Southeast Fairbanks Census Area County",
  "Southeast Fairbanks County",
  "Spink County",
  "St. Bernard Parish County",
  "St. Charles County",
  "St. Charles Parish County",
  "St. Croix Island County",
  "St. Francis County",
  "St. Francois County",
  "St. Helena Parish County",
  "St. James Parish County",
  "St. John Island County",
  "St. John the Baptist Parish County",
  "St. Johns County",
  "St. Joseph County",
  "St. Landry Parish County",
  "St. Lawrence County",
  "St. Martin Parish County",
  "St. Mary Parish County",
  "St. Mary's County",
  "St. Tammany Parish County",
  "St. Thomas Island County",
  "Stanley County",
  "Staunton city County",
  "Ste. Genevieve County",
  "Stewart County",
  "Stillwater County",
  "Stonewall County",
  "Sully County",
  "Swift County",
  "Swisher County",
  "Taliaferro County",
  "Tangipahoa Parish County",
  "Telfair County",
  "Tensas County",
  "Tensas Parish County",
  "Terrebonne Parish County",
  "Throckmorton County",
  "Tillman County",
  "Tinian County",
  "Tippah County",
  "Tipton County",
  "Toa Alta County",
  "Toa Alta Municipio County",
  "Toa Baja County",
  "Toa Baja Municipio County",
  "Torrance County",
  "Towner County",
  "Treasure County",
  "Trego County",
  "Trousdale County",
  "Trujillo Alto County",
  "Trujillo Alto Municipio County",
  "Tyrrell County",
  "Unicoi County",
  "Union Parish County",
  "Upton County",
  "Utuado County",
  "Utuado Municipio County",
  "Valencia County",
  "Vega Alta County",
  "Vega Alta Municipio County",
  "Vega Baja Municipio County",
  "Vermilion Parish County",
  "Vernon Parish County",
  "Vieques County",
  "Vieques Municipio County",
  "Villalba County",
  "Villalba Municipio County",
  "Wabaunsee County",
  "Wallace County",
  "Washburn County",
  "Washington Parish County",
  "Washita County",
  "Watonwan County",
  "Waynesboro city County",
  "Weakley County",
  "West Baton Rouge Parish County",
  "West Carroll Parish County",
  "West Feliciana Parish County",
  "Western District County",
  "Wheatland County",
  "Wilbarger County",
  "Williamsburg city County",
  "Winchester city County",
  "Winn County",
  "Winn Parish County",
  "Woodruff County",
  "Wrangell County",
  "Yabucoa County",
  "Yabucoa Municipio County",
  "Yakutat City and Borough County",
  "Yauco County",
  "Yauco Municipio County",
  "Yell County",
  "Yellow Medicine County",
  "Yukon Koyukuk County",
  "Yukon-Koyukuk Census Area County",
  "Zavala County",
  "Ziebach County",
];
export const bq_location_address_cbsa_name = [
  "Aberdeen, SD",
  "Aberdeen, WA",
  "Abilene, TX",
  "Ada, OK",
  "Adrian, MI",
  "Akron, OH",
  "Alamogordo, NM",
  "Albany, GA",
  "Albany-Lebanon, OR",
  "Albany-Schenectady-Troy, NY",
  "Albemarle, NC",
  "Albert Lea, MN",
  "Albertville, AL",
  "Albuquerque, NM",
  "Alexander City, AL",
  "Alexandria, LA",
  "Alexandria, MN",
  "Alice, TX",
  "Allentown-Bethlehem-Easton, PA-NJ",
  "Alma, MI",
  "Alpena, MI",
  "Altoona, PA",
  "Amarillo, TX",
  "Americus, GA",
  "Ames, IA",
  "Amsterdam, NY",
  "Anchorage, AK",
  "Andrews, TX",
  "Angola, IN",
  "Ann Arbor, MI",
  "Anniston-Oxford, AL",
  "Appleton, WI",
  "Arcadia, FL",
  "Ardmore, OK",
  "Arkadelphia, AR",
  "Asheville, NC",
  "Ashland, OH",
  "Ashtabula, OH",
  "Astoria, OR",
  "Athens, OH",
  "Athens, TX",
  "Athens-Clarke County, GA",
  "Atlanta-Sandy Springs-Alpharetta, GA",
  "Atlantic City-Hammonton, NJ",
  "Atmore, AL",
  "Auburn, IN",
  "Auburn, NY",
  "Auburn-Opelika, AL",
  "Augusta-Richmond County, GA-SC",
  "Augusta-Waterville, ME",
  "Austin, MN",
  "Austin-Round Rock-Georgetown, TX",
  "Bainbridge, GA",
  "Bakersfield, CA",
  "Baltimore-Columbia-Towson, MD",
  "Bangor, ME",
  "Baraboo, WI",
  "Bardstown, KY",
  "Barnstable Town, MA",
  "Barre, VT",
  "Bartlesville, OK",
  "Batavia, NY",
  "Batesville, AR",
  "Baton Rouge, LA",
  "Battle Creek, MI",
  "Bay City, MI",
  "Bay City, TX",
  "Beatrice, NE",
  "Beaumont-Port Arthur, TX",
  "Beaver Dam, WI",
  "Beckley, WV",
  "Bedford, IN",
  "Beeville, TX",
  "Bellefontaine, OH",
  "Bellingham, WA",
  "Bemidji, MN",
  "Bend, OR",
  "Bennettsville, SC",
  "Bennington, VT",
  "Berlin, NH",
  "Big Rapids, MI",
  "Big Spring, TX",
  "Big Stone Gap, VA",
  "Billings, MT",
  "Binghamton, NY",
  "Birmingham-Hoover, AL",
  "Bismarck, ND",
  "Blackfoot, ID",
  "Blacksburg-Christiansburg, VA",
  "Bloomington, IL",
  "Bloomington, IN",
  "Bloomsburg-Berwick, PA",
  "Bluefield, WV-VA",
  "Bluffton, IN",
  "Blytheville, AR",
  "Bogalusa, LA",
  "Boise City, ID",
  "Bonham, TX",
  "Boone, NC",
  "Borger, TX",
  "Boston-Cambridge-Newton, MA-NH",
  "Boulder, CO",
  "Bowling Green, KY",
  "Bozeman, MT",
  "Bradford, PA",
  "Brainerd, MN",
  "Branson, MO",
  "Breckenridge, CO",
  "Bremerton-Silverdale-Port Orchard, WA",
  "Brenham, TX",
  "Brevard, NC",
  "Bridgeport-Stamford-Norwalk, CT",
  "Brookhaven, MS",
  "Brookings, OR",
  "Brookings, SD",
  "Brownsville-Harlingen, TX",
  "Brownwood, TX",
  "Brunswick, GA",
  "Bucyrus-Galion, OH",
  "Buffalo-Cheektowaga, NY",
  "Burley, ID",
  "Burlington, IA-IL",
  "Burlington, NC",
  "Burlington-South Burlington, VT",
  "Butte-Silver Bow, MT",
  "Cadillac, MI",
  "Calhoun, GA",
  "California-Lexington Park, MD",
  "Cambridge, MD",
  "Cambridge, OH",
  "Camden, AR",
  "Campbellsville, KY",
  "Canton-Massillon, OH",
  "Cape Coral-Fort Myers, FL",
  "Cape Girardeau, MO-IL",
  "Carbondale-Marion, IL",
  "Carlsbad-Artesia, NM",
  "Carroll, IA",
  "Carson City, NV",
  "Casper, WY",
  "Ca on City, CO",
  "Cedar City, UT",
  "Cedar Rapids, IA",
  "Cedartown, GA",
  "Celina, OH",
  "Centralia, IL",
  "Centralia, WA",
  "Chambersburg-Waynesboro, PA",
  "Champaign-Urbana, IL",
  "Charleston, WV",
  "Charleston-Mattoon, IL",
  "Charleston-North Charleston, SC",
  "Charlotte-Concord-Gastonia, NC-SC",
  "Charlottesville, VA",
  "Chattanooga, TN-GA",
  "Cheyenne, WY",
  "Chicago-Naperville-Elgin, IL-IN-WI",
  "Chico, CA",
  "Chillicothe, OH",
  "Cincinnati, OH-KY-IN",
  "Clarksburg, WV",
  "Clarksdale, MS",
  "Clarksville, TN-KY",
  "Clearlake, CA",
  "Cleveland, MS",
  "Cleveland, TN",
  "Cleveland-Elyria, OH",
  "Clewiston, FL",
  "Clinton, IA",
  "Clovis, NM",
  "Coeur dAlene, ID",
  "Coffeyville, KS",
  "Coldwater, MI",
  "College Station-Bryan, TX",
  "Colorado Springs, CO",
  "Columbia, MO",
  "Columbia, SC",
  "Columbus, GA-AL",
  "Columbus, IN",
  "Columbus, MS",
  "Columbus, NE",
  "Columbus, OH",
  "Concord, NH",
  "Cookeville, TN",
  "Coos Bay, OR",
  "Cordele, GA",
  "Corinth, MS",
  "Cornelia, GA",
  "Corning, NY",
  "Corpus Christi, TX",
  "Corsicana, TX",
  "Cortland, NY",
  "Corvallis, OR",
  "Coshocton, OH",
  "Crawfordsville, IN",
  "Crestview-Fort Walton Beach-Destin, FL",
  "Crossville, TN",
  "Cullman, AL",
  "Cullowhee, NC",
  "Cumberland, MD-WV",
  "Dallas-Fort Worth-Arlington, TX",
  "Dalton, GA",
  "Danville, IL",
  "Danville, KY",
  "Danville, VA",
  "Daphne-Fairhope-Foley, AL",
  "Davenport-Moline-Rock Island, IA-IL",
  "Dayton-Kettering, OH",
  "DeRidder, LA",
  "Decatur, AL",
  "Decatur, IL",
  "Decatur, IN",
  "Defiance, OH",
  "Del Rio, TX",
  "Deltona-Daytona Beach-Ormond Beach, FL",
  "Deming, NM",
  "Denver-Aurora-Lakewood, CO",
  "Des Moines-West Des Moines, IA",
  "Detroit-Warren-Dearborn, MI",
  "Dickinson, ND",
  "Dixon, IL",
  "Dodge City, KS",
  "Dothan, AL",
  "Douglas, GA",
  "Dover, DE",
  "DuBois, PA",
  "Dublin, GA",
  "Dubuque, IA",
  "Duluth, MN-WI",
  "Dumas, TX",
  "Duncan, OK",
  "Durango, CO",
  "Durant, OK",
  "Durham-Chapel Hill, NC",
  "Dyersburg, TN",
  "Eagle Pass, TX",
  "East Stroudsburg, PA",
  "Easton, MD",
  "Eau Claire, WI",
  "Edwards, CO",
  "Effingham, IL",
  "El Campo, TX",
  "El Centro, CA",
  "El Dorado, AR",
  "El Paso, TX",
  "Elizabeth City, NC",
  "Elizabethtown-Fort Knox, KY",
  "Elk City, OK",
  "Elkhart-Goshen, IN",
  "Elkins, WV",
  "Elko, NV",
  "Ellensburg, WA",
  "Elmira, NY",
  "Emporia, KS",
  "Enid, OK",
  "Enterprise, AL",
  "Erie, PA",
  "Escanaba, MI",
  "Espa ola, NM",
  "Eufaula, AL-GA",
  "Eugene-Springfield, OR",
  "Eureka-Arcata, CA",
  "Evanston, WY",
  "Evansville, IN-KY",
  "Fairbanks, AK",
  "Fairfield, IA",
  "Fairmont, MN",
  "Fairmont, WV",
  "Fallon, NV",
  "Fargo, ND-MN",
  "Faribault-Northfield, MN",
  "Farmington, MO",
  "Farmington, NM",
  "Fayetteville, NC",
  "Fayetteville-Springdale-Rogers, AR",
  "Fergus Falls, MN",
  "Fernley, NV",
  "Findlay, OH",
  "Flagstaff, AZ",
  "Flint, MI",
  "Florence, SC",
  "Florence-Muscle Shoals, AL",
  "Fond du Lac, WI",
  "Forest City, NC",
  "Fort Collins, CO",
  "Fort Dodge, IA",
  "Fort Leonard Wood, MO",
  "Fort Madison-Keokuk, IA-IL-MO",
  "Fort Morgan, CO",
  "Fort Payne, AL",
  "Fort Polk South, LA",
  "Fort Smith, AR-OK",
  "Fort Wayne, IN",
  "Frankfort, IN",
  "Frankfort, KY",
  "Fredericksburg, TX",
  "Freeport, IL",
  "Fremont, NE",
  "Fremont, OH",
  "Fresno, CA",
  "Gadsden, AL",
  "Gaffney, SC",
  "Gainesville, FL",
  "Gainesville, GA",
  "Gainesville, TX",
  "Gallup, NM",
  "Garden City, KS",
  "Gardnerville Ranchos, NV",
  "Georgetown, SC",
  "Gettysburg, PA",
  "Gillette, WY",
  "Glasgow, KY",
  "Glens Falls, NY",
  "Glenwood Springs, CO",
  "Gloversville, NY",
  "Goldsboro, NC",
  "Granbury, TX",
  "Grand Forks, ND-MN",
  "Grand Island, NE",
  "Grand Junction, CO",
  "Grand Rapids, MN",
  "Grand Rapids-Kentwood, MI",
  "Grants Pass, OR",
  "Grants, NM",
  "Great Bend, KS",
  "Great Falls, MT",
  "Greeley, CO",
  "Green Bay, WI",
  "Greeneville, TN",
  "Greensboro-High Point, NC",
  "Greensburg, IN",
  "Greenville, MS",
  "Greenville, NC",
  "Greenville, OH",
  "Greenville-Anderson, SC",
  "Greenwood, MS",
  "Greenwood, SC",
  "Grenada, MS",
  "Guayama, PR",
  "Gulfport-Biloxi, MS",
  "Hagerstown-Martinsburg, MD-WV",
  "Hailey, ID",
  "Hammond, LA",
  "Hanford-Corcoran, CA",
  "Hannibal, MO",
  "Harrisburg-Carlisle, PA",
  "Harrison, AR",
  "Harrisonburg, VA",
  "Hartford-East Hartford-Middletown, CT",
  "Hastings, NE",
  "Hattiesburg, MS",
  "Hays, KS",
  "Heber, UT",
  "Helena, MT",
  "Henderson, NC",
  "Hereford, TX",
  "Hermiston-Pendleton, OR",
  "Hickory-Lenoir-Morganton, NC",
  "Hillsdale, MI",
  "Hilo, HI",
  "Hilton Head Island-Bluffton, SC",
  "Hinesville, GA",
  "Hobbs, NM",
  "Holland, MI",
  "Homosassa Springs, FL",
  "Hood River, OR",
  "Hope, AR",
  "Hot Springs, AR",
  "Houghton, MI",
  "Houma-Thibodaux, LA",
  "Houston-The Woodlands-Sugar Land, TX",
  "Hudson, NY",
  "Huntingdon, PA",
  "Huntington, IN",
  "Huntington-Ashland, WV-KY-OH",
  "Huntsville, AL",
  "Huntsville, TX",
  "Huron, SD",
  "Hutchinson, KS",
  "Hutchinson, MN",
  "Idaho Falls, ID",
  "Indiana, PA",
  "Indianapolis-Carmel-Anderson, IN",
  "Indianola, MS",
  "Iowa City, IA",
  "Iron Mountain, MI-WI",
  "Ithaca, NY",
  "Jackson, MI",
  "Jackson, MS",
  "Jackson, OH",
  "Jackson, TN",
  "Jackson, WY-ID",
  "Jacksonville, FL",
  "Jacksonville, IL",
  "Jacksonville, NC",
  "Jacksonville, TX",
  "Jamestown, ND",
  "Jamestown-Dunkirk-Fredonia, NY",
  "Janesville-Beloit, WI",
  "Jasper, AL",
  "Jasper, IN",
  "Jayuya, PR",
  "Jefferson City, MO",
  "Jefferson, GA",
  "Jennings, LA",
  "Jesup, GA",
  "Johnson City, TN",
  "Johnstown, PA",
  "Jonesboro, AR",
  "Joplin, MO",
  "Juneau, AK",
  "Kahului-Wailuku-Lahaina, HI",
  "Kalamazoo-Portage, MI",
  "Kalispell, MT",
  "Kankakee, IL",
  "Kansas City, MO-KS",
  "Kapaa, HI",
  "Kearney, NE",
  "Keene, NH",
  "Kendallville, IN",
  "Kennewick-Richland, WA",
  "Kerrville, TX",
  "Ketchikan, AK",
  "Key West, FL",
  "Kill Devil Hills, NC",
  "Killeen-Temple, TX",
  "Kingsport-Bristol, TN-VA",
  "Kingston, NY",
  "Kingsville, TX",
  "Kinston, NC",
  "Kirksville, MO",
  "Klamath Falls, OR",
  "Knoxville, TN",
  "Kokomo, IN",
  "La Crosse-Onalaska, WI-MN",
  "La Grande, OR",
  "LaGrange, GA-AL",
  "Laconia, NH",
  "Lafayette, LA",
  "Lafayette-West Lafayette, IN",
  "Lake Charles, LA",
  "Lake City, FL",
  "Lake Havasu City-Kingman, AZ",
  "Lakeland-Winter Haven, FL",
  "Lamesa, TX",
  "Lancaster, PA",
  "Lansing-East Lansing, MI",
  "Laramie, WY",
  "Laredo, TX",
  "Las Cruces, NM",
  "Las Vegas, NM",
  "Las Vegas-Henderson-Paradise, NV",
  "Laurel, MS",
  "Laurinburg, NC",
  "Lawrence, KS",
  "Lawton, OK",
  "Lebanon, MO",
  "Lebanon, NH-VT",
  "Lebanon, PA",
  "Levelland, TX",
  "Lewiston, ID-WA",
  "Lewiston-Auburn, ME",
  "Lewistown, PA",
  "Lexington, NE",
  "Lexington-Fayette, KY",
  "Lima, OH",
  "Lincoln, NE",
  "Little Rock-North Little Rock-Conway, AR",
  "Logan, UT-ID",
  "London, KY",
  "Longview, TX",
  "Longview, WA",
  "Los Alamos, NM",
  "Los Angeles-Long Beach-Anaheim, CA",
  "Louisville/Jefferson County, KY-IN",
  "Lubbock, TX",
  "Ludington, MI",
  "Lufkin, TX",
  "Lumberton, NC",
  "Lynchburg, VA",
  "Macomb, IL",
  "Macon-Bibb County, GA",
  "Madera, CA",
  "Madison, IN",
  "Madison, WI",
  "Madisonville, KY",
  "Magnolia, AR",
  "Malone, NY",
  "Manchester-Nashua, NH",
  "Manhattan, KS",
  "Manitowoc, WI",
  "Mankato, MN",
  "Mansfield, OH",
  "Marietta, OH",
  "Marinette, WI-MI",
  "Marion, IN",
  "Marion, NC",
  "Marion, OH",
  "Marquette, MI",
  "Marshall, MN",
  "Marshall, MO",
  "Marshalltown, IA",
  "Martinsville, VA",
  "Maryville, MO",
  "Mason City, IA",
  "Mayfield, KY",
  "Maysville, KY",
  "McAlester, OK",
  "McAllen-Edinburg-Mission, TX",
  "McComb, MS",
  "McMinnville, TN",
  "McPherson, KS",
  "Medford, OR",
  "Memphis, TN-MS-AR",
  "Menomonie, WI",
  "Merced, CA",
  "Meridian, MS",
  "Mexico, MO",
  "Miami, OK",
  "Miami-Fort Lauderdale-Pompano Beach, FL",
  "Michigan City-La Porte, IN",
  "Middlesborough, KY",
  "Midland, MI",
  "Midland, TX",
  "Milledgeville, GA",
  "Milwaukee-Waukesha, WI",
  "Minden, LA",
  "Mineral Wells, TX",
  "Minneapolis-St. Paul-Bloomington, MN-WI",
  "Minot, ND",
  "Missoula, MT",
  "Mitchell, SD",
  "Moberly, MO",
  "Mobile, AL",
  "Modesto, CA",
  "Monroe, LA",
  "Monroe, MI",
  "Montgomery, AL",
  "Montrose, CO",
  "Morehead City, NC",
  "Morgan City, LA",
  "Morgantown, WV",
  "Morristown, TN",
  "Moscow, ID",
  "Moses Lake, WA",
  "Moultrie, GA",
  "Mount Airy, NC",
  "Mount Gay-Shamrock, WV",
  "Mount Pleasant, MI",
  "Mount Pleasant, TX",
  "Mount Sterling, KY",
  "Mount Vernon, OH",
  "Mount Vernon-Anacortes, WA",
  "Mountain Home, AR",
  "Mountain Home, ID",
  "Muncie, IN",
  "Murray, KY",
  "Muscatine, IA",
  "Muskegon, MI",
  "Muskogee, OK",
  "Myrtle Beach-Conway-North Myrtle Beach, SC-NC",
  "Nacogdoches, TX",
  "Napa, CA",
  "Naples-Marco Island, FL",
  "Nashville-Davidson--Murfreesboro--Franklin, TN",
  "Natchez, MS-LA",
  "Natchitoches, LA",
  "New Bern, NC",
  "New Castle, IN",
  "New Castle, PA",
  "New Haven-Milford, CT",
  "New Orleans-Metairie, LA",
  "New Philadelphia-Dover, OH",
  "New Ulm, MN",
  "New York-Newark-Jersey City, NY-NJ-PA",
  "Newberry, SC",
  "Newport, OR",
  "Newport, TN",
  "Niles, MI",
  "Nogales, AZ",
  "Norfolk, NE",
  "North Platte, NE",
  "North Port-Sarasota-Bradenton, FL",
  "North Vernon, IN",
  "North Wilkesboro, NC",
  "Norwalk, OH",
  "Norwich-New London, CT",
  "Oak Harbor, WA",
  "Ocala, FL",
  "Ocean City, NJ",
  "Odessa, TX",
  "Ogden-Clearfield, UT",
  "Ogdensburg-Massena, NY",
  "Oil City, PA",
  "Okeechobee, FL",
  "Oklahoma City, OK",
  "Olean, NY",
  "Olympia-Lacey-Tumwater, WA",
  "Omaha-Council Bluffs, NE-IA",
  "Oneonta, NY",
  "Ontario, OR-ID",
  "Opelousas, LA",
  "Orangeburg, SC",
  "Orlando-Kissimmee-Sanford, FL",
  "Oshkosh-Neenah, WI",
  "Oskaloosa, IA",
  "Othello, WA",
  "Ottawa, IL",
  "Ottawa, KS",
  "Ottumwa, IA",
  "Owatonna, MN",
  "Owensboro, KY",
  "Oxford, MS",
  "Oxnard-Thousand Oaks-Ventura, CA",
  "Ozark, AL",
  "Paducah, KY-IL",
  "Pahrump, NV",
  "Palatka, FL",
  "Palestine, TX",
  "Palm Bay-Melbourne-Titusville, FL",
  "Pampa, TX",
  "Panama City, FL",
  "Paragould, AR",
  "Paris, TX",
  "Parkersburg-Vienna, WV",
  "Parsons, KS",
  "Payson, AZ",
  "Pearsall, TX",
  "Pecos, TX",
  "Pella, IA",
  "Pensacola-Ferry Pass-Brent, FL",
  "Peoria, IL",
  "Peru, IN",
  "Philadelphia-Camden-Wilmington, PA-NJ-DE-MD",
  "Phoenix-Mesa-Chandler, AZ",
  "Picayune, MS",
  "Pierre, SD",
  "Pine Bluff, AR",
  "Pinehurst-Southern Pines, NC",
  "Pittsburg, KS",
  "Pittsburgh, PA",
  "Pittsfield, MA",
  "Plainview, TX",
  "Platteville, WI",
  "Plattsburgh, NY",
  "Plymouth, IN",
  "Pocatello, ID",
  "Point Pleasant, WV-OH",
  "Ponca City, OK",
  "Pontiac, IL",
  "Poplar Bluff, MO",
  "Port Angeles, WA",
  "Port Lavaca, TX",
  "Port St. Lucie, FL",
  "Portland-South Portland, ME",
  "Portland-Vancouver-Hillsboro, OR-WA",
  "Portsmouth, OH",
  "Pottsville, PA",
  "Poughkeepsie-Newburgh-Middletown, NY",
  "Prescott Valley-Prescott, AZ",
  "Price, UT",
  "Prineville, OR",
  "Providence-Warwick, RI-MA",
  "Provo-Orem, UT",
  "Pueblo, CO",
  "Pullman, WA",
  "Punta Gorda, FL",
  "Quincy, IL-MO",
  "Racine, WI",
  "Raleigh-Cary, NC",
  "Rapid City, SD",
  "Raymondville, TX",
  "Reading, PA",
  "Red Bluff, CA",
  "Red Wing, MN",
  "Redding, CA",
  "Reno, NV",
  "Rexburg, ID",
  "Richmond, IN",
  "Richmond, VA",
  "Richmond-Berea, KY",
  "Rio Grande City-Roma, TX",
  "Riverside-San Bernardino-Ontario, CA",
  "Riverton, WY",
  "Roanoke Rapids, NC",
  "Roanoke, VA",
  "Rochelle, IL",
  "Rochester, MN",
  "Rochester, NY",
  "Rock Springs, WY",
  "Rockford, IL",
  "Rockingham, NC",
  "Rockport, TX",
  "Rocky Mount, NC",
  "Rolla, MO",
  "Rome, GA",
  "Roseburg, OR",
  "Roswell, NM",
  "Ruidoso, NM",
  "Russellville, AR",
  "Ruston, LA",
  "Rutland, VT",
  "Sacramento-Roseville-Folsom, CA",
  "Safford, AZ",
  "Saginaw, MI",
  "Salem, OH",
  "Salem, OR",
  "Salina, KS",
  "Salinas, CA",
  "Salisbury, MD-DE",
  "Salt Lake City, UT",
  "San Angelo, TX",
  "San Antonio-New Braunfels, TX",
  "San Diego-Chula Vista-Carlsbad, CA",
  "San Francisco-Oakland-Berkeley, CA",
  "San Jose-Sunnyvale-Santa Clara, CA",
  "San Juan-Bayam n-Caguas, PR",
  "San Luis Obispo-Paso Robles, CA",
  "Sandpoint, ID",
  "Sandusky, OH",
  "Sanford, NC",
  "Santa Cruz-Watsonville, CA",
  "Santa Fe, NM",
  "Santa Maria-Santa Barbara, CA",
  "Santa Rosa-Petaluma, CA",
  "Sault Ste. Marie, MI",
  "Savannah, GA",
  "Sayre, PA",
  "Scottsbluff, NE",
  "Scottsboro, AL",
  "Scottsburg, IN",
  "Scranton--Wilkes-Barre, PA",
  "Searcy, AR",
  "Seattle-Tacoma-Bellevue, WA",
  "Sebastian-Vero Beach, FL",
  "Sebring-Avon Park, FL",
  "Sedalia, MO",
  "Selinsgrove, PA",
  "Selma, AL",
  "Seneca Falls, NY",
  "Seneca, SC",
  "Sevierville, TN",
  "Seymour, IN",
  "Shawano, WI",
  "Shawnee, OK",
  "Sheboygan, WI",
  "Shelby, NC",
  "Shelbyville, TN",
  "Shelton, WA",
  "Sheridan, WY",
  "Sherman-Denison, TX",
  "Show Low, AZ",
  "Shreveport-Bossier City, LA",
  "Sidney, OH",
  "Sierra Vista-Douglas, AZ",
  "Sikeston, MO",
  "Silver City, NM",
  "Sioux City, IA-NE-SD",
  "Sioux Falls, SD",
  "Snyder, TX",
  "Somerset, KY",
  "Somerset, PA",
  "Sonora, CA",
  "South Bend-Mishawaka, IN-MI",
  "Spartanburg, SC",
  "Spearfish, SD",
  "Spencer, IA",
  "Spirit Lake, IA",
  "Spokane-Spokane Valley, WA",
  "Springfield, IL",
  "Springfield, MA",
  "Springfield, MO",
  "Springfield, OH",
  "St. Cloud, MN",
  "St. George, UT",
  "St. Joseph, MO-KS",
  "St. Louis, MO-IL",
  "St. Marys, GA",
  "Starkville, MS",
  "State College, PA",
  "Statesboro, GA",
  "Staunton, VA",
  "Steamboat Springs, CO",
  "Stephenville, TX",
  "Sterling, IL",
  "Stevens Point, WI",
  "Stillwater, OK",
  "Stockton, CA",
  "Storm Lake, IA",
  "Sturgis, MI",
  "Sulphur Springs, TX",
  "Summerville, GA",
  "Sumter, SC",
  "Sunbury, PA",
  "Susanville, CA",
  "Sweetwater, TX",
  "Syracuse, NY",
  "Tahlequah, OK",
  "Talladega-Sylacauga, AL",
  "Tallahassee, FL",
  "Tampa-St. Petersburg-Clearwater, FL",
  "Taos, NM",
  "Taylorville, IL",
  "Terre Haute, IN",
  "Texarkana, TX-AR",
  "The Dalles, OR",
  "The Villages, FL",
  "Thomaston, GA",
  "Thomasville, GA",
  "Tiffin, OH",
  "Tifton, GA",
  "Toccoa, GA",
  "Toledo, OH",
  "Topeka, KS",
  "Torrington, CT",
  "Traverse City, MI",
  "Trenton-Princeton, NJ",
  "Troy, AL",
  "Truckee-Grass Valley, CA",
  "Tucson, AZ",
  "Tullahoma-Manchester, TN",
  "Tulsa, OK",
  "Tupelo, MS",
  "Tuscaloosa, AL",
  "Twin Falls, ID",
  "Tyler, TX",
  "Ukiah, CA",
  "Union City, TN",
  "Union, SC",
  "Urban Honolulu, HI",
  "Urbana, OH",
  "Utica-Rome, NY",
  "Uvalde, TX",
  "Valdosta, GA",
  "Vallejo, CA",
  "Van Wert, OH",
  "Vernal, UT",
  "Vicksburg, MS",
  "Victoria, TX",
  "Vidalia, GA",
  "Vincennes, IN",
  "Vineland-Bridgeton, NJ",
  "Vineyard Haven, MA",
  "Virginia Beach-Norfolk-Newport News, VA-NC",
  "Visalia, CA",
  "Wabash, IN",
  "Waco, TX",
  "Wahpeton, ND-MN",
  "Walla Walla, WA",
  "Wapakoneta, OH",
  "Warner Robins, GA",
  "Warrensburg, MO",
  "Warsaw, IN",
  "Washington Court House, OH",
  "Washington, IN",
  "Washington, NC",
  "Washington-Arlington-Alexandria, DC-VA-MD-WV",
  "Waterloo-Cedar Falls, IA",
  "Watertown, SD",
  "Watertown-Fort Atkinson, WI",
  "Watertown-Fort Drum, NY",
  "Wauchula, FL",
  "Wausau-Weston, WI",
  "Waycross, GA",
  "Weatherford, OK",
  "Weirton-Steubenville, WV-OH",
  "Wenatchee, WA",
  "West Plains, MO",
  "West Point, MS",
  "Wheeling, WV-OH",
  "Whitewater, WI",
  "Wichita Falls, TX",
  "Wichita, KS",
  "Williamsport, PA",
  "Williston, ND",
  "Willmar, MN",
  "Wilmington, NC",
  "Wilmington, OH",
  "Wilson, NC",
  "Winchester, VA-WV",
  "Winfield, KS",
  "Winnemucca, NV",
  "Winona, MN",
  "Winston-Salem, NC",
  "Wisconsin Rapids-Marshfield, WI",
  "Woodward, OK",
  "Wooster, OH",
  "Worcester, MA-CT",
  "Yakima, WA",
  "Yankton, SD",
  "York-Hanover, PA",
  "Youngstown-Warren-Boardman, OH-PA",
  "Yuba City, CA",
  "Yuma, AZ",
  "Zanesville, OH",
  "Zapata, TX",
  "Aguadilla-Isabela, PR",
  "Altus, OK",
  "Arecibo, PR",
  "Atchison, KS",
  "Athens, TN",
  "Brownsville, TN",
  "Central City, KY",
  "Coamo, PR",
  "Coco, PR",
  "Connersville, IN",
  "Craig, CO",
  "Crescent City, CA",
  "Dayton, TN",
  "Fitzgerald, GA",
  "Forrest City, AR",
  "Galesburg, IL",
  "Guymon, OK",
  "Helena-West Helena, AR",
  "Kennett, MO",
  "Lawrenceburg, TN",
  "Lewisburg, PA",
  "Lewisburg, TN",
  "Liberal, KS",
  "Lincoln, IL",
  "Lock Haven, PA",
  "Logansport, IN",
  "Malvern, AR",
  "Martin, TN",
  "Mayag ez, PR",
  "Meadville, PA",
  "Mount Vernon, IL",
  "Paris, TN",
  "Ponce, PR",
  "Portales, NM",
  "San Germ n, PR",
  "Santa Isabel, PR",
  "St. Marys, PA",
  "Sterling, CO",
  "Vermillion, SD",
  "Vernon, TX",
  "Warren, PA",
  "Worthington, MN",
  "Yauco, PR",
];

export const bq_location_type = [
  "Business",
  "Legal",
  "Officer Company",
  "Officer Person",
];
