export const Metro = [
  { value: "Aberdeen, SD", title: "Aberdeen, SD" },
  { value: "Aberdeen, WA", title: "Aberdeen, WA" },
  { value: "Abilene, TX", title: "Abilene, TX" },
  { value: "Ada, OK", title: "Ada, OK" },
  { value: "Adrian, MI", title: "Adrian, MI" },
  { value: "Aguadilla-Isabela, PR", title: "Aguadilla-Isabela, PR" },
  { value: "Akron, OH", title: "Akron, OH" },
  { value: "Alamogordo, NM", title: "Alamogordo, NM" },
  { value: "Albany, GA", title: "Albany, GA" },
  { value: "Albany-Lebanon, OR", title: "Albany-Lebanon, OR" },
  {
    value: "Albany-Schenectady-Troy, NY",
    title: "Albany-Schenectady-Troy, NY",
  },
  { value: "Albemarle, NC", title: "Albemarle, NC" },
  { value: "Albert Lea, MN", title: "Albert Lea, MN" },
  { value: "Albertville, AL", title: "Albertville, AL" },
  { value: "Albuquerque, NM", title: "Albuquerque, NM" },
  { value: "Alexander City, AL", title: "Alexander City, AL" },
  { value: "Alexandria, LA", title: "Alexandria, LA" },
  { value: "Alexandria, MN", title: "Alexandria, MN" },
  { value: "Alice, TX", title: "Alice, TX" },
  {
    value: "Allentown-Bethlehem-Easton, PA-NJ",
    title: "Allentown-Bethlehem-Easton, PA-NJ",
  },
  { value: "Alma, MI", title: "Alma, MI" },
  { value: "Alpena, MI", title: "Alpena, MI" },
  { value: "Altoona, PA", title: "Altoona, PA" },
  { value: "Altus, OK", title: "Altus, OK" },
  { value: "Amarillo, TX", title: "Amarillo, TX" },
  { value: "Americus, GA", title: "Americus, GA" },
  { value: "Ames, IA", title: "Ames, IA" },
  { value: "Amsterdam, NY", title: "Amsterdam, NY" },
  { value: "Anchorage, AK", title: "Anchorage, AK" },
  { value: "Andrews, TX", title: "Andrews, TX" },
  { value: "Angola, IN", title: "Angola, IN" },
  { value: "Ann Arbor, MI", title: "Ann Arbor, MI" },
  { value: "Anniston-Oxford, AL", title: "Anniston-Oxford, AL" },
  { value: "Appleton, WI", title: "Appleton, WI" },
  { value: "Arcadia, FL", title: "Arcadia, FL" },
  { value: "Ardmore, OK", title: "Ardmore, OK" },
  { value: "Arecibo, PR", title: "Arecibo, PR" },
  { value: "Arkadelphia, AR", title: "Arkadelphia, AR" },
  { value: "Asheville, NC", title: "Asheville, NC" },
  { value: "Ashland, OH", title: "Ashland, OH" },
  { value: "Ashtabula, OH", title: "Ashtabula, OH" },
  { value: "Astoria, OR", title: "Astoria, OR" },
  { value: "Atchison, KS", title: "Atchison, KS" },
  { value: "Athens, OH", title: "Athens, OH" },
  { value: "Athens, TN", title: "Athens, TN" },
  { value: "Athens, TX", title: "Athens, TX" },
  { value: "Athens-Clarke County, GA", title: "Athens-Clarke County, GA" },
  {
    value: "Atlanta-Sandy Springs-Alpharetta, GA",
    title: "Atlanta-Sandy Springs-Alpharetta, GA",
  },
  {
    value: "Atlantic City-Hammonton, NJ",
    title: "Atlantic City-Hammonton, NJ",
  },
  { value: "Atmore, AL", title: "Atmore, AL" },
  { value: "Auburn, IN", title: "Auburn, IN" },
  { value: "Auburn, NY", title: "Auburn, NY" },
  { value: "Auburn-Opelika, AL", title: "Auburn-Opelika, AL" },
  {
    value: "Augusta-Richmond County, GA-SC",
    title: "Augusta-Richmond County, GA-SC",
  },
  { value: "Augusta-Waterville, ME", title: "Augusta-Waterville, ME" },
  { value: "Austin, MN", title: "Austin, MN" },
  {
    value: "Austin-Round Rock-Georgetown, TX",
    title: "Austin-Round Rock-Georgetown, TX",
  },
  { value: "Bainbridge, GA", title: "Bainbridge, GA" },
  { value: "Bakersfield, CA", title: "Bakersfield, CA" },
  {
    value: "Baltimore-Columbia-Towson, MD",
    title: "Baltimore-Columbia-Towson, MD",
  },
  { value: "Bangor, ME", title: "Bangor, ME" },
  { value: "Baraboo, WI", title: "Baraboo, WI" },
  { value: "Bardstown, KY", title: "Bardstown, KY" },
  { value: "Barnstable Town, MA", title: "Barnstable Town, MA" },
  { value: "Barre, VT", title: "Barre, VT" },
  { value: "Bartlesville, OK", title: "Bartlesville, OK" },
  { value: "Batavia, NY", title: "Batavia, NY" },
  { value: "Batesville, AR", title: "Batesville, AR" },
  { value: "Baton Rouge, LA", title: "Baton Rouge, LA" },
  { value: "Battle Creek, MI", title: "Battle Creek, MI" },
  { value: "Bay City, MI", title: "Bay City, MI" },
  { value: "Bay City, TX", title: "Bay City, TX" },
  { value: "Beatrice, NE", title: "Beatrice, NE" },
  { value: "Beaumont-Port Arthur, TX", title: "Beaumont-Port Arthur, TX" },
  { value: "Beaver Dam, WI", title: "Beaver Dam, WI" },
  { value: "Beckley, WV", title: "Beckley, WV" },
  { value: "Bedford, IN", title: "Bedford, IN" },
  { value: "Beeville, TX", title: "Beeville, TX" },
  { value: "Bellefontaine, OH", title: "Bellefontaine, OH" },
  { value: "Bellingham, WA", title: "Bellingham, WA" },
  { value: "Bemidji, MN", title: "Bemidji, MN" },
  { value: "Bend, OR", title: "Bend, OR" },
  { value: "Bennettsville, SC", title: "Bennettsville, SC" },
  { value: "Bennington, VT", title: "Bennington, VT" },
  { value: "Berlin, NH", title: "Berlin, NH" },
  { value: "Big Rapids, MI", title: "Big Rapids, MI" },
  { value: "Big Spring, TX", title: "Big Spring, TX" },
  { value: "Big Stone Gap, VA", title: "Big Stone Gap, VA" },
  { value: "Billings, MT", title: "Billings, MT" },
  { value: "Binghamton, NY", title: "Binghamton, NY" },
  { value: "Birmingham-Hoover, AL", title: "Birmingham-Hoover, AL" },
  { value: "Bismarck, ND", title: "Bismarck, ND" },
  { value: "Blackfoot, ID", title: "Blackfoot, ID" },
  {
    value: "Blacksburg-Christiansburg, VA",
    title: "Blacksburg-Christiansburg, VA",
  },
  { value: "Bloomington, IL", title: "Bloomington, IL" },
  { value: "Bloomington, IN", title: "Bloomington, IN" },
  { value: "Bloomsburg-Berwick, PA", title: "Bloomsburg-Berwick, PA" },
  { value: "Bluefield, WV-VA", title: "Bluefield, WV-VA" },
  { value: "Bluffton, IN", title: "Bluffton, IN" },
  { value: "Blytheville, AR", title: "Blytheville, AR" },
  { value: "Bogalusa, LA", title: "Bogalusa, LA" },
  { value: "Boise City, ID", title: "Boise City, ID" },
  { value: "Bonham, TX", title: "Bonham, TX" },
  { value: "Boone, NC", title: "Boone, NC" },
  { value: "Borger, TX", title: "Borger, TX" },
  {
    value: "Boston-Cambridge-Newton, MA-NH",
    title: "Boston-Cambridge-Newton, MA-NH",
  },
  { value: "Boulder, CO", title: "Boulder, CO" },
  { value: "Bowling Green, KY", title: "Bowling Green, KY" },
  { value: "Bozeman, MT", title: "Bozeman, MT" },
  { value: "Bradford, PA", title: "Bradford, PA" },
  { value: "Brainerd, MN", title: "Brainerd, MN" },
  { value: "Branson, MO", title: "Branson, MO" },
  { value: "Breckenridge, CO", title: "Breckenridge, CO" },
  {
    value: "Bremerton-Silverdale-Port Orchard, WA",
    title: "Bremerton-Silverdale-Port Orchard, WA",
  },
  { value: "Brenham, TX", title: "Brenham, TX" },
  { value: "Brevard, NC", title: "Brevard, NC" },
  {
    value: "Bridgeport-Stamford-Norwalk, CT",
    title: "Bridgeport-Stamford-Norwalk, CT",
  },
  { value: "Brookhaven, MS", title: "Brookhaven, MS" },
  { value: "Brookings, OR", title: "Brookings, OR" },
  { value: "Brookings, SD", title: "Brookings, SD" },
  { value: "Brownsville, TN", title: "Brownsville, TN" },
  { value: "Brownsville-Harlingen, TX", title: "Brownsville-Harlingen, TX" },
  { value: "Brownwood, TX", title: "Brownwood, TX" },
  { value: "Brunswick, GA", title: "Brunswick, GA" },
  { value: "Bucyrus-Galion, OH", title: "Bucyrus-Galion, OH" },
  { value: "Buffalo-Cheektowaga, NY", title: "Buffalo-Cheektowaga, NY" },
  { value: "Burley, ID", title: "Burley, ID" },
  { value: "Burlington, IA-IL", title: "Burlington, IA-IL" },
  { value: "Burlington, NC", title: "Burlington, NC" },
  {
    value: "Burlington-South Burlington, VT",
    title: "Burlington-South Burlington, VT",
  },
  { value: "Butte-Silver Bow, MT", title: "Butte-Silver Bow, MT" },
  { value: "Cadillac, MI", title: "Cadillac, MI" },
  { value: "Calhoun, GA", title: "Calhoun, GA" },
  {
    value: "California-Lexington Park, MD",
    title: "California-Lexington Park, MD",
  },
  { value: "Cambridge, MD", title: "Cambridge, MD" },
  { value: "Cambridge, OH", title: "Cambridge, OH" },
  { value: "Camden, AR", title: "Camden, AR" },
  { value: "Campbellsville, KY", title: "Campbellsville, KY" },
  { value: "Canton-Massillon, OH", title: "Canton-Massillon, OH" },
  { value: "Cape Coral-Fort Myers, FL", title: "Cape Coral-Fort Myers, FL" },
  { value: "Cape Girardeau, MO-IL", title: "Cape Girardeau, MO-IL" },
  { value: "Carbondale-Marion, IL", title: "Carbondale-Marion, IL" },
  { value: "Carlsbad-Artesia, NM", title: "Carlsbad-Artesia, NM" },
  { value: "Carroll, IA", title: "Carroll, IA" },
  { value: "Carson City, NV", title: "Carson City, NV" },
  { value: "Casper, WY", title: "Casper, WY" },
  { value: "Ca�on City, CO", title: "Ca�on City, CO" },
  { value: "Cedar City, UT", title: "Cedar City, UT" },
  { value: "Cedar Rapids, IA", title: "Cedar Rapids, IA" },
  { value: "Cedartown, GA", title: "Cedartown, GA" },
  { value: "Celina, OH", title: "Celina, OH" },
  { value: "Central City, KY", title: "Central City, KY" },
  { value: "Centralia, IL", title: "Centralia, IL" },
  { value: "Centralia, WA", title: "Centralia, WA" },
  {
    value: "Chambersburg-Waynesboro, PA",
    title: "Chambersburg-Waynesboro, PA",
  },
  { value: "Champaign-Urbana, IL", title: "Champaign-Urbana, IL" },
  { value: "Charleston, WV", title: "Charleston, WV" },
  { value: "Charleston-Mattoon, IL", title: "Charleston-Mattoon, IL" },
  {
    value: "Charleston-North Charleston, SC",
    title: "Charleston-North Charleston, SC",
  },
  {
    value: "Charlotte-Concord-Gastonia, NC-SC",
    title: "Charlotte-Concord-Gastonia, NC-SC",
  },
  { value: "Charlottesville, VA", title: "Charlottesville, VA" },
  { value: "Chattanooga, TN-GA", title: "Chattanooga, TN-GA" },
  { value: "Cheyenne, WY", title: "Cheyenne, WY" },
  {
    value: "Chicago-Naperville-Elgin, IL-IN-WI",
    title: "Chicago-Naperville-Elgin, IL-IN-WI",
  },
  { value: "Chico, CA", title: "Chico, CA" },
  { value: "Chillicothe, OH", title: "Chillicothe, OH" },
  { value: "Cincinnati, OH-KY-IN", title: "Cincinnati, OH-KY-IN" },
  { value: "Clarksburg, WV", title: "Clarksburg, WV" },
  { value: "Clarksdale, MS", title: "Clarksdale, MS" },
  { value: "Clarksville, TN-KY", title: "Clarksville, TN-KY" },
  { value: "Clearlake, CA", title: "Clearlake, CA" },
  { value: "Cleveland, MS", title: "Cleveland, MS" },
  { value: "Cleveland, TN", title: "Cleveland, TN" },
  { value: "Cleveland-Elyria, OH", title: "Cleveland-Elyria, OH" },
  { value: "Clewiston, FL", title: "Clewiston, FL" },
  { value: "Clinton, IA", title: "Clinton, IA" },
  { value: "Clovis, NM", title: "Clovis, NM" },
  { value: "Coamo, PR", title: "Coamo, PR" },
  { value: "Coeur dAlene, ID", title: "Coeur dAlene, ID" },
  { value: "Coffeyville, KS", title: "Coffeyville, KS" },
  { value: "Coldwater, MI", title: "Coldwater, MI" },
  { value: "College Station-Bryan, TX", title: "College Station-Bryan, TX" },
  { value: "Colorado Springs, CO", title: "Colorado Springs, CO" },
  { value: "Columbia, MO", title: "Columbia, MO" },
  { value: "Columbia, SC", title: "Columbia, SC" },
  { value: "Columbus, GA-AL", title: "Columbus, GA-AL" },
  { value: "Columbus, IN", title: "Columbus, IN" },
  { value: "Columbus, MS", title: "Columbus, MS" },
  { value: "Columbus, NE", title: "Columbus, NE" },
  { value: "Columbus, OH", title: "Columbus, OH" },
  { value: "Concord, NH", title: "Concord, NH" },
  { value: "Connersville, IN", title: "Connersville, IN" },
  { value: "Cookeville, TN", title: "Cookeville, TN" },
  { value: "Coos Bay, OR", title: "Coos Bay, OR" },
  { value: "Cordele, GA", title: "Cordele, GA" },
  { value: "Corinth, MS", title: "Corinth, MS" },
  { value: "Cornelia, GA", title: "Cornelia, GA" },
  { value: "Corning, NY", title: "Corning, NY" },
  { value: "Corpus Christi, TX", title: "Corpus Christi, TX" },
  { value: "Corsicana, TX", title: "Corsicana, TX" },
  { value: "Cortland, NY", title: "Cortland, NY" },
  { value: "Corvallis, OR", title: "Corvallis, OR" },
  { value: "Coshocton, OH", title: "Coshocton, OH" },
  { value: "Craig, CO", title: "Craig, CO" },
  { value: "Crawfordsville, IN", title: "Crawfordsville, IN" },
  { value: "Crescent City, CA", title: "Crescent City, CA" },
  {
    value: "Crestview-Fort Walton Beach-Destin, FL",
    title: "Crestview-Fort Walton Beach-Destin, FL",
  },
  { value: "Crossville, TN", title: "Crossville, TN" },
  { value: "Cullman, AL", title: "Cullman, AL" },
  { value: "Cullowhee, NC", title: "Cullowhee, NC" },
  { value: "Cumberland, MD-WV", title: "Cumberland, MD-WV" },
  {
    value: "Dallas-Fort Worth-Arlington, TX",
    title: "Dallas-Fort Worth-Arlington, TX",
  },
  { value: "Dalton, GA", title: "Dalton, GA" },
  { value: "Danville, IL", title: "Danville, IL" },
  { value: "Danville, KY", title: "Danville, KY" },
  { value: "Danville, VA", title: "Danville, VA" },
  { value: "Daphne-Fairhope-Foley, AL", title: "Daphne-Fairhope-Foley, AL" },
  {
    value: "Davenport-Moline-Rock Island, IA-IL",
    title: "Davenport-Moline-Rock Island, IA-IL",
  },
  { value: "Dayton, TN", title: "Dayton, TN" },
  { value: "Dayton-Kettering, OH", title: "Dayton-Kettering, OH" },
  { value: "DeRidder, LA", title: "DeRidder, LA" },
  { value: "Decatur, AL", title: "Decatur, AL" },
  { value: "Decatur, IL", title: "Decatur, IL" },
  { value: "Decatur, IN", title: "Decatur, IN" },
  { value: "Defiance, OH", title: "Defiance, OH" },
  { value: "Del Rio, TX", title: "Del Rio, TX" },
  {
    value: "Deltona-Daytona Beach-Ormond Beach, FL",
    title: "Deltona-Daytona Beach-Ormond Beach, FL",
  },
  { value: "Deming, NM", title: "Deming, NM" },
  { value: "Denver-Aurora-Lakewood, CO", title: "Denver-Aurora-Lakewood, CO" },
  {
    value: "Des Moines-West Des Moines, IA",
    title: "Des Moines-West Des Moines, IA",
  },
  {
    value: "Detroit-Warren-Dearborn, MI",
    title: "Detroit-Warren-Dearborn, MI",
  },
  { value: "Dickinson, ND", title: "Dickinson, ND" },
  { value: "Dixon, IL", title: "Dixon, IL" },
  { value: "Dodge City, KS", title: "Dodge City, KS" },
  { value: "Dothan, AL", title: "Dothan, AL" },
  { value: "Douglas, GA", title: "Douglas, GA" },
  { value: "Dover, DE", title: "Dover, DE" },
  { value: "DuBois, PA", title: "DuBois, PA" },
  { value: "Dublin, GA", title: "Dublin, GA" },
  { value: "Dubuque, IA", title: "Dubuque, IA" },
  { value: "Duluth, MN-WI", title: "Duluth, MN-WI" },
  { value: "Dumas, TX", title: "Dumas, TX" },
  { value: "Duncan, OK", title: "Duncan, OK" },
  { value: "Durango, CO", title: "Durango, CO" },
  { value: "Durant, OK", title: "Durant, OK" },
  { value: "Durham-Chapel Hill, NC", title: "Durham-Chapel Hill, NC" },
  { value: "Dyersburg, TN", title: "Dyersburg, TN" },
  { value: "Eagle Pass, TX", title: "Eagle Pass, TX" },
  { value: "East Stroudsburg, PA", title: "East Stroudsburg, PA" },
  { value: "Easton, MD", title: "Easton, MD" },
  { value: "Eau Claire, WI", title: "Eau Claire, WI" },
  { value: "Edwards, CO", title: "Edwards, CO" },
  { value: "Effingham, IL", title: "Effingham, IL" },
  { value: "El Campo, TX", title: "El Campo, TX" },
  { value: "El Centro, CA", title: "El Centro, CA" },
  { value: "El Dorado, AR", title: "El Dorado, AR" },
  { value: "El Paso, TX", title: "El Paso, TX" },
  { value: "Elizabeth City, NC", title: "Elizabeth City, NC" },
  {
    value: "Elizabethtown-Fort Knox, KY",
    title: "Elizabethtown-Fort Knox, KY",
  },
  { value: "Elk City, OK", title: "Elk City, OK" },
  { value: "Elkhart-Goshen, IN", title: "Elkhart-Goshen, IN" },
  { value: "Elkins, WV", title: "Elkins, WV" },
  { value: "Elko, NV", title: "Elko, NV" },
  { value: "Ellensburg, WA", title: "Ellensburg, WA" },
  { value: "Elmira, NY", title: "Elmira, NY" },
  { value: "Emporia, KS", title: "Emporia, KS" },
  { value: "Enid, OK", title: "Enid, OK" },
  { value: "Enterprise, AL", title: "Enterprise, AL" },
  { value: "Erie, PA", title: "Erie, PA" },
  { value: "Escanaba, MI", title: "Escanaba, MI" },
  { value: "Espa�ola, NM", title: "Espa�ola, NM" },
  { value: "Eufaula, AL-GA", title: "Eufaula, AL-GA" },
  { value: "Eugene-Springfield, OR", title: "Eugene-Springfield, OR" },
  { value: "Eureka-Arcata, CA", title: "Eureka-Arcata, CA" },
  { value: "Evanston, WY", title: "Evanston, WY" },
  { value: "Evansville, IN-KY", title: "Evansville, IN-KY" },
  { value: "Fairbanks, AK", title: "Fairbanks, AK" },
  { value: "Fairfield, IA", title: "Fairfield, IA" },
  { value: "Fairmont, MN", title: "Fairmont, MN" },
  { value: "Fairmont, WV", title: "Fairmont, WV" },
  { value: "Fallon, NV", title: "Fallon, NV" },
  { value: "Fargo, ND-MN", title: "Fargo, ND-MN" },
  { value: "Faribault-Northfield, MN", title: "Faribault-Northfield, MN" },
  { value: "Farmington, MO", title: "Farmington, MO" },
  { value: "Farmington, NM", title: "Farmington, NM" },
  { value: "Fayetteville, NC", title: "Fayetteville, NC" },
  {
    value: "Fayetteville-Springdale-Rogers, AR",
    title: "Fayetteville-Springdale-Rogers, AR",
  },
  { value: "Fergus Falls, MN", title: "Fergus Falls, MN" },
  { value: "Fernley, NV", title: "Fernley, NV" },
  { value: "Findlay, OH", title: "Findlay, OH" },
  { value: "Fitzgerald, GA", title: "Fitzgerald, GA" },
  { value: "Flagstaff, AZ", title: "Flagstaff, AZ" },
  { value: "Flint, MI", title: "Flint, MI" },
  { value: "Florence, SC", title: "Florence, SC" },
  { value: "Florence-Muscle Shoals, AL", title: "Florence-Muscle Shoals, AL" },
  { value: "Fond du Lac, WI", title: "Fond du Lac, WI" },
  { value: "Forest City, NC", title: "Forest City, NC" },
  { value: "Forrest City, AR", title: "Forrest City, AR" },
  { value: "Fort Collins, CO", title: "Fort Collins, CO" },
  { value: "Fort Dodge, IA", title: "Fort Dodge, IA" },
  { value: "Fort Leonard Wood, MO", title: "Fort Leonard Wood, MO" },
  {
    value: "Fort Madison-Keokuk, IA-IL-MO",
    title: "Fort Madison-Keokuk, IA-IL-MO",
  },
  { value: "Fort Morgan, CO", title: "Fort Morgan, CO" },
  { value: "Fort Payne, AL", title: "Fort Payne, AL" },
  { value: "Fort Polk South, LA", title: "Fort Polk South, LA" },
  { value: "Fort Smith, AR-OK", title: "Fort Smith, AR-OK" },
  { value: "Fort Wayne, IN", title: "Fort Wayne, IN" },
  { value: "Frankfort, IN", title: "Frankfort, IN" },
  { value: "Frankfort, KY", title: "Frankfort, KY" },
  { value: "Fredericksburg, TX", title: "Fredericksburg, TX" },
  { value: "Freeport, IL", title: "Freeport, IL" },
  { value: "Fremont, NE", title: "Fremont, NE" },
  { value: "Fremont, OH", title: "Fremont, OH" },
  { value: "Fresno, CA", title: "Fresno, CA" },
  { value: "Gadsden, AL", title: "Gadsden, AL" },
  { value: "Gaffney, SC", title: "Gaffney, SC" },
  { value: "Gainesville, FL", title: "Gainesville, FL" },
  { value: "Gainesville, GA", title: "Gainesville, GA" },
  { value: "Gainesville, TX", title: "Gainesville, TX" },
  { value: "Galesburg, IL", title: "Galesburg, IL" },
  { value: "Gallup, NM", title: "Gallup, NM" },
  { value: "Garden City, KS", title: "Garden City, KS" },
  { value: "Gardnerville Ranchos, NV", title: "Gardnerville Ranchos, NV" },
  { value: "Georgetown, SC", title: "Georgetown, SC" },
  { value: "Gettysburg, PA", title: "Gettysburg, PA" },
  { value: "Gillette, WY", title: "Gillette, WY" },
  { value: "Glasgow, KY", title: "Glasgow, KY" },
  { value: "Glens Falls, NY", title: "Glens Falls, NY" },
  { value: "Glenwood Springs, CO", title: "Glenwood Springs, CO" },
  { value: "Gloversville, NY", title: "Gloversville, NY" },
  { value: "Goldsboro, NC", title: "Goldsboro, NC" },
  { value: "Granbury, TX", title: "Granbury, TX" },
  { value: "Grand Forks, ND-MN", title: "Grand Forks, ND-MN" },
  { value: "Grand Island, NE", title: "Grand Island, NE" },
  { value: "Grand Junction, CO", title: "Grand Junction, CO" },
  { value: "Grand Rapids, MN", title: "Grand Rapids, MN" },
  { value: "Grand Rapids-Kentwood, MI", title: "Grand Rapids-Kentwood, MI" },
  { value: "Grants Pass, OR", title: "Grants Pass, OR" },
  { value: "Grants, NM", title: "Grants, NM" },
  { value: "Great Bend, KS", title: "Great Bend, KS" },
  { value: "Great Falls, MT", title: "Great Falls, MT" },
  { value: "Greeley, CO", title: "Greeley, CO" },
  { value: "Green Bay, WI", title: "Green Bay, WI" },
  { value: "Greeneville, TN", title: "Greeneville, TN" },
  { value: "Greensboro-High Point, NC", title: "Greensboro-High Point, NC" },
  { value: "Greensburg, IN", title: "Greensburg, IN" },
  { value: "Greenville, MS", title: "Greenville, MS" },
  { value: "Greenville, NC", title: "Greenville, NC" },
  { value: "Greenville, OH", title: "Greenville, OH" },
  { value: "Greenville-Anderson, SC", title: "Greenville-Anderson, SC" },
  { value: "Greenwood, MS", title: "Greenwood, MS" },
  { value: "Greenwood, SC", title: "Greenwood, SC" },
  { value: "Grenada, MS", title: "Grenada, MS" },
  { value: "Guayama, PR", title: "Guayama, PR" },
  { value: "Gulfport-Biloxi, MS", title: "Gulfport-Biloxi, MS" },
  { value: "Guymon, OK", title: "Guymon, OK" },
  {
    value: "Hagerstown-Martinsburg, MD-WV",
    title: "Hagerstown-Martinsburg, MD-WV",
  },
  { value: "Hailey, ID", title: "Hailey, ID" },
  { value: "Hammond, LA", title: "Hammond, LA" },
  { value: "Hanford-Corcoran, CA", title: "Hanford-Corcoran, CA" },
  { value: "Hannibal, MO", title: "Hannibal, MO" },
  { value: "Harrisburg-Carlisle, PA", title: "Harrisburg-Carlisle, PA" },
  { value: "Harrison, AR", title: "Harrison, AR" },
  { value: "Harrisonburg, VA", title: "Harrisonburg, VA" },
  {
    value: "Hartford-East Hartford-Middletown, CT",
    title: "Hartford-East Hartford-Middletown, CT",
  },
  { value: "Hastings, NE", title: "Hastings, NE" },
  { value: "Hattiesburg, MS", title: "Hattiesburg, MS" },
  { value: "Hays, KS", title: "Hays, KS" },
  { value: "Heber, UT", title: "Heber, UT" },
  { value: "Helena, MT", title: "Helena, MT" },
  { value: "Helena-West Helena, AR", title: "Helena-West Helena, AR" },
  { value: "Henderson, NC", title: "Henderson, NC" },
  { value: "Hereford, TX", title: "Hereford, TX" },
  { value: "Hermiston-Pendleton, OR", title: "Hermiston-Pendleton, OR" },
  {
    value: "Hickory-Lenoir-Morganton, NC",
    title: "Hickory-Lenoir-Morganton, NC",
  },
  { value: "Hillsdale, MI", title: "Hillsdale, MI" },
  { value: "Hilo, HI", title: "Hilo, HI" },
  {
    value: "Hilton Head Island-Bluffton, SC",
    title: "Hilton Head Island-Bluffton, SC",
  },
  { value: "Hinesville, GA", title: "Hinesville, GA" },
  { value: "Hobbs, NM", title: "Hobbs, NM" },
  { value: "Holland, MI", title: "Holland, MI" },
  { value: "Homosassa Springs, FL", title: "Homosassa Springs, FL" },
  { value: "Hood River, OR", title: "Hood River, OR" },
  { value: "Hope, AR", title: "Hope, AR" },
  { value: "Hot Springs, AR", title: "Hot Springs, AR" },
  { value: "Houghton, MI", title: "Houghton, MI" },
  { value: "Houma-Thibodaux, LA", title: "Houma-Thibodaux, LA" },
  {
    value: "Houston-The Woodlands-Sugar Land, TX",
    title: "Houston-The Woodlands-Sugar Land, TX",
  },
  { value: "Hudson, NY", title: "Hudson, NY" },
  { value: "Huntingdon, PA", title: "Huntingdon, PA" },
  { value: "Huntington, IN", title: "Huntington, IN" },
  {
    value: "Huntington-Ashland, WV-KY-OH",
    title: "Huntington-Ashland, WV-KY-OH",
  },
  { value: "Huntsville, AL", title: "Huntsville, AL" },
  { value: "Huntsville, TX", title: "Huntsville, TX" },
  { value: "Huron, SD", title: "Huron, SD" },
  { value: "Hutchinson, KS", title: "Hutchinson, KS" },
  { value: "Hutchinson, MN", title: "Hutchinson, MN" },
  { value: "Idaho Falls, ID", title: "Idaho Falls, ID" },
  { value: "Indiana, PA", title: "Indiana, PA" },
  {
    value: "Indianapolis-Carmel-Anderson, IN",
    title: "Indianapolis-Carmel-Anderson, IN",
  },
  { value: "Indianola, MS", title: "Indianola, MS" },
  { value: "Iowa City, IA", title: "Iowa City, IA" },
  { value: "Iron Mountain, MI-WI", title: "Iron Mountain, MI-WI" },
  { value: "Ithaca, NY", title: "Ithaca, NY" },
  { value: "Jackson, MI", title: "Jackson, MI" },
  { value: "Jackson, MS", title: "Jackson, MS" },
  { value: "Jackson, OH", title: "Jackson, OH" },
  { value: "Jackson, TN", title: "Jackson, TN" },
  { value: "Jackson, WY-ID", title: "Jackson, WY-ID" },
  { value: "Jacksonville, FL", title: "Jacksonville, FL" },
  { value: "Jacksonville, IL", title: "Jacksonville, IL" },
  { value: "Jacksonville, NC", title: "Jacksonville, NC" },
  { value: "Jacksonville, TX", title: "Jacksonville, TX" },
  { value: "Jamestown, ND", title: "Jamestown, ND" },
  {
    value: "Jamestown-Dunkirk-Fredonia, NY",
    title: "Jamestown-Dunkirk-Fredonia, NY",
  },
  { value: "Janesville-Beloit, WI", title: "Janesville-Beloit, WI" },
  { value: "Jasper, AL", title: "Jasper, AL" },
  { value: "Jasper, IN", title: "Jasper, IN" },
  { value: "Jayuya, PR", title: "Jayuya, PR" },
  { value: "Jefferson City, MO", title: "Jefferson City, MO" },
  { value: "Jefferson, GA", title: "Jefferson, GA" },
  { value: "Jennings, LA", title: "Jennings, LA" },
  { value: "Jesup, GA", title: "Jesup, GA" },
  { value: "Johnson City, TN", title: "Johnson City, TN" },
  { value: "Johnstown, PA", title: "Johnstown, PA" },
  { value: "Jonesboro, AR", title: "Jonesboro, AR" },
  { value: "Joplin, MO", title: "Joplin, MO" },
  { value: "Juneau, AK", title: "Juneau, AK" },
  {
    value: "Kahului-Wailuku-Lahaina, HI",
    title: "Kahului-Wailuku-Lahaina, HI",
  },
  { value: "Kalamazoo-Portage, MI", title: "Kalamazoo-Portage, MI" },
  { value: "Kalispell, MT", title: "Kalispell, MT" },
  { value: "Kankakee, IL", title: "Kankakee, IL" },
  { value: "Kansas City, MO-KS", title: "Kansas City, MO-KS" },
  { value: "Kapaa, HI", title: "Kapaa, HI" },
  { value: "Kearney, NE", title: "Kearney, NE" },
  { value: "Keene, NH", title: "Keene, NH" },
  { value: "Kendallville, IN", title: "Kendallville, IN" },
  { value: "Kennett, MO", title: "Kennett, MO" },
  { value: "Kennewick-Richland, WA", title: "Kennewick-Richland, WA" },
  { value: "Kerrville, TX", title: "Kerrville, TX" },
  { value: "Ketchikan, AK", title: "Ketchikan, AK" },
  { value: "Key West, FL", title: "Key West, FL" },
  { value: "Kill Devil Hills, NC", title: "Kill Devil Hills, NC" },
  { value: "Killeen-Temple, TX", title: "Killeen-Temple, TX" },
  { value: "Kingsport-Bristol, TN-VA", title: "Kingsport-Bristol, TN-VA" },
  { value: "Kingston, NY", title: "Kingston, NY" },
  { value: "Kingsville, TX", title: "Kingsville, TX" },
  { value: "Kinston, NC", title: "Kinston, NC" },
  { value: "Kirksville, MO", title: "Kirksville, MO" },
  { value: "Klamath Falls, OR", title: "Klamath Falls, OR" },
  { value: "Knoxville, TN", title: "Knoxville, TN" },
  { value: "Kokomo, IN", title: "Kokomo, IN" },
  { value: "La Crosse-Onalaska, WI-MN", title: "La Crosse-Onalaska, WI-MN" },
  { value: "La Grande, OR", title: "La Grande, OR" },
  { value: "LaGrange, GA-AL", title: "LaGrange, GA-AL" },
  { value: "Laconia, NH", title: "Laconia, NH" },
  { value: "Lafayette, LA", title: "Lafayette, LA" },
  {
    value: "Lafayette-West Lafayette, IN",
    title: "Lafayette-West Lafayette, IN",
  },
  { value: "Lake Charles, LA", title: "Lake Charles, LA" },
  { value: "Lake City, FL", title: "Lake City, FL" },
  {
    value: "Lake Havasu City-Kingman, AZ",
    title: "Lake Havasu City-Kingman, AZ",
  },
  { value: "Lakeland-Winter Haven, FL", title: "Lakeland-Winter Haven, FL" },
  { value: "Lamesa, TX", title: "Lamesa, TX" },
  { value: "Lancaster, PA", title: "Lancaster, PA" },
  { value: "Lansing-East Lansing, MI", title: "Lansing-East Lansing, MI" },
  { value: "Laramie, WY", title: "Laramie, WY" },
  { value: "Laredo, TX", title: "Laredo, TX" },
  { value: "Las Cruces, NM", title: "Las Cruces, NM" },
  { value: "Las Vegas, NM", title: "Las Vegas, NM" },
  {
    value: "Las Vegas-Henderson-Paradise, NV",
    title: "Las Vegas-Henderson-Paradise, NV",
  },
  { value: "Laurel, MS", title: "Laurel, MS" },
  { value: "Laurinburg, NC", title: "Laurinburg, NC" },
  { value: "Lawrence, KS", title: "Lawrence, KS" },
  { value: "Lawrenceburg, TN", title: "Lawrenceburg, TN" },
  { value: "Lawton, OK", title: "Lawton, OK" },
  { value: "Lebanon, MO", title: "Lebanon, MO" },
  { value: "Lebanon, NH-VT", title: "Lebanon, NH-VT" },
  { value: "Lebanon, PA", title: "Lebanon, PA" },
  { value: "Levelland, TX", title: "Levelland, TX" },
  { value: "Lewisburg, PA", title: "Lewisburg, PA" },
  { value: "Lewisburg, TN", title: "Lewisburg, TN" },
  { value: "Lewiston, ID-WA", title: "Lewiston, ID-WA" },
  { value: "Lewiston-Auburn, ME", title: "Lewiston-Auburn, ME" },
  { value: "Lewistown, PA", title: "Lewistown, PA" },
  { value: "Lexington, NE", title: "Lexington, NE" },
  { value: "Lexington-Fayette, KY", title: "Lexington-Fayette, KY" },
  { value: "Liberal, KS", title: "Liberal, KS" },
  { value: "Lima, OH", title: "Lima, OH" },
  { value: "Lincoln, IL", title: "Lincoln, IL" },
  { value: "Lincoln, NE", title: "Lincoln, NE" },
  {
    value: "Little Rock-North Little Rock-Conway, AR",
    title: "Little Rock-North Little Rock-Conway, AR",
  },
  { value: "Lock Haven, PA", title: "Lock Haven, PA" },
  { value: "Logan, UT-ID", title: "Logan, UT-ID" },
  { value: "Logansport, IN", title: "Logansport, IN" },
  { value: "London, KY", title: "London, KY" },
  { value: "Longview, TX", title: "Longview, TX" },
  { value: "Longview, WA", title: "Longview, WA" },
  { value: "Los Alamos, NM", title: "Los Alamos, NM" },
  {
    value: "Los Angeles-Long Beach-Anaheim, CA",
    title: "Los Angeles-Long Beach-Anaheim, CA",
  },
  {
    value: "Louisville/Jefferson County, KY-IN",
    title: "Louisville/Jefferson County, KY-IN",
  },
  { value: "Lubbock, TX", title: "Lubbock, TX" },
  { value: "Ludington, MI", title: "Ludington, MI" },
  { value: "Lufkin, TX", title: "Lufkin, TX" },
  { value: "Lumberton, NC", title: "Lumberton, NC" },
  { value: "Lynchburg, VA", title: "Lynchburg, VA" },
  { value: "Macomb, IL", title: "Macomb, IL" },
  { value: "Macon-Bibb County, GA", title: "Macon-Bibb County, GA" },
  { value: "Madera, CA", title: "Madera, CA" },
  { value: "Madison, IN", title: "Madison, IN" },
  { value: "Madison, WI", title: "Madison, WI" },
  { value: "Madisonville, KY", title: "Madisonville, KY" },
  { value: "Magnolia, AR", title: "Magnolia, AR" },
  { value: "Malone, NY", title: "Malone, NY" },
  { value: "Malvern, AR", title: "Malvern, AR" },
  { value: "Manchester-Nashua, NH", title: "Manchester-Nashua, NH" },
  { value: "Manhattan, KS", title: "Manhattan, KS" },
  { value: "Manitowoc, WI", title: "Manitowoc, WI" },
  { value: "Mankato, MN", title: "Mankato, MN" },
  { value: "Mansfield, OH", title: "Mansfield, OH" },
  { value: "Marietta, OH", title: "Marietta, OH" },
  { value: "Marinette, WI-MI", title: "Marinette, WI-MI" },
  { value: "Marion, IN", title: "Marion, IN" },
  { value: "Marion, NC", title: "Marion, NC" },
  { value: "Marion, OH", title: "Marion, OH" },
  { value: "Marquette, MI", title: "Marquette, MI" },
  { value: "Marshall, MN", title: "Marshall, MN" },
  { value: "Marshall, MO", title: "Marshall, MO" },
  { value: "Marshalltown, IA", title: "Marshalltown, IA" },
  { value: "Martin, TN", title: "Martin, TN" },
  { value: "Martinsville, VA", title: "Martinsville, VA" },
  { value: "Maryville, MO", title: "Maryville, MO" },
  { value: "Mason City, IA", title: "Mason City, IA" },
  { value: "Mayag�ez, PR", title: "Mayag�ez, PR" },
  { value: "Mayfield, KY", title: "Mayfield, KY" },
  { value: "Maysville, KY", title: "Maysville, KY" },
  { value: "McAlester, OK", title: "McAlester, OK" },
  {
    value: "McAllen-Edinburg-Mission, TX",
    title: "McAllen-Edinburg-Mission, TX",
  },
  { value: "McComb, MS", title: "McComb, MS" },
  { value: "McMinnville, TN", title: "McMinnville, TN" },
  { value: "McPherson, KS", title: "McPherson, KS" },
  { value: "Meadville, PA", title: "Meadville, PA" },
  { value: "Medford, OR", title: "Medford, OR" },
  { value: "Memphis, TN-MS-AR", title: "Memphis, TN-MS-AR" },
  { value: "Menomonie, WI", title: "Menomonie, WI" },
  { value: "Merced, CA", title: "Merced, CA" },
  { value: "Meridian, MS", title: "Meridian, MS" },
  { value: "Mexico, MO", title: "Mexico, MO" },
  { value: "Miami, OK", title: "Miami, OK" },
  {
    value: "Miami-Fort Lauderdale-Pompano Beach, FL",
    title: "Miami-Fort Lauderdale-Pompano Beach, FL",
  },
  { value: "Michigan City-La Porte, IN", title: "Michigan City-La Porte, IN" },
  { value: "Middlesborough, KY", title: "Middlesborough, KY" },
  { value: "Midland, MI", title: "Midland, MI" },
  { value: "Midland, TX", title: "Midland, TX" },
  { value: "Milledgeville, GA", title: "Milledgeville, GA" },
  { value: "Milwaukee-Waukesha, WI", title: "Milwaukee-Waukesha, WI" },
  { value: "Minden, LA", title: "Minden, LA" },
  { value: "Mineral Wells, TX", title: "Mineral Wells, TX" },
  {
    value: "Minneapolis-St. Paul-Bloomington, MN-WI",
    title: "Minneapolis-St. Paul-Bloomington, MN-WI",
  },
  { value: "Minot, ND", title: "Minot, ND" },
  { value: "Missoula, MT", title: "Missoula, MT" },
  { value: "Mitchell, SD", title: "Mitchell, SD" },
  { value: "Moberly, MO", title: "Moberly, MO" },
  { value: "Mobile, AL", title: "Mobile, AL" },
  { value: "Modesto, CA", title: "Modesto, CA" },
  { value: "Monroe, LA", title: "Monroe, LA" },
  { value: "Monroe, MI", title: "Monroe, MI" },
  { value: "Montgomery, AL", title: "Montgomery, AL" },
  { value: "Montrose, CO", title: "Montrose, CO" },
  { value: "Morehead City, NC", title: "Morehead City, NC" },
  { value: "Morgan City, LA", title: "Morgan City, LA" },
  { value: "Morgantown, WV", title: "Morgantown, WV" },
  { value: "Morristown, TN", title: "Morristown, TN" },
  { value: "Moscow, ID", title: "Moscow, ID" },
  { value: "Moses Lake, WA", title: "Moses Lake, WA" },
  { value: "Moultrie, GA", title: "Moultrie, GA" },
  { value: "Mount Airy, NC", title: "Mount Airy, NC" },
  { value: "Mount Gay-Shamrock, WV", title: "Mount Gay-Shamrock, WV" },
  { value: "Mount Pleasant, MI", title: "Mount Pleasant, MI" },
  { value: "Mount Pleasant, TX", title: "Mount Pleasant, TX" },
  { value: "Mount Sterling, KY", title: "Mount Sterling, KY" },
  { value: "Mount Vernon, IL", title: "Mount Vernon, IL" },
  { value: "Mount Vernon, OH", title: "Mount Vernon, OH" },
  { value: "Mount Vernon-Anacortes, WA", title: "Mount Vernon-Anacortes, WA" },
  { value: "Mountain Home, AR", title: "Mountain Home, AR" },
  { value: "Mountain Home, ID", title: "Mountain Home, ID" },
  { value: "Muncie, IN", title: "Muncie, IN" },
  { value: "Murray, KY", title: "Murray, KY" },
  { value: "Muscatine, IA", title: "Muscatine, IA" },
  { value: "Muskegon, MI", title: "Muskegon, MI" },
  { value: "Muskogee, OK", title: "Muskogee, OK" },
  {
    value: "Myrtle Beach-Conway-North Myrtle Beach, SC-NC",
    title: "Myrtle Beach-Conway-North Myrtle Beach, SC-NC",
  },
  { value: "Nacogdoches, TX", title: "Nacogdoches, TX" },
  { value: "Napa, CA", title: "Napa, CA" },
  { value: "Naples-Marco Island, FL", title: "Naples-Marco Island, FL" },
  {
    value: "Nashville-Davidson--Murfreesboro--Franklin, TN",
    title: "Nashville-Davidson--Murfreesboro--Franklin, TN",
  },
  { value: "Natchez, MS-LA", title: "Natchez, MS-LA" },
  { value: "Natchitoches, LA", title: "Natchitoches, LA" },
  { value: "New Bern, NC", title: "New Bern, NC" },
  { value: "New Castle, IN", title: "New Castle, IN" },
  { value: "New Castle, PA", title: "New Castle, PA" },
  { value: "New Haven-Milford, CT", title: "New Haven-Milford, CT" },
  { value: "New Orleans-Metairie, LA", title: "New Orleans-Metairie, LA" },
  { value: "New Philadelphia-Dover, OH", title: "New Philadelphia-Dover, OH" },
  { value: "New Ulm, MN", title: "New Ulm, MN" },
  {
    value: "New York-Newark-Jersey City, NY-NJ-PA",
    title: "New York-Newark-Jersey City, NY-NJ-PA",
  },
  { value: "Newberry, SC", title: "Newberry, SC" },
  { value: "Newport, OR", title: "Newport, OR" },
  { value: "Newport, TN", title: "Newport, TN" },
  { value: "Niles, MI", title: "Niles, MI" },
  { value: "Nogales, AZ", title: "Nogales, AZ" },
  { value: "Norfolk, NE", title: "Norfolk, NE" },
  { value: "North Platte, NE", title: "North Platte, NE" },
  {
    value: "North Port-Sarasota-Bradenton, FL",
    title: "North Port-Sarasota-Bradenton, FL",
  },
  { value: "North Vernon, IN", title: "North Vernon, IN" },
  { value: "North Wilkesboro, NC", title: "North Wilkesboro, NC" },
  { value: "Norwalk, OH", title: "Norwalk, OH" },
  { value: "Norwich-New London, CT", title: "Norwich-New London, CT" },
  { value: "Oak Harbor, WA", title: "Oak Harbor, WA" },
  { value: "Ocala, FL", title: "Ocala, FL" },
  { value: "Ocean City, NJ", title: "Ocean City, NJ" },
  { value: "Odessa, TX", title: "Odessa, TX" },
  { value: "Ogden-Clearfield, UT", title: "Ogden-Clearfield, UT" },
  { value: "Ogdensburg-Massena, NY", title: "Ogdensburg-Massena, NY" },
  { value: "Oil City, PA", title: "Oil City, PA" },
  { value: "Okeechobee, FL", title: "Okeechobee, FL" },
  { value: "Oklahoma City, OK", title: "Oklahoma City, OK" },
  { value: "Olean, NY", title: "Olean, NY" },
  { value: "Olympia-Lacey-Tumwater, WA", title: "Olympia-Lacey-Tumwater, WA" },
  {
    value: "Omaha-Council Bluffs, NE-IA",
    title: "Omaha-Council Bluffs, NE-IA",
  },
  { value: "Oneonta, NY", title: "Oneonta, NY" },
  { value: "Ontario, OR-ID", title: "Ontario, OR-ID" },
  { value: "Opelousas, LA", title: "Opelousas, LA" },
  { value: "Orangeburg, SC", title: "Orangeburg, SC" },
  {
    value: "Orlando-Kissimmee-Sanford, FL",
    title: "Orlando-Kissimmee-Sanford, FL",
  },
  { value: "Oshkosh-Neenah, WI", title: "Oshkosh-Neenah, WI" },
  { value: "Oskaloosa, IA", title: "Oskaloosa, IA" },
  { value: "Othello, WA", title: "Othello, WA" },
  { value: "Ottawa, IL", title: "Ottawa, IL" },
  { value: "Ottawa, KS", title: "Ottawa, KS" },
  { value: "Ottumwa, IA", title: "Ottumwa, IA" },
  { value: "Owatonna, MN", title: "Owatonna, MN" },
  { value: "Owensboro, KY", title: "Owensboro, KY" },
  { value: "Oxford, MS", title: "Oxford, MS" },
  {
    value: "Oxnard-Thousand Oaks-Ventura, CA",
    title: "Oxnard-Thousand Oaks-Ventura, CA",
  },
  { value: "Ozark, AL", title: "Ozark, AL" },
  { value: "Paducah, KY-IL", title: "Paducah, KY-IL" },
  { value: "Pahrump, NV", title: "Pahrump, NV" },
  { value: "Palatka, FL", title: "Palatka, FL" },
  { value: "Palestine, TX", title: "Palestine, TX" },
  {
    value: "Palm Bay-Melbourne-Titusville, FL",
    title: "Palm Bay-Melbourne-Titusville, FL",
  },
  { value: "Pampa, TX", title: "Pampa, TX" },
  { value: "Panama City, FL", title: "Panama City, FL" },
  { value: "Paragould, AR", title: "Paragould, AR" },
  { value: "Paris, TN", title: "Paris, TN" },
  { value: "Paris, TX", title: "Paris, TX" },
  { value: "Parkersburg-Vienna, WV", title: "Parkersburg-Vienna, WV" },
  { value: "Parsons, KS", title: "Parsons, KS" },
  { value: "Payson, AZ", title: "Payson, AZ" },
  { value: "Pearsall, TX", title: "Pearsall, TX" },
  { value: "Pecos, TX", title: "Pecos, TX" },
  { value: "Pella, IA", title: "Pella, IA" },
  {
    value: "Pensacola-Ferry Pass-Brent, FL",
    title: "Pensacola-Ferry Pass-Brent, FL",
  },
  { value: "Peoria, IL", title: "Peoria, IL" },
  { value: "Peru, IN", title: "Peru, IN" },
  {
    value: "Philadelphia-Camden-Wilmington, PA-NJ-DE-MD",
    title: "Philadelphia-Camden-Wilmington, PA-NJ-DE-MD",
  },
  { value: "Phoenix-Mesa-Chandler, AZ", title: "Phoenix-Mesa-Chandler, AZ" },
  { value: "Picayune, MS", title: "Picayune, MS" },
  { value: "Pierre, SD", title: "Pierre, SD" },
  { value: "Pine Bluff, AR", title: "Pine Bluff, AR" },
  {
    value: "Pinehurst-Southern Pines, NC",
    title: "Pinehurst-Southern Pines, NC",
  },
  { value: "Pittsburg, KS", title: "Pittsburg, KS" },
  { value: "Pittsburgh, PA", title: "Pittsburgh, PA" },
  { value: "Pittsfield, MA", title: "Pittsfield, MA" },
  { value: "Plainview, TX", title: "Plainview, TX" },
  { value: "Platteville, WI", title: "Platteville, WI" },
  { value: "Plattsburgh, NY", title: "Plattsburgh, NY" },
  { value: "Plymouth, IN", title: "Plymouth, IN" },
  { value: "Pocatello, ID", title: "Pocatello, ID" },
  { value: "Point Pleasant, WV-OH", title: "Point Pleasant, WV-OH" },
  { value: "Ponca City, OK", title: "Ponca City, OK" },
  { value: "Ponce, PR", title: "Ponce, PR" },
  { value: "Pontiac, IL", title: "Pontiac, IL" },
  { value: "Poplar Bluff, MO", title: "Poplar Bluff, MO" },
  { value: "Port Angeles, WA", title: "Port Angeles, WA" },
  { value: "Port Lavaca, TX", title: "Port Lavaca, TX" },
  { value: "Port St. Lucie, FL", title: "Port St. Lucie, FL" },
  { value: "Portales, NM", title: "Portales, NM" },
  {
    value: "Portland-South Portland, ME",
    title: "Portland-South Portland, ME",
  },
  {
    value: "Portland-Vancouver-Hillsboro, OR-WA",
    title: "Portland-Vancouver-Hillsboro, OR-WA",
  },
  { value: "Portsmouth, OH", title: "Portsmouth, OH" },
  { value: "Pottsville, PA", title: "Pottsville, PA" },
  {
    value: "Poughkeepsie-Newburgh-Middletown, NY",
    title: "Poughkeepsie-Newburgh-Middletown, NY",
  },
  {
    value: "Prescott Valley-Prescott, AZ",
    title: "Prescott Valley-Prescott, AZ",
  },
  { value: "Price, UT", title: "Price, UT" },
  { value: "Prineville, OR", title: "Prineville, OR" },
  { value: "Providence-Warwick, RI-MA", title: "Providence-Warwick, RI-MA" },
  { value: "Provo-Orem, UT", title: "Provo-Orem, UT" },
  { value: "Pueblo, CO", title: "Pueblo, CO" },
  { value: "Pullman, WA", title: "Pullman, WA" },
  { value: "Punta Gorda, FL", title: "Punta Gorda, FL" },
  { value: "Quincy, IL-MO", title: "Quincy, IL-MO" },
  { value: "Racine, WI", title: "Racine, WI" },
  { value: "Raleigh-Cary, NC", title: "Raleigh-Cary, NC" },
  { value: "Rapid City, SD", title: "Rapid City, SD" },
  { value: "Raymondville, TX", title: "Raymondville, TX" },
  { value: "Reading, PA", title: "Reading, PA" },
  { value: "Red Bluff, CA", title: "Red Bluff, CA" },
  { value: "Red Wing, MN", title: "Red Wing, MN" },
  { value: "Redding, CA", title: "Redding, CA" },
  { value: "Reno, NV", title: "Reno, NV" },
  { value: "Rexburg, ID", title: "Rexburg, ID" },
  { value: "Richmond, IN", title: "Richmond, IN" },
  { value: "Richmond, VA", title: "Richmond, VA" },
  { value: "Richmond-Berea, KY", title: "Richmond-Berea, KY" },
  { value: "Rio Grande City-Roma, TX", title: "Rio Grande City-Roma, TX" },
  {
    value: "Riverside-San Bernardino-Ontario, CA",
    title: "Riverside-San Bernardino-Ontario, CA",
  },
  { value: "Riverton, WY", title: "Riverton, WY" },
  { value: "Roanoke Rapids, NC", title: "Roanoke Rapids, NC" },
  { value: "Roanoke, VA", title: "Roanoke, VA" },
  { value: "Rochelle, IL", title: "Rochelle, IL" },
  { value: "Rochester, MN", title: "Rochester, MN" },
  { value: "Rochester, NY", title: "Rochester, NY" },
  { value: "Rock Springs, WY", title: "Rock Springs, WY" },
  { value: "Rockford, IL", title: "Rockford, IL" },
  { value: "Rockingham, NC", title: "Rockingham, NC" },
  { value: "Rockport, TX", title: "Rockport, TX" },
  { value: "Rocky Mount, NC", title: "Rocky Mount, NC" },
  { value: "Rolla, MO", title: "Rolla, MO" },
  { value: "Rome, GA", title: "Rome, GA" },
  { value: "Roseburg, OR", title: "Roseburg, OR" },
  { value: "Roswell, NM", title: "Roswell, NM" },
  { value: "Ruidoso, NM", title: "Ruidoso, NM" },
  { value: "Russellville, AR", title: "Russellville, AR" },
  { value: "Ruston, LA", title: "Ruston, LA" },
  { value: "Rutland, VT", title: "Rutland, VT" },
  {
    value: "Sacramento-Roseville-Folsom, CA",
    title: "Sacramento-Roseville-Folsom, CA",
  },
  { value: "Safford, AZ", title: "Safford, AZ" },
  { value: "Saginaw, MI", title: "Saginaw, MI" },
  { value: "Salem, OH", title: "Salem, OH" },
  { value: "Salem, OR", title: "Salem, OR" },
  { value: "Salina, KS", title: "Salina, KS" },
  { value: "Salinas, CA", title: "Salinas, CA" },
  { value: "Salisbury, MD-DE", title: "Salisbury, MD-DE" },
  { value: "Salt Lake City, UT", title: "Salt Lake City, UT" },
  { value: "San Angelo, TX", title: "San Angelo, TX" },
  {
    value: "San Antonio-New Braunfels, TX",
    title: "San Antonio-New Braunfels, TX",
  },
  {
    value: "San Diego-Chula Vista-Carlsbad, CA",
    title: "San Diego-Chula Vista-Carlsbad, CA",
  },
  {
    value: "San Francisco-Oakland-Berkeley, CA",
    title: "San Francisco-Oakland-Berkeley, CA",
  },
  { value: "San Germ�n, PR", title: "San Germ�n, PR" },
  {
    value: "San Jose-Sunnyvale-Santa Clara, CA",
    title: "San Jose-Sunnyvale-Santa Clara, CA",
  },
  {
    value: "San Juan-Bayam�n-Caguas, PR",
    title: "San Juan-Bayam�n-Caguas, PR",
  },
  {
    value: "San Luis Obispo-Paso Robles, CA",
    title: "San Luis Obispo-Paso Robles, CA",
  },
  { value: "Sandpoint, ID", title: "Sandpoint, ID" },
  { value: "Sandusky, OH", title: "Sandusky, OH" },
  { value: "Sanford, NC", title: "Sanford, NC" },
  { value: "Santa Cruz-Watsonville, CA", title: "Santa Cruz-Watsonville, CA" },
  { value: "Santa Fe, NM", title: "Santa Fe, NM" },
  { value: "Santa Isabel, PR", title: "Santa Isabel, PR" },
  {
    value: "Santa Maria-Santa Barbara, CA",
    title: "Santa Maria-Santa Barbara, CA",
  },
  { value: "Santa Rosa-Petaluma, CA", title: "Santa Rosa-Petaluma, CA" },
  { value: "Sault Ste. Marie, MI", title: "Sault Ste. Marie, MI" },
  { value: "Savannah, GA", title: "Savannah, GA" },
  { value: "Sayre, PA", title: "Sayre, PA" },
  { value: "Scottsbluff, NE", title: "Scottsbluff, NE" },
  { value: "Scottsboro, AL", title: "Scottsboro, AL" },
  { value: "Scottsburg, IN", title: "Scottsburg, IN" },
  { value: "Scranton--Wilkes-Barre, PA", title: "Scranton--Wilkes-Barre, PA" },
  { value: "Searcy, AR", title: "Searcy, AR" },
  {
    value: "Seattle-Tacoma-Bellevue, WA",
    title: "Seattle-Tacoma-Bellevue, WA",
  },
  { value: "Sebastian-Vero Beach, FL", title: "Sebastian-Vero Beach, FL" },
  { value: "Sebring-Avon Park, FL", title: "Sebring-Avon Park, FL" },
  { value: "Sedalia, MO", title: "Sedalia, MO" },
  { value: "Selinsgrove, PA", title: "Selinsgrove, PA" },
  { value: "Selma, AL", title: "Selma, AL" },
  { value: "Seneca Falls, NY", title: "Seneca Falls, NY" },
  { value: "Seneca, SC", title: "Seneca, SC" },
  { value: "Sevierville, TN", title: "Sevierville, TN" },
  { value: "Seymour, IN", title: "Seymour, IN" },
  { value: "Shawano, WI", title: "Shawano, WI" },
  { value: "Shawnee, OK", title: "Shawnee, OK" },
  { value: "Sheboygan, WI", title: "Sheboygan, WI" },
  { value: "Shelby, NC", title: "Shelby, NC" },
  { value: "Shelbyville, TN", title: "Shelbyville, TN" },
  { value: "Shelton, WA", title: "Shelton, WA" },
  { value: "Sheridan, WY", title: "Sheridan, WY" },
  { value: "Sherman-Denison, TX", title: "Sherman-Denison, TX" },
  { value: "Show Low, AZ", title: "Show Low, AZ" },
  {
    value: "Shreveport-Bossier City, LA",
    title: "Shreveport-Bossier City, LA",
  },
  { value: "Sidney, OH", title: "Sidney, OH" },
  { value: "Sierra Vista-Douglas, AZ", title: "Sierra Vista-Douglas, AZ" },
  { value: "Sikeston, MO", title: "Sikeston, MO" },
  { value: "Silver City, NM", title: "Silver City, NM" },
  { value: "Sioux City, IA-NE-SD", title: "Sioux City, IA-NE-SD" },
  { value: "Sioux Falls, SD", title: "Sioux Falls, SD" },
  { value: "Snyder, TX", title: "Snyder, TX" },
  { value: "Somerset, KY", title: "Somerset, KY" },
  { value: "Somerset, PA", title: "Somerset, PA" },
  { value: "Sonora, CA", title: "Sonora, CA" },
  {
    value: "South Bend-Mishawaka, IN-MI",
    title: "South Bend-Mishawaka, IN-MI",
  },
  { value: "Spartanburg, SC", title: "Spartanburg, SC" },
  { value: "Spearfish, SD", title: "Spearfish, SD" },
  { value: "Spencer, IA", title: "Spencer, IA" },
  { value: "Spirit Lake, IA", title: "Spirit Lake, IA" },
  { value: "Spokane-Spokane Valley, WA", title: "Spokane-Spokane Valley, WA" },
  { value: "Springfield, IL", title: "Springfield, IL" },
  { value: "Springfield, MA", title: "Springfield, MA" },
  { value: "Springfield, MO", title: "Springfield, MO" },
  { value: "Springfield, OH", title: "Springfield, OH" },
  { value: "St. Cloud, MN", title: "St. Cloud, MN" },
  { value: "St. George, UT", title: "St. George, UT" },
  { value: "St. Joseph, MO-KS", title: "St. Joseph, MO-KS" },
  { value: "St. Louis, MO-IL", title: "St. Louis, MO-IL" },
  { value: "St. Marys, GA", title: "St. Marys, GA" },
  { value: "St. Marys, PA", title: "St. Marys, PA" },
  { value: "Starkville, MS", title: "Starkville, MS" },
  { value: "State College, PA", title: "State College, PA" },
  { value: "Statesboro, GA", title: "Statesboro, GA" },
  { value: "Staunton, VA", title: "Staunton, VA" },
  { value: "Steamboat Springs, CO", title: "Steamboat Springs, CO" },
  { value: "Stephenville, TX", title: "Stephenville, TX" },
  { value: "Sterling, CO", title: "Sterling, CO" },
  { value: "Sterling, IL", title: "Sterling, IL" },
  { value: "Stevens Point, WI", title: "Stevens Point, WI" },
  { value: "Stillwater, OK", title: "Stillwater, OK" },
  { value: "Stockton, CA", title: "Stockton, CA" },
  { value: "Storm Lake, IA", title: "Storm Lake, IA" },
  { value: "Sturgis, MI", title: "Sturgis, MI" },
  { value: "Sulphur Springs, TX", title: "Sulphur Springs, TX" },
  { value: "Summerville, GA", title: "Summerville, GA" },
  { value: "Sumter, SC", title: "Sumter, SC" },
  { value: "Sunbury, PA", title: "Sunbury, PA" },
  { value: "Susanville, CA", title: "Susanville, CA" },
  { value: "Sweetwater, TX", title: "Sweetwater, TX" },
  { value: "Syracuse, NY", title: "Syracuse, NY" },
  { value: "Tahlequah, OK", title: "Tahlequah, OK" },
  { value: "Talladega-Sylacauga, AL", title: "Talladega-Sylacauga, AL" },
  { value: "Tallahassee, FL", title: "Tallahassee, FL" },
  {
    value: "Tampa-St. Petersburg-Clearwater, FL",
    title: "Tampa-St. Petersburg-Clearwater, FL",
  },
  { value: "Taos, NM", title: "Taos, NM" },
  { value: "Taylorville, IL", title: "Taylorville, IL" },
  { value: "Terre Haute, IN", title: "Terre Haute, IN" },
  { value: "Texarkana, TX-AR", title: "Texarkana, TX-AR" },
  { value: "The Dalles, OR", title: "The Dalles, OR" },
  { value: "The Villages, FL", title: "The Villages, FL" },
  { value: "Thomaston, GA", title: "Thomaston, GA" },
  { value: "Thomasville, GA", title: "Thomasville, GA" },
  { value: "Tiffin, OH", title: "Tiffin, OH" },
  { value: "Tifton, GA", title: "Tifton, GA" },
  { value: "Toccoa, GA", title: "Toccoa, GA" },
  { value: "Toledo, OH", title: "Toledo, OH" },
  { value: "Topeka, KS", title: "Topeka, KS" },
  { value: "Torrington, CT", title: "Torrington, CT" },
  { value: "Traverse City, MI", title: "Traverse City, MI" },
  { value: "Trenton-Princeton, NJ", title: "Trenton-Princeton, NJ" },
  { value: "Troy, AL", title: "Troy, AL" },
  { value: "Truckee-Grass Valley, CA", title: "Truckee-Grass Valley, CA" },
  { value: "Tucson, AZ", title: "Tucson, AZ" },
  { value: "Tullahoma-Manchester, TN", title: "Tullahoma-Manchester, TN" },
  { value: "Tulsa, OK", title: "Tulsa, OK" },
  { value: "Tupelo, MS", title: "Tupelo, MS" },
  { value: "Tuscaloosa, AL", title: "Tuscaloosa, AL" },
  { value: "Twin Falls, ID", title: "Twin Falls, ID" },
  { value: "Tyler, TX", title: "Tyler, TX" },
  { value: "Ukiah, CA", title: "Ukiah, CA" },
  { value: "Union City, TN", title: "Union City, TN" },
  { value: "Union, SC", title: "Union, SC" },
  { value: "Urban Honolulu, HI", title: "Urban Honolulu, HI" },
  { value: "Urbana, OH", title: "Urbana, OH" },
  { value: "Utica-Rome, NY", title: "Utica-Rome, NY" },
  { value: "Uvalde, TX", title: "Uvalde, TX" },
  { value: "Valdosta, GA", title: "Valdosta, GA" },
  { value: "Vallejo, CA", title: "Vallejo, CA" },
  { value: "Van Wert, OH", title: "Van Wert, OH" },
  { value: "Vermillion, SD", title: "Vermillion, SD" },
  { value: "Vernal, UT", title: "Vernal, UT" },
  { value: "Vernon, TX", title: "Vernon, TX" },
  { value: "Vicksburg, MS", title: "Vicksburg, MS" },
  { value: "Victoria, TX", title: "Victoria, TX" },
  { value: "Vidalia, GA", title: "Vidalia, GA" },
  { value: "Vincennes, IN", title: "Vincennes, IN" },
  { value: "Vineland-Bridgeton, NJ", title: "Vineland-Bridgeton, NJ" },
  { value: "Vineyard Haven, MA", title: "Vineyard Haven, MA" },
  {
    value: "Virginia Beach-Norfolk-Newport News, VA-NC",
    title: "Virginia Beach-Norfolk-Newport News, VA-NC",
  },
  { value: "Visalia, CA", title: "Visalia, CA" },
  { value: "Wabash, IN", title: "Wabash, IN" },
  { value: "Waco, TX", title: "Waco, TX" },
  { value: "Wahpeton, ND-MN", title: "Wahpeton, ND-MN" },
  { value: "Walla Walla, WA", title: "Walla Walla, WA" },
  { value: "Wapakoneta, OH", title: "Wapakoneta, OH" },
  { value: "Warner Robins, GA", title: "Warner Robins, GA" },
  { value: "Warren, PA", title: "Warren, PA" },
  { value: "Warrensburg, MO", title: "Warrensburg, MO" },
  { value: "Warsaw, IN", title: "Warsaw, IN" },
  { value: "Washington Court House, OH", title: "Washington Court House, OH" },
  { value: "Washington, IN", title: "Washington, IN" },
  { value: "Washington, NC", title: "Washington, NC" },
  {
    value: "Washington-Arlington-Alexandria, DC-VA-MD-WV",
    title: "Washington-Arlington-Alexandria, DC-VA-MD-WV",
  },
  { value: "Waterloo-Cedar Falls, IA", title: "Waterloo-Cedar Falls, IA" },
  { value: "Watertown, SD", title: "Watertown, SD" },
  {
    value: "Watertown-Fort Atkinson, WI",
    title: "Watertown-Fort Atkinson, WI",
  },
  { value: "Watertown-Fort Drum, NY", title: "Watertown-Fort Drum, NY" },
  { value: "Wauchula, FL", title: "Wauchula, FL" },
  { value: "Wausau-Weston, WI", title: "Wausau-Weston, WI" },
  { value: "Waycross, GA", title: "Waycross, GA" },
  { value: "Weatherford, OK", title: "Weatherford, OK" },
  {
    value: "Weirton-Steubenville, WV-OH",
    title: "Weirton-Steubenville, WV-OH",
  },
  { value: "Wenatchee, WA", title: "Wenatchee, WA" },
  { value: "West Plains, MO", title: "West Plains, MO" },
  { value: "West Point, MS", title: "West Point, MS" },
  { value: "Wheeling, WV-OH", title: "Wheeling, WV-OH" },
  { value: "Whitewater, WI", title: "Whitewater, WI" },
  { value: "Wichita Falls, TX", title: "Wichita Falls, TX" },
  { value: "Wichita, KS", title: "Wichita, KS" },
  { value: "Williamsport, PA", title: "Williamsport, PA" },
  { value: "Williston, ND", title: "Williston, ND" },
  { value: "Willmar, MN", title: "Willmar, MN" },
  { value: "Wilmington, NC", title: "Wilmington, NC" },
  { value: "Wilmington, OH", title: "Wilmington, OH" },
  { value: "Wilson, NC", title: "Wilson, NC" },
  { value: "Winchester, VA-WV", title: "Winchester, VA-WV" },
  { value: "Winfield, KS", title: "Winfield, KS" },
  { value: "Winnemucca, NV", title: "Winnemucca, NV" },
  { value: "Winona, MN", title: "Winona, MN" },
  { value: "Winston-Salem, NC", title: "Winston-Salem, NC" },
  {
    value: "Wisconsin Rapids-Marshfield, WI",
    title: "Wisconsin Rapids-Marshfield, WI",
  },
  { value: "Woodward, OK", title: "Woodward, OK" },
  { value: "Wooster, OH", title: "Wooster, OH" },
  { value: "Worcester, MA-CT", title: "Worcester, MA-CT" },
  { value: "Worthington, MN", title: "Worthington, MN" },
  { value: "Yakima, WA", title: "Yakima, WA" },
  { value: "Yankton, SD", title: "Yankton, SD" },
  { value: "Yauco, PR", title: "Yauco, PR" },
  { value: "York-Hanover, PA", title: "York-Hanover, PA" },
  {
    value: "Youngstown-Warren-Boardman, OH-PA",
    title: "Youngstown-Warren-Boardman, OH-PA",
  },
  { value: "Yuba City, CA", title: "Yuba City, CA" },
  { value: "Yuma, AZ", title: "Yuma, AZ" },
  { value: "Zanesville, OH", title: "Zanesville, OH" },
  { value: "Zapata, TX", title: "Zapata, TX" },
];
