export const Naics = [
  {
    Construction: [
      "New Single-Family Housing Construction (except For-Sale Builders)",
      "Water and Sewer Line and Related Structures Construction",
      "Flooring Contractors",
      "All Other Specialty Trade Contractors",
      "Painting and Wall Covering Contractors",
      "Structural Steel and Precast Concrete Contractors",
      "Residential Remodelers",
      "Poured Concrete Foundation and Structure Contractors",
      "Other Foundation, Structure, and Building Exterior Contractors",
      "Commercial and Institutional Building Construction",
      "Framing Contractors",
      "Other Building Equipment Contractors",
      "Land Subdivision",
      "Roofing Contractors",
      "Siding Contractors",
      "Glass and Glazing Contractors",
      "New Housing For-Sale Builders",
      "Oil and Gas Pipeline and Related Structures Construction",
      "Masonry Contractors",
      "Other Building Finishing Contractors",
      "Highway, Street, and Bridge Construction",
      "Site Preparation Contractors",
      "New Multifamily Housing Construction (except For-Sale Builders)",
      "Drywall and Insulation Contractors",
      "Finish Carpentry Contractors",
      "Power and Communication Line and Related Structures Construction",
      "Plumbing, Heating, and Air-Conditioning Contractors",
      "Electrical Contractors and Other Wiring Installation Contractors",
      "Industrial Building Construction",
      "Tile and Terrazzo Contractors",
      "Other Heavy and Civil Engineering Construction",
    ],
  },
  {
    Manufacturing: [
      "Sawmills",
      "Other Millwork (including Flooring)",
      "Retail Bakeries",
      "Mayonnaise, Dressing, and Other Prepared Sauce Manufacturing",
      "Scale and Balance Manufacturing",
      "Primary Battery Manufacturing",
      "Frozen Fruit, Juice, and Vegetable Manufacturing",
      "Frozen Cakes, Pies, and Other Pastries Manufacturing",
      "Cookie and Cracker Manufacturing",
      "Adhesive Manufacturing",
      "Bare Printed Circuit Board Manufacturing",
      "Wineries",
      "Pesticide and Other Agricultural Chemical Manufacturing",
      "Mineral Wool Manufacturing",
      "Industrial and Commercial Fan and Blower and Air Purification Equipment Manufacturing",
      "Motor Home Manufacturing",
      "Reconstituted Wood Product Manufacturing",
      "Glass Product Manufacturing Made of Purchased Glass",
      "Elevator and Moving Stairway Manufacturing",
      "Artificial and Synthetic Fibers and Filaments Manufacturing",
      "Nitrogenous Fertilizer Manufacturing",
      "Custom Compounding of Purchased Resins",
      "Computer Terminal and Other Computer Peripheral Equipment Manufacturing",
      "Plumbing Fixture Fitting and Trim Manufacturing",
      "Heavy Duty Truck Manufacturing",
      "Petroleum Refineries",
      "Wood Kitchen Cabinet and Countertop Manufacturing",
      "Upholstered Household Furniture Manufacturing",
      "Petrochemical Manufacturing",
      "Metal Tank (Heavy Gauge) Manufacturing",
      "Special Die and Tool, Die Set, Jig, and Fixture Manufacturing",
      "Fluid Power Cylinder and Actuator Manufacturing",
      "Electronic Connector Manufacturing",
      "Engineered Wood Member (except Truss) Manufacturing",
      "Surface Active Agent Manufacturing",
      "Fluid Power Pump and Motor Manufacturing",
      "Beet Sugar Manufacturing",
      "Steel Foundries (except Investment)",
      "Industrial Truck, Tractor, Trailer, and Stacker Machinery Manufacturing",
      "Motor Vehicle Steering and Suspension Components (except Spring) Manufacturing",
      "Burial Casket Manufacturing",
      "Truss Manufacturing",
      "Nonchocolate Confectionery Manufacturing",
      "Sheet Metal Work Manufacturing",
      "Mining Machinery and Equipment Manufacturing",
      "Plastics Material and Resin Manufacturing",
      "Flat Glass Manufacturing",
      "Instrument Manufacturing for Measuring and Testing Electricity and Electrical Signals",
      "Electronic Computer Manufacturing",
      "Household Furniture (except Wood and Metal) Manufacturing",
      "Flavoring Syrup and Concentrate Manufacturing",
      "Plastics Packaging Film and Sheet (including Laminated) Manufacturing",
      "Alumina Refining and Primary Aluminum Production",
      "Metal Kitchen Cookware, Utensil, Cutlery, and Flatware (except Precious) Manufacturing",
      "Totalizing Fluid Meter and Counting Device Manufacturing",
      "Fluid Milk Manufacturing",
      "Synthetic Dye and Pigment Manufacturing",
      "Plastics Bag and Pouch Manufacturing",
      "Light Truck and Utility Vehicle Manufacturing",
      "Carpet and Rug Mills",
      "Motor Vehicle Electrical and Electronic Equipment Manufacturing",
      "Cut and Sew Apparel Contractors",
      "Secondary Smelting and Alloying of Aluminum",
      "All Other Miscellaneous General Purpose Machinery Manufacturing",
      "Fastener, Button, Needle, and Pin Manufacturing",
      "Biological Product (except Diagnostic) Manufacturing",
      "Polish and Other Sanitation Good Manufacturing",
      "Rubber Product Manufacturing for Mechanical Use",
      "Motor and Generator Manufacturing",
      "Fiber Optic Cable Manufacturing",
      "Specialty Canning",
      "Textile and Fabric Finishing Mills",
      "Other Measuring and Controlling Device Manufacturing",
      "Motor Vehicle Seating and Interior Trim Manufacturing",
      "Roasted Nuts and Peanut Butter Manufacturing",
      "Nonwoven Fabric Mills",
      "Plastics Plumbing Fixture Manufacturing",
      "Power Boiler and Heat Exchanger Manufacturing",
      "Other Metal Valve and Pipe Fitting Manufacturing",
      "Meat Processed from Carcasses",
      "Hosiery and Sock Mills",
      "Other Engine Equipment Manufacturing",
      "Other Motor Vehicle Parts Manufacturing",
      "Mattress Manufacturing",
      "Rice Milling",
      "Seafood Product Preparation and Packaging",
      "Commercial Screen Printing",
      "Optical Instrument and Lens Manufacturing",
      "Wood Office Furniture Manufacturing",
      "Distilleries",
      "Medicinal and Botanical Manufacturing",
      "Ammunition (except Small Arms) Manufacturing",
      "Industrial Mold Manufacturing",
      "Breweries",
      "Sanitary Paper Product Manufacturing",
      "Wet Corn Milling",
      "Women's Handbag and Purse Manufacturing",
      "Concrete Pipe Manufacturing",
      "Motor Vehicle Body Manufacturing",
      "Cut Stock, Resawing Lumber, and Planing",
      "Measuring, Dispensing, and Other Pumping Equipment Manufacturing",
      "Dental Equipment and Supplies Manufacturing",
      "Corrugated and Solid Fiber Box Manufacturing",
      "Aluminum Sheet, Plate, and Foil Manufacturing",
      "Electric Lamp Bulb and Part Manufacturing",
      "Explosives Manufacturing",
      "Automatic Environmental Control Manufacturing for Residential, Commercial, and Appliance Use",
      "Other Lighting Equipment Manufacturing",
      "Current-Carrying Wiring Device Manufacturing",
      "Other Guided Missile and Space Vehicle Parts and Auxiliary Equipment Manufacturing",
      "Sporting and Athletic Goods Manufacturing",
      "Bottled Water Manufacturing",
      "Tire Retreading",
      "Other Pressed and Blown Glass and Glassware Manufacturing",
      "Steel Investment Foundries",
      "Overhead Traveling Crane, Hoist, and Monorail System Manufacturing",
      "Pulp Mills",
      "Laminated Plastics Plate, Sheet (except Packaging), and Shape Manufacturing",
      "Copper Rolling, Drawing, Extruding, and Alloying",
      "Rolling Mill and Other Metalworking Machinery Manufacturing",
      "Capacitor, Resistor, Coil, Transformer, and Other Inductor Manufacturing",
      "Motor Vehicle Transmission and Power Train Parts Manufacturing",
      "Unlaminated Plastics Film and Sheet (except Packaging) Manufacturing",
      "Ball and Roller Bearing Manufacturing",
      "Confectionery Manufacturing from Purchased Chocolate",
      "Cyclic Crude, Intermediate, and Gum and Wood Chemical Manufacturing",
      "All Other Miscellaneous Fabricated Metal Product Manufacturing",
      "Storage Battery Manufacturing",
      "Broadwoven Fabric Mills",
      "Saw Blade and Handtool Manufacturing",
      "Other Communications Equipment Manufacturing",
      "Other Communication and Energy Wire Manufacturing",
      "Dental Laboratories",
      "Prefabricated Metal Building and Component Manufacturing",
      "Small Electrical Appliance Manufacturing",
      "Mens and Boys Cut and Sew Apparel Manufacturing",
      "Newsprint Mills",
      "Fluid Power Valve and Hose Fitting Manufacturing",
      "Small Arms, Ordnance, and Ordnance Accessories Manufacturing",
      "Folding Paperboard Box Manufacturing",
      "In-Vitro Diagnostic Substance Manufacturing",
      "Fabricated Pipe and Pipe Fitting Manufacturing",
      "Machine Tool Manufacturing",
      "Truck Trailer Manufacturing",
      "Surgical Appliance and Supplies Manufacturing",
      "Cane Sugar Manufacturing",
      "Fruit and Vegetable Canning",
      "Wood Preservation",
      "Cutting Tool and Machine Tool Accessory Manufacturing",
      "Spice and Extract Manufacturing",
      "Glass Container Manufacturing",
      "Noncurrent-Carrying Wiring Device Manufacturing",
      "Ice Manufacturing",
      "Books Printing",
      "Travel Trailer and Camper Manufacturing",
      "Fats and Oils Refining and Blending",
      "Broom, Brush, and Mop Manufacturing",
      "Support Activities for Printing",
      "Machine Shops",
      "Curtain and Linen Mills",
      "Heating Equipment (except Warm Air Furnaces) Manufacturing",
      "Wood Window and Door Manufacturing",
      "Fertilizer (Mixing Only) Manufacturing",
      "Iron and Steel Forging",
      "Other Electronic Component Manufacturing",
      "Other Basic Inorganic Chemical Manufacturing",
      "Concrete Block and Brick Manufacturing",
      "Paper Bag and Coated and Treated Paper Manufacturing",
      "Iron and Steel Pipe and Tube Manufacturing from Purchased Steel",
      "Military Armored Vehicle, Tank, and Tank Component Manufacturing",
      "Cement Manufacturing",
      "Other Concrete Product Manufacturing",
      "Farm Machinery and Equipment Manufacturing",
      "Air and Gas Compressor Manufacturing",
      "Automobile Manufacturing",
      "Sign Manufacturing",
      "Womens, Girls, and Infants Cut and Sew Apparel Manufacturing",
      "Custom Architectural Woodwork and Millwork Manufacturing",
      "Coffee and Tea Manufacturing",
      "Plate Work Manufacturing",
      "Bolt, Nut, Screw, Rivet, and Washer Manufacturing",
      "Stationery Product Manufacturing",
      "Speed Changer, Industrial High-Speed Drive, and Gear Manufacturing",
      "Welding and Soldering Equipment Manufacturing",
      "Polystyrene Foam Product Manufacturing",
      "Software and Other Prerecorded Compact Disc, Tape, and Record Reproducing",
      "Blind and Shade Manufacturing",
      "Malt Manufacturing",
      "Rope, Cordage, Twine, Tire Cord, and Tire Fabric Mills",
      "Oil and Gas Field Machinery and Equipment Manufacturing",
      "Major Household Appliance Manufacturing",
      "Toilet Preparation Manufacturing",
      "Cheese Manufacturing",
      "Clay Building Material and Refractories Manufacturing",
      "Radio and Television Broadcasting and Wireless Communications Equipment Manufacturing",
      "Carbon and Graphite Product Manufacturing",
      "Dog and Cat Food Manufacturing",
      "Industrial Process Furnace and Oven Manufacturing",
      "All Other Miscellaneous Wood Product Manufacturing",
      "All Other Converted Paper Product Manufacturing",
      "Aluminum Foundries (except Die-Casting)",
      "Analytical Laboratory Instrument Manufacturing",
      "Musical Instrument Manufacturing",
      "Chocolate and Confectionery Manufacturing from Cacao Beans",
      "Knit Fabric Mills",
      "Photographic Film, Paper, Plate, and Chemical Manufacturing",
      "Hardware Manufacturing",
      "Residential Electric Lighting Fixture Manufacturing",
      "Motor Vehicle Gasoline Engine and Engine Parts Manufacturing",
      "Other Commercial and Service Industry Machinery Manufacturing",
      "Semiconductor and Related Device Manufacturing",
      "Other Animal Food Manufacturing",
      "Metal Crown, Closure, and Other Metal Stamping (except Automotive)",
      "Motorcycle, Bicycle, and Parts Manufacturing",
      "Surgical and Medical Instrument Manufacturing",
      "Gasket, Packing, and Sealing Device Manufacturing",
      "All Other Rubber Product Manufacturing",
      "Power, Distribution, and Specialty Transformer Manufacturing",
      "All Other Miscellaneous Electrical Equipment and Component Manufacturing",
      "Doll, Toy, and Game Manufacturing",
      "Pottery, Ceramics, and Plumbing Fixture Manufacturing",
      "Metal Can Manufacturing",
      "Mechanical Power Transmission Equipment Manufacturing",
      "Printing Machinery and Equipment Manufacturing",
      "Conveyor and Conveying Equipment Manufacturing",
      "Lawn and Garden Tractor and Home Lawn and Garden Equipment Manufacturing",
      "Ready-Mix Concrete Manufacturing",
      "Tortilla Manufacturing",
      "Textile Bag and Canvas Mills",
      "Apparel Accessories and Other Apparel Manufacturing",
      "Asphalt Shingle and Coating Materials Manufacturing",
      "Jewelry and Silverware Manufacturing",
      "Dry, Condensed, and Evaporated Dairy Product Manufacturing",
      "Rolled Steel Shape Manufacturing",
      "Perishable Prepared Food Manufacturing",
      "Narrow Fabric Mills and Schiffli Machine Embroidery",
      "Footwear Manufacturing",
      "Secondary Smelting, Refining, and Alloying of Nonferrous Metal (except Copper and Aluminum)",
      "Nonferrous Forging",
      "Metal Household Furniture Manufacturing",
      "Other Aluminum Rolling, Drawing, and Extruding",
      "Metal Coating, Engraving (except Jewelry and Silverware), and Allied Services to Manufacturers",
      "Food Product Machinery Manufacturing",
      "Other Industrial Machinery Manufacturing",
      "Motor Vehicle Brake System Manufacturing",
      "Aircraft Manufacturing",
      "Boat Building",
      "Rendering and Meat Byproduct Processing",
      "Guided Missile and Space Vehicle Manufacturing",
      "Animal (except Poultry) Slaughtering",
      "Tobacco Manufacturing",
      "Packaging Machinery Manufacturing",
      "Instruments and Related Products Manufacturing for Measuring, Displaying, and Controlling Industrial Process Variables",
      "Other Aircraft Parts and Auxiliary Equipment Manufacturing",
      "Hardwood Veneer and Plywood Manufacturing",
      "Printing Ink Manufacturing",
      "Small Arms Ammunition Manufacturing",
      "All Other Leather Good and Allied Product Manufacturing",
      "Pharmaceutical Preparation Manufacturing",
      "Soap and Other Detergent Manufacturing",
      "All Other Miscellaneous Food Manufacturing",
      "Soft Drink Manufacturing",
      "Wood Container and Pallet Manufacturing",
      "Other Nonferrous Metal Foundries (except Die-Casting)",
      "Search, Detection, Navigation, Guidance, Aeronautical, and Nautical System and Instrument Manufacturing",
      "Office Supplies (except Paper) Manufacturing",
      "Soybean and Other Oilseed Processing",
      "Ethyl Alcohol Manufacturing",
      "Abrasive Product Manufacturing",
      "Photographic and Photocopying Equipment Manufacturing",
      "Audio and Video Equipment Manufacturing",
      "Paper (except Newsprint) Mills",
      "Ornamental and Architectural Metal Work Manufacturing",
      "Construction Machinery Manufacturing",
      "Motor Vehicle Metal Stamping",
      "Frozen Specialty Food Manufacturing",
      "Relay and Industrial Control Manufacturing",
      "Softwood Veneer and Plywood Manufacturing",
      "Air-Conditioning and Warm Air Heating Equipment and Commercial and Industrial Refrigeration Equipment Manufacturing",
      "Institutional Furniture Manufacturing",
      "Other Paperboard Container Manufacturing",
      "Asphalt Paving Mixture and Block Manufacturing",
      "Industrial Valve Manufacturing",
      "Flour Milling",
      "Power-Driven Handtool Manufacturing",
      "Other Apparel Knitting Mills",
      "Fiber, Yarn, and Thread Mills",
      "Tire Manufacturing (except Retreading)",
      "Custom Roll Forming",
      "Semiconductor Machinery Manufacturing",
      "Commercial, Industrial, and Institutional Electric Lighting Fixture Manufacturing",
      "Dried and Dehydrated Food Manufacturing",
      "Other Snack Food Manufacturing",
      "All Other Miscellaneous Chemical Product and Preparation Manufacturing",
      "Ground or Treated Mineral and Earth Manufacturing",
      "Iron Foundries",
      "Nonferrous Metal Die-Casting Foundries",
      "Turbine and Turbine Generator Set Units Manufacturing",
      "Phosphatic Fertilizer Manufacturing",
      "Telephone Apparatus Manufacturing",
      "Blank Magnetic and Optical Recording Media Manufacturing",
      "Nonferrous Metal (except Copper and Aluminum) Rolling, Drawing, and Extruding",
      "Other Metal Container Manufacturing",
      "Other Fabricated Wire Product Manufacturing",
      "All Other Miscellaneous Manufacturing",
      "All Other Petroleum and Coal Products Manufacturing",
      "Urethane and Other Foam Product (except Polystyrene) Manufacturing",
      "Spring Manufacturing",
      "Creamery Butter Manufacturing",
      "Manufactured Home (Mobile Home) Manufacturing",
      "Guided Missile and Space Vehicle Propulsion Unit and Propulsion Unit Parts Manufacturing",
      "Nonupholstered Wood Household Furniture Manufacturing",
      "Office Furniture (except Wood) Manufacturing",
      "Lime Manufacturing",
      "Paint and Coating Manufacturing",
      "Plastics Pipe and Pipe Fitting Manufacturing",
      "Metal Heat Treating",
      "Showcase, Partition, Shelving, and Locker Manufacturing",
      "Dry Pasta, Dough, and Flour Mixes Manufacturing from Purchased Flour",
      "Petroleum Lubricating Oil and Grease Manufacturing",
      "Synthetic Rubber Manufacturing",
      "Irradiation Apparatus Manufacturing",
      "Gypsum Product Manufacturing",
      "All Other Miscellaneous Nonmetallic Mineral Product Manufacturing",
      "Printed Circuit Assembly (Electronic Assembly) Manufacturing",
      "Electromedical and Electrotherapeutic Apparatus Manufacturing",
      "Ship Building and Repairing",
      "Leather and Hide Tanning and Finishing",
      "Precision Turned Product Manufacturing",
      "Ophthalmic Goods Manufacturing",
      "Other Cut and Sew Apparel Manufacturing",
      "Electroplating, Plating, Polishing, Anodizing, and Coloring",
      "Prefabricated Wood Building Manufacturing",
      "Industrial Gas Manufacturing",
      "Nonferrous Metal (except Aluminum) Smelting and Refining",
      "Computer Storage Device Manufacturing",
      "Paperboard Mills",
      "Plastics Bottle Manufacturing",
      "Rubber and Plastics Hoses and Belting Manufacturing",
      "Sawmill, Woodworking, and Paper Machinery Manufacturing",
      "All Other Transportation Equipment Manufacturing",
      "Poultry Processing",
      "Unlaminated Plastics Profile Shape Manufacturing",
      "Iron and Steel Mills and Ferroalloy Manufacturing",
      "Ice Cream and Frozen Dessert Manufacturing",
      "Cut Stone and Stone Product Manufacturing",
      "Powder Metallurgy Part Manufacturing",
      "Switchgear and Switchboard Apparatus Manufacturing",
      "Breakfast Cereal Manufacturing",
      "Fabric Coating Mills",
      "Steel Wire Drawing",
      "Metal Window and Door Manufacturing",
      "Commercial Bakeries",
      "Commercial Printing (except Screen and Books)",
      "All Other Basic Organic Chemical Manufacturing",
      "All Other Plastics Product Manufacturing",
      "Fabricated Structural Metal Manufacturing",
      "All Other Miscellaneous Textile Product Mills",
      "Aircraft Engine and Engine Parts Manufacturing",
      "Railroad Rolling Stock Manufacturing",
    ],
  },
  {
    "Wholesale Trade": [
      "Grain and Field Bean Merchant Wholesalers",
      "Petroleum Bulk Stations and Terminals",
      "Flower, Nursery Stock, and Florists' Supplies Merchant Wholesalers",
      "Women's, Children's, and Infants' Clothing and Accessories Merchant Wholesalers",
      "Fish and Seafood Merchant Wholesalers",
      "Home Furnishing Merchant Wholesalers",
      "Other Commercial Equipment Merchant Wholesalers",
      "Drugs and Druggists' Sundries Merchant Wholesalers",
      "General Line Grocery Merchant Wholesalers",
      "Industrial and Personal Service Paper Merchant Wholesalers",
      "Other Professional Equipment and Supplies Merchant Wholesalers",
      "Other Farm Product Raw Material Merchant Wholesalers",
      "Stationery and Office Supplies Merchant Wholesalers",
      "Medical, Dental, and Hospital Equipment and Supplies Merchant Wholesalers",
      "Farm and Garden Machinery and Equipment Merchant Wholesalers",
      "Service Establishment Equipment and Supplies Merchant Wholesalers",
      "Tire and Tube Merchant Wholesalers",
      "Transportation Equipment and Supplies (except Motor Vehicle) Merchant Wholesalers",
      "Beer and Ale Merchant Wholesalers",
      "Wholesale Trade Agents and Brokers",
      "Confectionery Merchant Wholesalers",
      "Refrigeration Equipment and Supplies Merchant Wholesalers",
      "Ophthalmic Goods Merchant Wholesalers",
      "Business to Business Electronic Markets",
      "Plastics Materials and Basic Forms and Shapes Merchant Wholesalers",
      "Other Chemical and Allied Products Merchant Wholesalers",
      "Furniture Merchant Wholesalers",
      "Computer and Computer Peripheral Equipment and Software Merchant Wholesalers",
      "Jewelry, Watch, Precious Stone, and Precious Metal Merchant Wholesalers",
      "Household Appliances, Electric Housewares, and Consumer Electronics Merchant Wholesalers",
      "Brick, Stone, and Related Construction Material Merchant Wholesalers",
      "Meat and Meat Product Merchant Wholesalers",
      "Poultry and Poultry Product Merchant Wholesalers",
      "Other Grocery and Related Products Merchant Wholesalers",
      "Wine and Distilled Alcoholic Beverage Merchant Wholesalers",
      "Paint, Varnish, and Supplies Merchant Wholesalers",
      "Construction and Mining (except Oil Well) Machinery and Equipment Merchant Wholesalers",
      "Warm Air Heating and Air-Conditioning Equipment and Supplies Merchant Wholesalers",
      "Printing and Writing Paper Merchant Wholesalers",
      "Plumbing and Heating Equipment and Supplies (Hydronics) Merchant Wholesalers",
      "Toy and Hobby Goods and Supplies Merchant Wholesalers",
      "Fresh Fruit and Vegetable Merchant Wholesalers",
      "Office Equipment Merchant Wholesalers",
      "Recyclable Material Merchant Wholesalers",
      "Book, Periodical, and Newspaper Merchant Wholesalers",
      "Petroleum and Petroleum Products Merchant Wholesalers (except Bulk Stations and Terminals)",
      "Lumber, Plywood, Millwork, and Wood Panel Merchant Wholesalers",
      "Men's and Boys' Clothing and Furnishings Merchant Wholesalers",
      "Dairy Product (except Dried or Canned) Merchant Wholesalers",
      "Photographic Equipment and Supplies Merchant Wholesalers",
      "Other Electronic Parts and Equipment Merchant Wholesalers",
      "Other Miscellaneous Nondurable Goods Merchant Wholesalers",
      "Metal Service Centers and Other Metal Merchant Wholesalers",
      "Roofing, Siding, and Insulation Material Merchant Wholesalers",
      "Hardware Merchant Wholesalers",
      "Farm Supplies Merchant Wholesalers",
      "Tobacco and Tobacco Product Merchant Wholesalers",
      "Other Construction Material Merchant Wholesalers",
      "Electrical Apparatus and Equipment, Wiring Supplies, and Related Equipment Merchant Wholesalers",
      "Motor Vehicle Parts (Used) Merchant Wholesalers",
      "Livestock Merchant Wholesalers",
      "Other Miscellaneous Durable Goods Merchant Wholesalers",
      "Motor Vehicle Supplies and New Parts Merchant Wholesalers",
      "Coal and Other Mineral and Ore Merchant Wholesalers",
      "Industrial Supplies Merchant Wholesalers",
      "Automobile and Other Motor Vehicle Merchant Wholesalers",
      "Packaged Frozen Food Merchant Wholesalers",
      "Industrial Machinery and Equipment Merchant Wholesalers",
      "Sporting and Recreational Goods and Supplies Merchant Wholesalers",
      "Piece Goods, Notions, and Other Dry Goods Merchant Wholesalers",
      "Footwear Merchant Wholesalers",
    ],
  },
  {
    "Administrative and Support and Waste Management and Remediation Services":
      [
        "Materials Recovery Facilities",
        "Convention and Trade Show Organizers",
        "Remediation Services",
        "Security Guards and Patrol Services",
        "All Other Support Services",
        "Telemarketing Bureaus and Other Contact Centers",
        "Armored Car Services",
        "Solid Waste Combustors and Incinerators",
        "Office Administrative Services",
        "Carpet and Upholstery Cleaning Services",
        "Executive Search Services",
        "Professional Employer Organizations",
        "Repossession Services",
        "Private Mail Centers",
        "Hazardous Waste Collection",
        "Tour Operators",
        "Solid Waste Collection",
        "Septic Tank and Related Services",
        "Document Preparation Services",
        "Janitorial Services",
        "Employment Placement Agencies",
        "Investigation Services",
        "Locksmiths",
        "Hazardous Waste Treatment and Disposal",
        "All Other Business Support Services",
        "Facilities Support Services",
        "Landscaping Services",
        "All Other Travel Arrangement and Reservation Services",
        "Credit Bureaus",
        "Other Nonhazardous Waste Treatment and Disposal",
        "Security Systems Services (except Locksmiths)",
        "Exterminating and Pest Control Services",
        "Collection Agencies",
        "Travel Agencies",
        "All Other Miscellaneous Waste Management Services",
        "Other Waste Collection",
        "Solid Waste Landfill",
        "Telephone Answering Services",
        "Temporary Help Services",
        "Other Business Service Centers (including Copy Shops)",
        "Packaging and Labeling Services",
        "Other Services to Buildings and Dwellings",
        "Convention and Visitors Bureaus",
        "Court Reporting and Stenotype Services",
      ],
  },
  {
    "Educational Services": [
      "Fine Arts Schools",
      "Educational Support Services",
      "All Other Miscellaneous Schools and Instruction",
      "Computer Training",
      "Flight Training",
      "Other Technical and Trade Schools",
      "Exam Preparation and Tutoring",
      "Cosmetology and Barber Schools",
      "Elementary and Secondary Schools",
      "Junior Colleges",
      "Sports and Recreation Instruction",
      "Business and Secretarial Schools",
      "Language Schools",
      "Automobile Driving Schools",
      "Colleges, Universities, and Professional Schools",
      "Professional and Management Development Training",
      "Apprenticeship Training",
    ],
  },
  {
    "Other Services (except Public Administration)": [
      "Automotive Oil Change and Lubrication Shops",
      "Coin-Operated Laundries and Drycleaners",
      "Professional Organizations",
      "Commercial and Industrial Machinery and Equipment (except Automotive and Electronic) Repair and Maintenance",
      "General Automotive Repair",
      "Communication Equipment Repair and Maintenance",
      "Photofinishing Laboratories (except One-Hour)",
      "Other Social Advocacy Organizations",
      "Business Associations",
      "Other Automotive Mechanical and Electrical Repair and Maintenance",
      "Labor Unions and Similar Labor Organizations",
      "Automotive Transmission Repair",
      "Automotive Glass Replacement Shops",
      "All Other Automotive Repair and Maintenance",
      "Funeral Homes and Funeral Services",
      "Consumer Electronics Repair and Maintenance",
      "Automotive Body, Paint, and Interior Repair and Maintenance",
      "Home and Garden Equipment Repair and Maintenance",
      "Linen Supply",
      "Industrial Launderers",
      "Car Washes",
      "All Other Personal Services",
      "Other Grantmaking and Giving Services",
      "Other Personal and Household Goods Repair and Maintenance",
      "Political Organizations",
      "Reupholstery and Furniture Repair",
      "Parking Lots and Garages",
      "Civic and Social Organizations",
      "Footwear and Leather Goods Repair",
      "Environment, Conservation and Wildlife Organizations",
      "Religious Organizations",
      "Automotive Exhaust System Repair",
      "Other Personal Care Services",
      "Appliance Repair and Maintenance",
      "Other Electronic and Precision Equipment Repair and Maintenance",
      "Nail Salons",
      "Voluntary Health Organizations",
      "Other Similar Organizations (except Business, Professional, Labor, and Political Organizations)",
      "Diet and Weight Reducing Centers",
      "Human Rights Organizations",
      "Cemeteries and Crematories",
      "Barber Shops",
      "Drycleaning and Laundry Services (except Coin-Operated)",
      "Grantmaking Foundations",
      "Pet Care (except Veterinary) Services",
      "Computer and Office Machine Repair and Maintenance",
      "Beauty Salons",
      "One-Hour Photofinishing",
    ],
  },
  {
    "Mining, Quarrying, and Oil and Gas Extraction": [
      "Bituminous Coal and Lignite Surface Mining",
      "Construction Sand and Gravel Mining",
      "Drilling Oil and Gas Wells",
      "Support Activities for Nonmetallic Minerals (except Fuels) Mining",
      "Uranium-Radium-Vanadium Ore Mining",
      "Natural Gas Extraction",
      "Crushed and Broken Limestone Mining and Quarrying",
      "Support Activities for Metal Mining",
      "Silver Ore Mining",
      "Phosphate Rock Mining",
      "Support Activities for Coal Mining",
      "Support Activities for Oil and Gas Operations",
      "Copper, Nickel, Lead, and Zinc Mining",
      "Dimension Stone Mining and Quarrying",
      "Anthracite Mining",
      "Kaolin and Ball Clay Mining",
      "All Other Nonmetallic Mineral Mining",
      "Bituminous Coal Underground Mining",
      "All Other Metal Ore Mining",
      "Potash, Soda, and Borate Mineral Mining",
      "Gold Ore Mining",
      "Clay and Ceramic and Refractory Minerals Mining",
      "Other Chemical and Fertilizer Mineral Mining",
      "Crude Petroleum Extraction",
      "Iron Ore Mining",
      "Crushed and Broken Granite Mining and Quarrying",
      "Other Crushed and Broken Stone Mining and Quarrying",
      "Industrial Sand Mining",
    ],
  },
  {
    "Professional, Scientific, and Technical Services": [
      "Architectural Services",
      "Human Resources Consulting Services",
      "Geophysical Surveying and Mapping Services",
      "Other Management Consulting Services",
      "Outdoor Advertising",
      "Translation and Interpretation Services",
      "Veterinary Services",
      "Drafting Services",
      "Public Relations Agencies",
      "Offices of Notaries",
      "Tax Preparation Services",
      "Computer Facilities Management Services",
      "Research and Development in Nanotechnology",
      "Advertising Material Distribution Services",
      "Research and Development in the Physical, Engineering, and Life Sciences (except Nanotechnology and Biotechnology)",
      "Building Inspection Services",
      "Other Services Related to Advertising",
      "Payroll Services",
      "Direct Mail Advertising",
      "Title Abstract and Settlement Offices",
      "Interior Design Services",
      "All Other Professional, Scientific, and Technical Services",
      "Surveying and Mapping (except Geophysical) Services",
      "Administrative Management and General Management Consulting Services",
      "Research and Development in the Social Sciences and Humanities",
      "Landscape Architectural Services",
      "Engineering Services",
      "Commercial Photography",
      "Offices of Lawyers",
      "Testing Laboratories",
      "All Other Legal Services",
      "Media Buying Agencies",
      "Marketing Research and Public Opinion Polling",
      "Other Computer Related Services",
      "Other Accounting Services",
      "Computer Systems Design Services",
      "Advertising Agencies",
      "Other Scientific and Technical Consulting Services",
      "Graphic Design Services",
      "Industrial Design Services",
      "Other Specialized Design Services",
      "Environmental Consulting Services",
      "Offices of Certified Public Accountants",
      "Marketing Consulting Services",
      "Process, Physical Distribution, and Logistics Consulting Services",
      "Media Representatives",
      "Custom Computer Programming Services",
      "Research and Development in Biotechnology (except Nanobiotechnology)",
      "Photography Studios, Portrait",
    ],
  },
  {
    Utilities: [
      "Wind Electric Power Generation",
      "Electric Power Distribution",
      "Geothermal Electric Power Generation",
      "Natural Gas Distribution",
      "Steam and Air-Conditioning Supply",
      "Sewage Treatment Facilities",
      "Fossil Fuel Electric Power Generation",
      "Electric Bulk Power Transmission and Control",
      "Hydroelectric Power Generation",
      "Nuclear Electric Power Generation",
      "Water Supply and Irrigation Systems",
      "Other Electric Power Generation",
      "Biomass Electric Power Generation",
      "Solar Electric Power Generation",
    ],
  },
  {
    "Finance and Insurance": [
      "Real Estate Credit",
      "Financial Transactions Processing, Reserve, and Clearinghouse Activities",
      "Savings Institutions",
      "Securities Brokerage",
      "Direct Title Insurance Carriers",
      "Other Depository Credit Intermediation",
      "Secondary Market Financing",
      "Direct Life Insurance Carriers",
      "Sales Financing",
      "Trust, Fiduciary, and Custody Activities",
      "Portfolio Management",
      "Other Activities Related to Credit Intermediation",
      "Miscellaneous Financial Investment Activities",
      "Commercial Banking",
      "Investment Advice",
      "International Trade Financing",
      "Direct Property and Casualty Insurance Carriers",
      "Reinsurance Carriers",
      "Commodity Contracts Brokerage",
      "All Other Nondepository Credit Intermediation",
      "Credit Card Issuing",
      "Claims Adjusting",
      "Other Financial Vehicles",
      "Other Direct Insurance (except Life, Health, and Medical) Carriers",
      "Insurance Agencies and Brokerages",
      "All Other Insurance Related Activities",
      "Other Insurance Funds",
      "Direct Health and Medical Insurance Carriers",
      "Investment Banking and Securities Dealing",
      "Trusts, Estates, and Agency Accounts",
      "Miscellaneous Intermediation",
      "Securities and Commodity Exchanges",
      "Health and Welfare Funds",
      "Credit Unions",
      "Mortgage and Nonmortgage Loan Brokers",
      "Pension Funds",
      "Third Party Administration of Insurance and Pension Funds",
      "Commodity Contracts Dealing",
      "Open-End Investment Funds",
      "Consumer Lending",
    ],
  },
  {
    "Health Care and Social Assistance": [
      "Offices of Physicians, Mental Health Specialists",
      "Temporary Shelters",
      "Offices of Chiropractors",
      "Nursing Care Facilities (Skilled Nursing Facilities)",
      "Family Planning Centers",
      "Medical Laboratories",
      "Psychiatric and Substance Abuse Hospitals",
      "Offices of Physical, Occupational and Speech Therapists, and Audiologists",
      "Diagnostic Imaging Centers",
      "Home Health Care Services",
      "All Other Outpatient Care Centers",
      "Community Food Services",
      "Other Individual and Family Services",
      "HMO Medical Centers",
      "All Other Miscellaneous Ambulatory Health Care Services",
      "Offices of Optometrists",
      "Offices of Podiatrists",
      "Offices of Dentists",
      "Offices of Mental Health Practitioners (except Physicians)",
      "Offices of All Other Miscellaneous Health Practitioners",
      "Child and Youth Services",
      "Child Day Care Services",
      "Other Community Housing Services",
      "Blood and Organ Banks",
      "Residential Intellectual and Developmental Disability Facilities",
      "Residential Mental Health and Substance Abuse Facilities",
      "Other Residential Care Facilities",
      "Kidney Dialysis Centers",
      "Offices of Physicians (except Mental Health Specialists)",
      "Vocational Rehabilitation Services",
      "Continuing Care Retirement Communities",
      "Freestanding Ambulatory Surgical and Emergency Centers",
      "Ambulance Services",
      "Assisted Living Facilities for the Elderly",
      "Services for the Elderly and Persons with Disabilities",
      "General Medical and Surgical Hospitals",
      "Specialty (except Psychiatric and Substance Abuse) Hospitals",
      "Emergency and Other Relief Services",
      "Outpatient Mental Health and Substance Abuse Centers",
    ],
  },
  {
    "Retail Trade": [
      "Fuel Dealers",
      "Sporting Goods Stores",
      "Automotive Parts and Accessories Stores",
      "Family Clothing Stores",
      "News Dealers and Newsstands",
      "Fruit and Vegetable Markets",
      "Home Centers",
      "Electronics Stores",
      "Men's Clothing Stores",
      "All Other Specialty Food Stores",
      "Convenience Stores",
      "New Car Dealers",
      "Book Stores",
      "Outdoor Power Equipment Stores",
      "All Other Miscellaneous Store Retailers (except Tobacco Stores)",
      "Women's Clothing Stores",
      "Florists",
      "Household Appliance Stores",
      "Meat Markets",
      "Fish and Seafood Markets",
      "Optical Goods Stores",
      "All Other Health and Personal Care Stores",
      "Supermarkets and Other Grocery (except Convenience) Stores",
      "Furniture Stores",
      "Office Supplies and Stationery Stores",
      "Used Car Dealers",
      "Nursery, Garden Center, and Farm Supply Stores",
      "Hardware Stores",
      "Sewing, Needlework, and Piece Goods Stores",
      "All Other Home Furnishings Stores",
      "Beer, Wine, and Liquor Stores",
      "Paint and Wallpaper Stores",
      "Window Treatment Stores",
      "Department Stores",
      "Vending Machine Operators",
      "Recreational Vehicle Dealers",
      "Tobacco Stores",
      "Boat Dealers",
      "Baked Goods Stores",
      "Musical Instrument and Supplies Stores",
      "Other Building Material Dealers",
      "All Other General Merchandise Stores",
      "Hobby, Toy, and Game Stores",
      "Motorcycle, ATV, and All Other Motor Vehicle Dealers",
      "Other Clothing Stores",
      "Floor Covering Stores",
      "Cosmetics, Beauty Supplies, and Perfume Stores",
      "Children's and Infants' Clothing Stores",
      "Other Gasoline Stations",
      "Gift, Novelty, and Souvenir Stores",
      "Warehouse Clubs and Supercenters",
      "Luggage and Leather Goods Stores",
      "Used Merchandise Stores",
      "Jewelry Stores",
      "Art Dealers",
      "Confectionery and Nut Stores",
      "Food (Health) Supplement Stores",
      "Tire Dealers",
      "Electronic Shopping and Mail-Order Houses",
      "Manufactured (Mobile) Home Dealers",
      "Gasoline Stations with Convenience Stores",
      "Shoe Stores",
      "Pharmacies and Drug Stores",
      "Clothing Accessories Stores",
      "Pet and Pet Supplies Stores",
      "Other Direct Selling Establishments",
    ],
  },
  {
    Information: [
      "Satellite Telecommunications",
      "Music Publishers",
      "All Other Telecommunications",
      "Motion Picture Theaters (except Drive-Ins)",
      "Telecommunications Resellers",
      "Other Sound Recording Industries",
      "Other Motion Picture and Video Industries",
      "Newspaper Publishers",
      "Television Broadcasting",
      "Drive-In Motion Picture Theaters",
      "Internet Publishing and Broadcasting and Web Search Portals",
      "Radio Stations",
      "Motion Picture and Video Production",
      "Data Processing, Hosting, and Related Services",
      "Wireless Telecommunications Carriers (except Satellite)",
      "Sound Recording Studios",
      "All Other Information Services",
      "Wired Telecommunications Carriers",
      "All Other Publishers",
      "Record Production and Distribution",
      "Cable and Other Subscription Programming",
      "Motion Picture and Video Distribution",
      "Radio Networks",
      "Directory and Mailing List Publishers",
      "Greeting Card Publishers",
      "Software Publishers",
      "Teleproduction and Other Postproduction Services",
      "Libraries and Archives",
      "Periodical Publishers",
      "Book Publishers",
      "News Syndicates",
    ],
  },
  {
    "Arts, Entertainment, and Recreation": [
      "Marinas",
      "Dance Companies",
      "Zoos and Botanical Gardens",
      "All Other Amusement and Recreation Industries",
      "Amusement Arcades",
      "Promoters of Performing Arts, Sports, and Similar Events without Facilities",
      "Musical Groups and Artists",
      "Independent Artists, Writers, and Performers",
      "Other Gambling Industries",
      "Historical Sites",
      "Museums",
      "Agents and Managers for Artists, Athletes, Entertainers, and Other Public Figures",
      "Skiing Facilities",
      "Fitness and Recreational Sports Centers",
      "Racetracks",
      "Golf Courses and Country Clubs",
      "Other Performing Arts Companies",
      "Theater Companies and Dinner Theaters",
      "Casinos (except Casino Hotels)",
      "Nature Parks and Other Similar Institutions",
      "Sports Teams and Clubs",
      "Promoters of Performing Arts, Sports, and Similar Events with Facilities",
      "Amusement and Theme Parks",
      "Bowling Centers",
      "Other Spectator Sports",
    ],
  },
  {
    "Agriculture, Forestry, Fishing and Hunting": [
      "Oilseed (except Soybean) Farming",
      "Cattle Feedlots",
      "Broilers and Other Meat Type Chicken Production",
      "Goat Farming",
      "Dry Pea and Bean Farming",
      "Nursery and Tree Production",
      "Postharvest Crop Activities (except Cotton Ginning)",
      "Farm Labor Contractors and Crew Leaders",
      "Citrus (except Orange) Groves",
      "Orange Groves",
      "Other Noncitrus Fruit Farming",
      "Timber Tract Operations",
      "Other Food Crops Grown Under Cover",
      "Dual-Purpose Cattle Ranching and Farming",
      "Wheat Farming",
      "Mushroom Production",
      "Rice Farming",
      "Hay Farming",
      "Tree Nut Farming",
      "Other Poultry Production",
      "All Other Grain Farming",
      "Poultry Hatcheries",
      "Support Activities for Forestry",
      "Cotton Farming",
      "Grape Vineyards",
      "Corn Farming",
      "Apple Orchards",
      "Floriculture Production",
      "Shellfish Fishing",
      "Farm Management Services",
      "Tobacco Farming",
      "Other Marine Fishing",
      "Soil Preparation, Planting, and Cultivating",
      "Potato Farming",
      "Sheep Farming",
      "Finfish Fishing",
      "Hunting and Trapping",
      "Fur-Bearing Animal and Rabbit Production",
      "Shellfish Farming",
      "Support Activities for Animal Production",
      "Oilseed and Grain Combination Farming",
      "Turkey Production",
      "Chicken Egg Production",
      "Hog and Pig Farming",
      "Apiculture",
      "Peanut Farming",
      "Horses and Other Equine Production",
      "Berry (except Strawberry) Farming",
      "Beef Cattle Ranching and Farming",
      "Other Aquaculture",
      "All Other Miscellaneous Crop Farming",
      "Soybean Farming",
      "Finfish Farming and Fish Hatcheries",
      "Sugar Beet Farming",
      "Logging",
      "Other Vegetable (except Potato) and Melon Farming",
      "Cotton Ginning",
      "Dairy Cattle and Milk Production",
      "Strawberry Farming",
      "Fruit and Tree Nut Combination Farming",
      "All Other Animal Production",
      "Forest Nurseries and Gathering of Forest Products",
      "Sugarcane Farming",
      "Crop Harvesting, Primarily by Machine",
    ],
  },
  {
    "Transportation and Warehousing": [
      "Navigational Services to Shipping",
      "General Freight Trucking, Long-Distance, Less Than Truckload",
      "Scenic and Sightseeing Transportation, Water",
      "Scheduled Passenger Air Transportation",
      "Farm Product Warehousing and Storage",
      "Pipeline Transportation of Crude Oil",
      "Scenic and Sightseeing Transportation, Other",
      "Deep Sea Freight Transportation",
      "Other Support Activities for Water Transportation",
      "Commuter Rail Systems",
      "Special Needs Transportation",
      "All Other Pipeline Transportation",
      "Inland Water Freight Transportation",
      "Deep Sea Passenger Transportation",
      "General Warehousing and Storage",
      "General Freight Trucking, Local",
      "Interurban and Rural Bus Transportation",
      "Other Nonscheduled Air Transportation",
      "Refrigerated Warehousing and Storage",
      "Other Support Activities for Air Transportation",
      "Port and Harbor Operations",
      "Used Household and Office Goods Moving",
      "All Other Transit and Ground Passenger Transportation",
      "Taxi Service",
      "Local Messengers and Local Delivery",
      "Nonscheduled Chartered Freight Air Transportation",
      "Charter Bus Industry",
      "Couriers and Express Delivery Services",
      "Short Line Railroads",
      "Inland Water Passenger Transportation",
      "Specialized Freight (except Used Goods) Trucking, Local",
      "Marine Cargo Handling",
      "All Other Support Activities for Transportation",
      "Support Activities for Rail Transportation",
      "Nonscheduled Chartered Passenger Air Transportation",
      "Coastal and Great Lakes Freight Transportation",
      "Packing and Crating",
      "Mixed Mode Transit Systems",
      "School and Employee Bus Transportation",
      "Specialized Freight (except Used Goods) Trucking, Long-Distance",
      "Scheduled Freight Air Transportation",
      "General Freight Trucking, Long-Distance, Truckload",
      "Bus and Other Motor Vehicle Transit Systems",
      "Line-Haul Railroads",
      "Postal Service",
      "Freight Transportation Arrangement",
      "Other Warehousing and Storage",
      "Limousine Service",
      "Other Urban Transit Systems",
      "Other Airport Operations",
      "Air Traffic Control",
      "Pipeline Transportation of Natural Gas",
      "Coastal and Great Lakes Passenger Transportation",
      "Motor Vehicle Towing",
      "Pipeline Transportation of Refined Petroleum Products",
      "Other Support Activities for Road Transportation",
      "Scenic and Sightseeing Transportation, Land",
    ],
  },
  {
    "Public Administration": [
      "Administration of Human Resource Programs (except Education, Public Health, and Veterans' Affairs Programs)",
      "Administration of Education Programs",
      "Regulation, Licensing, and Inspection of Miscellaneous Commercial Sectors",
      "Administration of General Economic Programs",
      "Administration of Housing Programs",
      "Regulation and Administration of Transportation Programs",
      "Legal Counsel and Prosecution",
      "Other General Government Support",
      "International Affairs",
      "Other Justice, Public Order, and Safety Activities",
      "Administration of Veterans' Affairs",
      "Courts",
      "Administration of Conservation Programs",
      "Administration of Air and Water Resource and Solid Waste Management Programs",
      "Parole Offices and Probation Offices",
      "American Indian and Alaska Native Tribal Governments",
      "Regulation and Administration of Communications, Electric, Gas, and Other Utilities",
      "Correctional Institutions",
      "Regulation of Agricultural Marketing and Commodities",
      "National Security",
      "Public Finance Activities",
      "Executive Offices",
      "Administration of Urban Planning and Community and Rural Development",
      "Police Protection",
      "Administration of Public Health Programs",
      "Space Research and Technology",
      "Legislative Bodies",
      "Executive and Legislative Offices, Combined",
      "Fire Protection",
    ],
  },
  {
    "Accommodation and Food Services": [
      "Limited-Service Restaurants",
      "Hotels (except Casino Hotels) and Motels",
      "All Other Traveler Accommodation",
      "RV (Recreational Vehicle) Parks and Campgrounds",
      "Recreational and Vacation Camps (except Campgrounds)",
      "Bed-and-Breakfast Inns",
      "Drinking Places (Alcoholic Beverages)",
      "Full-Service Restaurants",
      "Caterers",
      "Snack and Nonalcoholic Beverage Bars",
      "Mobile Food Services",
      "Food Service Contractors",
      "Casino Hotels",
      "Rooming and Boarding Houses",
      "Cafeterias, Grill Buffets, and Buffets",
    ],
  },
  {
    "Management of Companies and Enterprises": [
      "Corporate, Subsidiary, and Regional Managing Offices",
      "Offices of Other Holding Companies",
      "Offices of Bank Holding Companies",
    ],
  },
  {
    "Real Estate and Rental and Leasing": [
      "Video Tape and Disc Rental",
      "Lessors of Nonfinancial Intangible Assets (except Copyrighted Works)",
      "Nonresidential Property Managers",
      "Lessors of Nonresidential Buildings (except Miniwarehouses)",
      "Lessors of Other Real Estate Property",
      "General Rental Centers",
      "Passenger Car Leasing",
      "Commercial Air, Rail, and Water Transportation Equipment Rental and Leasing",
      "Truck, Utility Trailer, and RV (Recreational Vehicle) Rental and Leasing",
      "Home Health Equipment Rental",
      "Lessors of Miniwarehouses and Self-Storage Units",
      "Formal Wear and Costume Rental",
      "Other Commercial and Industrial Machinery and Equipment Rental and Leasing",
      "All Other Consumer Goods Rental",
      "Passenger Car Rental",
      "Residential Property Managers",
      "Recreational Goods Rental",
      "Office Machinery and Equipment Rental and Leasing",
      "Lessors of Residential Buildings and Dwellings",
      "Consumer Electronics and Appliances Rental",
      "Offices of Real Estate Appraisers",
      "Offices of Real Estate Agents and Brokers",
      "Construction, Mining, and Forestry Machinery and Equipment Rental and Leasing",
      "Other Activities Related to Real Estate",
    ],
  },
  {
    "No Classification": ["No Classification"],
  },
];
